
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
from views_shard_server_debug import *
from views_job_db import *
from views_priority_labels import *
from views_snmp import *
from views_waf_policy import *
from views_nsx import *
from views_network_policy import *
from views_vi_mgr import *
from views_metrics_mgr import *
from views_pool_group import *
from views_se_properties import *
from views_ipam_dns_provider_profile import *
from views_gslb import *
from views_waf_policy_psm_group import *
from views_health_monitor import *
from views_se_group import *
from views_network import *
from views_autoscale_mgr import *
from views_alerts import *
from views_custom_ipam_dns_profile import *
from views_system import *
from views_vs_datascript import *
from views_application import *
from views_network_profile import *
from views_dns_policy import *
from views_nat_policy import *
from views_error_page import *
from views_match import *
from views_debug_controller import *
from views_transaction_stats import *
from views_controller_properties import *
from views_debug_se import *
from views_traffic_clone_profile import *
from views_webhook import *
from views_auth import *
from views_hsm import *
from views_ssl import *
from views_sso import *
from views_application_persistence_profile import *
from views_l4_policy import *
from views_vrf import *
from views_scheduler import *
from views_apic import *
from views_se_datastore_debug import *
from views_waf_profile import *
from views_pool import *
from views_micro_service import *
from views_security_policy import *
from views_server_autoscale import *
from views_placement import *
from views_protocol_parser import *
from views_application_profile import *
from views_pool_group_deployment_policy import *
from views_analytics_profile import *
from views_cloud_properties import *
from views_application_policy import *
from views_django import *
from views_se_policy import *
from views_security_mgr import *
from views_vs import *
from views_log import *
from views_sc import *
from views_secure_channel import *
from views_backup import *
from views_se import *
