
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *
from models_common import *
from models_events import *
from models_log_common import *
from models_metrics_query import *

from models_snmp import *
REALTIME = 1
ROLLINGWINDOW = 2
WATERMARK = 3
AlertCategoryChoices = (
    (REALTIME, 'REALTIME'),
    (ROLLINGWINDOW, 'ROLLINGWINDOW'),
    (WATERMARK, 'WATERMARK'),
)
ALERT_EMAIL_CONFIG_AVI = 1
AlertEmailConfigDefaultsChoices = (
    (ALERT_EMAIL_CONFIG_AVI, 'ALERT_EMAIL_CONFIG_AVI'),
)
EVENTS_OBJECT_LIST = 1
METRICS_OBJECT_LIST = 2
AlertObjectListConfigDefaultsChoices = (
    (EVENTS_OBJECT_LIST, 'EVENTS_OBJECT_LIST'),
    (METRICS_OBJECT_LIST, 'METRICS_OBJECT_LIST'),
)
ALERT_OP_LT = 1
ALERT_OP_LE = 2
ALERT_OP_EQ = 3
ALERT_OP_NE = 4
ALERT_OP_GE = 5
ALERT_OP_GT = 6
AlertOperationChoices = (
    (ALERT_OP_LT, 'ALERT_OP_LT'),
    (ALERT_OP_LE, 'ALERT_OP_LE'),
    (ALERT_OP_EQ, 'ALERT_OP_EQ'),
    (ALERT_OP_NE, 'ALERT_OP_NE'),
    (ALERT_OP_GE, 'ALERT_OP_GE'),
    (ALERT_OP_GT, 'ALERT_OP_GT'),
)
ALERT_REASON_NONE = 0
ALERT_REASON_THRESHOLD_EXCEEDED = 1
ALERT_REASON_EVENT_OCCURED = 2
AlertReasonChoices = (
    (ALERT_REASON_NONE, 'ALERT_REASON_NONE'),
    (ALERT_REASON_THRESHOLD_EXCEEDED, 'ALERT_REASON_THRESHOLD_EXCEEDED'),
    (ALERT_REASON_EVENT_OCCURED, 'ALERT_REASON_EVENT_OCCURED'),
)
OPERATOR_AND = 1
OPERATOR_OR = 2
AlertRuleOperatorChoices = (
    (OPERATOR_AND, 'OPERATOR_AND'),
    (OPERATOR_OR, 'OPERATOR_OR'),
)
ALERT_SCRIPT_CONFIG_SE_GRP_FLV_UPD = 1
ALERT_SCRIPT_CONFIG_POSTGRESQL_VACUUM = 2
AlertScriptConfigDefaultsChoices = (
    (ALERT_SCRIPT_CONFIG_SE_GRP_FLV_UPD, 'ALERT_SCRIPT_CONFIG_SE_GRP_FLV_UPD'),
    (ALERT_SCRIPT_CONFIG_POSTGRESQL_VACUUM, 'ALERT_SCRIPT_CONFIG_POSTGRESQL_VACUUM'),
)
CONN_LOGS = 0
APP_LOGS = 1
EVENT_LOGS = 2
METRICS = 3
AlertSourceChoices = (
    (CONN_LOGS, 'CONN_LOGS'),
    (APP_LOGS, 'APP_LOGS'),
    (EVENT_LOGS, 'EVENT_LOGS'),
    (METRICS, 'METRICS'),
)
ALERT_STATE_ON = 0
ALERT_STATE_DISMISSED = 1
ALERT_STATE_THROTTLED = 2
AlertStateChoices = (
    (ALERT_STATE_ON, 'ALERT_STATE_ON'),
    (ALERT_STATE_DISMISSED, 'ALERT_STATE_DISMISSED'),
    (ALERT_STATE_THROTTLED, 'ALERT_STATE_THROTTLED'),
)
ALERT_SYSLOG_CONFIG_AVI = 1
AlertSyslogConfigDefaultsChoices = (
    (ALERT_SYSLOG_CONFIG_AVI, 'ALERT_SYSLOG_CONFIG_AVI'),
)
SYSLOG_LEGACY = 1
SYSLOG_RFC5424 = 2
SYSLOG_JSON = 3
SyslogFormatChoices = (
    (SYSLOG_LEGACY, 'SYSLOG_LEGACY'),
    (SYSLOG_RFC5424, 'SYSLOG_RFC5424'),
    (SYSLOG_JSON, 'SYSLOG_JSON'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.alerts_pb2 import AlertObjectList as AlertObjectListProto

from models_common import Tenant


class AlertObjectList (models.Model, GenBase):
    pb_class = AlertObjectListProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'alertobjectlist-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(AlertObjectList, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(AlertObjectList, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(AlertObjectList, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = AlertObjectListProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="alertobjectlist_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '72cc2365f9c64954'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.alerts_pb2 import AlertSyslogConfig as AlertSyslogConfigProto

from models_common import Tenant


class AlertSyslogConfig (models.Model, GenBase):
    pb_class = AlertSyslogConfigProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'alertsyslogconfig-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(AlertSyslogConfig, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(AlertSyslogConfig, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(AlertSyslogConfig, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = AlertSyslogConfigProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="alertsyslogconfig_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'c88b83624e8b4a0d'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.alerts_pb2 import AlertEmailConfig as AlertEmailConfigProto

from models_common import Tenant


class AlertEmailConfig (models.Model, GenBase):
    pb_class = AlertEmailConfigProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'alertemailconfig-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(AlertEmailConfig, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(AlertEmailConfig, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(AlertEmailConfig, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = AlertEmailConfigProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="alertemailconfig_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '137bd115efbc45c6'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.alerts_pb2 import AlertScriptConfig as AlertScriptConfigProto

from models_common import Tenant


class AlertScriptConfig (models.Model, GenBase):
    pb_class = AlertScriptConfigProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'alertscriptconfig-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(AlertScriptConfig, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(AlertScriptConfig, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(AlertScriptConfig, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = AlertScriptConfigProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="alertscriptconfig_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '1ac150dcfae94f85'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.alerts_pb2 import ActionGroupConfig as ActionGroupConfigProto

from models_common import Tenant


class ActionGroupConfig (models.Model, GenBase):
    pb_class = ActionGroupConfigProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'actiongroupconfig-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(ActionGroupConfig, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(ActionGroupConfig, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(ActionGroupConfig, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = ActionGroupConfigProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="actiongroupconfig_tenant_ref", on_delete=models.PROTECT)
    email_config_ref_b0e4e5d3cb174153_ref = models.ForeignKey(AlertEmailConfig, null=True, blank=True, related_name="actiongroupconfig_email_config_ref_b0e4e5d3cb174153", on_delete=models.PROTECT)
    syslog_config_ref_03f1dee1d2c445ba_ref = models.ForeignKey(AlertSyslogConfig, null=True, blank=True, related_name="actiongroupconfig_syslog_config_ref_03f1dee1d2c445ba", on_delete=models.PROTECT)
    action_script_config_ref_9a9e3eb5d2ab4119_ref = models.ForeignKey(AlertScriptConfig, null=True, blank=True, related_name="actiongroupconfig_action_script_config_ref_9a9e3eb5d2ab4119", on_delete=models.PROTECT)
    snmp_trap_profile_ref_0fd0fc42d8814adb_ref = models.ForeignKey(SnmpTrapProfile, null=True, blank=True, related_name="actiongroupconfig_snmp_trap_profile_ref_0fd0fc42d8814adb", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.email_config_uuid': ('refers_to', u'AlertEmailConfig', 'b0e4e5d3cb174153'),
        'root.snmp_trap_profile_uuid': ('refers_to', u'SnmpTrapProfile', '0fd0fc42d8814adb'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'aa8bf25ebd394ebe'),
        'root.action_script_config_uuid': ('refers_to', u'AlertScriptConfig', '9a9e3eb5d2ab4119'),
        'root.syslog_config_uuid': ('refers_to', u'AlertSyslogConfig', '03f1dee1d2c445ba'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.alerts_pb2 import AlertConfig as AlertConfigProto

from models_common import Tenant


class AlertConfig (models.Model, GenBase):
    pb_class = AlertConfigProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'alertconfig-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(AlertConfig, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(AlertConfig, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(AlertConfig, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = AlertConfigProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('enabled')
        if self.enabled is not None:
            pb.enabled = self.enabled
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    enabled = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="alertconfig_tenant_ref", on_delete=models.PROTECT)
    action_group_ref_54ae50331ada4524_ref = models.ForeignKey(ActionGroupConfig, null=True, blank=True, related_name="alertconfig_action_group_ref_54ae50331ada4524", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '2348ecfd570741de'),
        'root.action_group_uuid': ('refers_to', u'ActionGroupConfig', '54ae50331ada4524'),
        'root.obj_uuid': ('disp_hyperlink_to', u'auto', 'b84cf5a6a28648b2'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.alerts_pb2 import Alert as AlertProto



class Alert (models.Model, GenBase):
    pb_class = AlertProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'alert-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(Alert, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(Alert, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(Alert, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = AlertProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.alert_config_uuid = self.alert_config_ref
        pb.level = self.level
        pb.state = self.state
        pb.timestamp = self.timestamp
        pb.obj_uuid = self.obj_ref
        pb.ClearField('related_uuids')
        if self.related_refs is not None:
            for uuid in self.related_refs[:-1].split(","):
                pb.related_uuids.append(uuid)
        pb.ClearField('event_pages')
        if self.event_pages is not None:
            for s in self.event_pages[:-1].split(","):
                pb.event_pages.append(s)
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    alert_config_ref = models.TextField(null=False, blank=False)
    level = models.IntegerField(max_length=100, choices=AlertLevelChoices, null=False, blank=False)
    state = models.IntegerField(max_length=100, choices=AlertStateChoices, null=False, blank=False)
    timestamp = models.FloatField(null=False, blank=False)
    obj_ref = models.TextField(null=False, blank=False)
    related_refs = models.TextField(null=True, blank=True)
    event_pages = models.TextField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="alert_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_failed': ('hyperlink_to', u'ServiceEngine', '350220604eb44d06'),
        'root.metric_info.time_series.series.header.tenant_uuid': ('hyperlink_to', u'auto', '37d279361e494ade'),
        'root.events.event_details.se_vnic_up_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', 'f90bf80d80224556'),
        'root.events.event_details.vs_fsm_details.vs_rt.datapath_debug.se_params.se_uuids': ('disp_hyperlink_to', u'ServiceEngine', 'f8ec06d25bb1499a'),
        'root.events.event_details.rebalance_scaleout_details.scaleout_params.to_host_uuid': ('hyperlink_to', u'VIMgrHostRuntime', '236138f463964c20'),
        'root.events.event_details.se_geo_db_details.se_uuid': ('hyperlink_to', u'ServiceEngine', 'c11bf6d320b240cc'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.discovered_networks.network_uuid': ('hyperlink_to', u'Network', '2b5f8474044a4c8c'),
        'root.events.event_details.glb_info.site.rxed_site_hs.datapath_gsinfo.services.override_network_profile_uuid': ('refers_to', u'NetworkProfile', '019b3bd48d894b28'),
        'root.events.event_details.se_hm_pool_details.virtual_service': ('hyperlink_to', u'VirtualService', 'a05364c850964d4e'),
        'root.events.event_details.se_vs_fault_event_details.virtual_service': ('hyperlink_to', u'VirtualService', '1970f2664a55475b'),
        'root.events.event_details.glb_info.site.rxed_site_hs.datapath_gsinfo.services.override_application_profile_uuid': ('refers_to', u'ApplicationProfile', '53175c24a30b4339'),
        'root.events.event_details.se_pool_lb_details.virtual_service': ('hyperlink_to', u'VirtualService', '18cd049bc0384668'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.ssl_profile_selectors.ssl_profile_uuid': ('refers_to', u'SSLProfile', '3ba35b963b5f4286'),
        'root.events.event_details.vs_scalein_details.se_assigned.uuid': ('hyperlink_to', u'ServiceEngine', '4955a06622bf4eb3'),
        'root.events.event_details.se_ip_removed_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', '1f66fae9ada04c29'),
        'root.events.event_details.rebalance_migrate_details.migrate_params.from_se_uuid': ('hyperlink_to', u'ServiceEngine', 'd7dcc28258844b92'),
        'root.events.event_details.server_autoscaleout_info.pool_uuid': ('disp_hyperlink_to', u'Pool', 'fe0cf8bc8ba8407b'),
        'root.events.event_details.all_seupgrade_event_details.request.se_group_uuids': ('hyperlink_to', u'ServiceEngineGroup', '2de8bd95386742f1'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.content_rewrite.rewritable_content_uuid': ('refers_to', u'StringGroup', '9ba6f5a31529424c'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.saml_sp_config.signing_ssl_key_and_certificate_uuid': ('refers_to', u'SSLKeyAndCertificate', '7e0dddaee622490a'),
        'root.events.event_details.se_licensed_bandwdith_exceeded_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', '57f399b6d9964ef6'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.network_profile_uuid': ('refers_to', u'NetworkProfile', '6cf3c0cda845477e'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.analytics_policy.client_log_filters.client_ip.group_uuids': ('refers_to', u'IpAddrGroup', '042098a728e646a1'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy.tenant_uuid': ('belongs_to', u'Tenant', 'c9a736145fcf4277'),
        'root.events.event_details.vs_fsm_details.vs_rt.datapath_debug.tenant_uuid': ('belongs_to', u'Tenant', 'a299d7c0f1484be2'),
        'root.events.event_details.vs_fsm_details.vs_rt.vip_runtime.scalein_request.from_se_uuid': ('hyperlink_to', u'ServiceEngine', '425296fc93954727'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.network_security_policy_uuid': ('refers_to', u'NetworkSecurityPolicy', 'cc9c9ba9fd934a97'),
        'root.events.event_details.seupgrade_scalein_details.scalein_params.from_se_uuid': ('hyperlink_to', u'ServiceEngine', 'de654f4f6e144873'),
        'root.events.event_details.se_ip_added_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', '23d960d58e1d44ca'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_poweredoff_at_start': ('hyperlink_to', u'ServiceEngine', '1bb3fee8e1b748a1'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.vsvip_uuid': ('hyperlink_to', u'VsVip', '81e70c28e47d48b2'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.pool_group_uuid': ('refers_to', u'PoolGroup', 'a4260326167a4926'),
        'root.events.event_details.se_pool_lb_details.pool': ('hyperlink_to', u'Pool', '2d419166a674435c'),
        'root.events.event_details.se_memory_limit_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', '9a41ee7290704159'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', '9ad22fcac59a4966'),
        'root.events.event_details.se_hm_gsgroup_details.gslb_service': ('hyperlink_to', u'GslbService', 'dc65e1424e8c4213'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.server_network_profile_uuid': ('refers_to', u'NetworkProfile', '3e94c18bcf2d4937'),
        'root.events.event_details.seupgrade_migrate_details.migrate_params.to_se_uuid': ('hyperlink_to', u'ServiceEngine', '7d256a40d01c47b1'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.se_with_vs_scaledout': ('hyperlink_to', u'ServiceEngine', '9d821f1aab5a4ecb'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.tenant_uuid': ('belongs_to', u'Tenant', '95933f39c6d347e1'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.vip.discovered_networks.network_uuid': ('hyperlink_to', u'Network', '51afe18178d4454a'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_errors.vs_uuid': ('hyperlink_to', u'VirtualService', '8c89b3c8a1e64808'),
        'root.events.event_details.se_hb_event_details.se_uuid1': ('hyperlink_to', u'ServiceEngine', '875b133ed70e4d26'),
        'root.events.event_details.se_hb_event_details.se_uuid2': ('hyperlink_to', u'ServiceEngine', '7888efc654f243dd'),
        'root.events.event_details.metric_threshold_up_details.pool_uuid': ('disp_hyperlink_to', u'auto', 'c17872d9bb944c74'),
        'root.metric_info.time_series.series.header.entity_uuid': ('hyperlink_to', u'auto', '654d384b4e1b42c5'),
        'root.events.event_details.rebalance_scalein_details.scalein_params.from_se_uuid': ('hyperlink_to', u'ServiceEngine', 'eb33b1ef635e46ba'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_errors.to_se_uuid': ('hyperlink_to', u'ServiceEngine', 'cb0d167eaa214923'),
        'root.events.event_details.glb_info.gslb_runtime.site.rxed_site_hs.controller_gsinfo.services.override_network_profile_uuid': ('refers_to', u'NetworkProfile', 'c6eb891c2c334115'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.vh_parent_vs_uuid': ('hyperlink_to', u'VirtualService', 'b9020449268f4dcd'),
        'root.metric_info.time_series.series.header.dimension_data.dimension_id': ('hyperlink_to', u'auto', 'eeb700c4048948bd'),
        'root.events.event_details.vs_scaleout_details.scale_status.vip_placement_resolution_info.networks.network_uuid': ('hyperlink_to', u'Network', '1220754cc47f49c3'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.se_with_no_vs': ('hyperlink_to', u'ServiceEngine', 'e493237cfc9c4d61'),
        'root.events.event_details.server_autoscaleout_complete_info.launch_config_uuid': ('hyperlink_to', u'auto', '258a5e4328c84781'),
        'root.events.event_details.server_autoscaleout_complete_info.pool_uuid': ('disp_hyperlink_to', u'Pool', '6dd10d7f2607461f'),
        'root.related_uuids': ('hyperlink_to', u'auto', '2e107bcd3de54905'),
        'root.events.event_details.server_autoscalein_info.alertconfig_uuid': ('disp_hyperlink_to', u'AlertConfig', '94db581c150f4ba6'),
        'root.events.event_details.vs_scaleout_details.se_assigned.uuid': ('hyperlink_to', u'ServiceEngine', 'fab9a9cc8dfc4bcd'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.vip.network_uuid': ('hyperlink_to', u'Network', '1b3879b10ba84899'),
        'root.events.event_details.se_hm_pool_details.server.shm.health_monitor': ('hyperlink_to', u'HealthMonitor', '4475f4ccde474530'),
        'root.events.event_details.vs_fsm_details.vs_rt.datapath_debug.cloud_uuid': ('belongs_to', u'Cloud', '1bf8324e804049cd'),
        'root.events.event_details.gs_info.gs_runtime.groups.members.services.override_network_profile_uuid': ('refers_to', u'NetworkProfile', '0e80efb18e1d4da1'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.network_uuid': ('hyperlink_to', u'Network', '3e6c204e67644f98'),
        'root.events.event_details.se_vs_fault_event_details.service_engine': ('hyperlink_to', u'ServiceEngine', '8bbab78a449f470e'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_in_progress': ('hyperlink_to', u'ServiceEngine', '71e9685051bd4c7a'),
        'root.events.event_details.glb_info.site.rxed_site_hs.controller_gsinfo.services.override_network_profile_uuid': ('refers_to', u'NetworkProfile', '73a98eec0d564d19'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy.authentication_policy.authn_rules.match.client_ip.group_uuids': ('refers_to', u'IpAddrGroup', 'd9735424574c431d'),
        'root.events.event_details.aws_asg_notif_details.pool_uuid': ('disp_hyperlink_to', u'Pool', 'ee7e4f6f5d5f48b7'),
        'root.events.event_details.rebalance_scaleout_details.scaleout_params.to_se_uuid': ('hyperlink_to', u'ServiceEngine', '42f54828b1dc48b5'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_skip_suspended': ('hyperlink_to', u'ServiceEngine', 'ef5f112090f14644'),
        'root.events.event_details.disable_se_migrate_details.migrate_params.to_se_uuid': ('hyperlink_to', u'ServiceEngine', 'fc66719e01634b3b'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_disconnected_at_start': ('hyperlink_to', u'ServiceEngine', '7206a4782b084543'),
        'root.events.event_details.seupgrade_scaleout_details.scaleout_params.to_se_uuid': ('hyperlink_to', u'ServiceEngine', 'acdbc8ff2db84bb6'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy.authentication_policy.authn_rules.match.path.string_group_uuids': ('refers_to', u'StringGroup', '992a0565fc8b4d7f'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_errors.se_uuid': ('hyperlink_to', u'ServiceEngine', '3f93277471d545e2'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.services.override_application_profile_uuid': ('refers_to', u'ApplicationProfile', '2e09e0171f634c96'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.se_upgrade_skip_suspended': ('hyperlink_to', u'ServiceEngine', '8a56a7400cad4ed2'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.http_policies.http_policy_set_uuid': ('refers_to', u'HTTPPolicySet', 'cb15c55b196340d7'),
        'root.events.event_details.glb_info.site.rxed_site_hs.controller_gsinfo.services.override_application_profile_uuid': ('refers_to', u'ApplicationProfile', '9dc8d603b8c24271'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.vs_migrate_in_progress_uuid': ('hyperlink_to', u'VirtualService', 'f5abe828d2894183'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sp_pool_uuids': ('refers_to', u'Pool', '8d59f5d2b10d4771'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_already_upgraded_at_start': ('hyperlink_to', u'ServiceEngine', '882fcc85938444b5'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_suspended': ('hyperlink_to', u'ServiceEngine', 'aeb349254b484288'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.error_page_profile_uuid': ('refers_to', u'ErrorPageProfile', 'e7a7e30d46e94f86'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.analytics_policy.client_log_filters.uri.string_group_uuids': ('refers_to', u'StringGroup', '739f89d0edd54bcb'),
        'root.events.event_details.vs_fsm_details.vs_rt.vip_runtime.migrate_request.from_se_uuid': ('hyperlink_to', u'ServiceEngine', '5d978174470a4212'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_errors.se_group_uuid': ('hyperlink_to', u'ServiceEngineGroup', 'afc6d5ff69c241a7'),
        'root.events.event_details.pool_deployment_failure_info.curr_in_service_pool_name': ('disp_hyperlink_to', u'Pool', '0f48f58ded7d486d'),
        'root.events.event_details.vs_migrate_details.se_assigned.uuid': ('hyperlink_to', u'ServiceEngine', '60d57806e69b463d'),
        'root.events.event_details.rebalance_migrate_details.migrate_params.to_host_uuid': ('hyperlink_to', u'VIMgrHostRuntime', 'a094382fa63749af'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.analytics_profile_uuid': ('refers_to', u'AnalyticsProfile', '68b70b709084441d'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.vs_scaleout_in_progress_uuid': ('hyperlink_to', u'VirtualService', 'a5bc5fd2033640d6'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy.authorization_policy.authz_rules.match.attr_matches.attribute_value_list.string_group_uuids': ('refers_to', u'StringGroup', '098c454990fa47d8'),
        'root.events.event_details.vs_scalein_details.scale_status.vip_placement_resolution_info.networks.network_uuid': ('hyperlink_to', u'Network', '4d092641048043d1'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.vs_scalein_in_progress_uuid': ('hyperlink_to', u'VirtualService', '695613e970b644da'),
        'root.events.event_details.vs_migrate_details.scale_status.vip_placement_resolution_info.networks.network_uuid': ('hyperlink_to', u'Network', 'b67ce4eddc344f8d'),
        'root.events.event_details.vs_fsm_details.vs_rt.vip_runtime.last_scale_status.vip_placement_resolution_info.networks.network_uuid': ('hyperlink_to', u'Network', 'd4ec3c05389e4d89'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.vip.ipam_network_subnet.network_uuid': ('hyperlink_to', u'Network', 'c8843b59763845fc'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.vs_datascripts.vs_datascript_set_uuid': ('refers_to', u'VSDataScriptSet', 'd4a4282a23c54fdb'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.services.override_network_profile_uuid': ('refers_to', u'NetworkProfile', '2f48568328c84deb'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.service_pool_select.service_pool_group_uuid': ('refers_to', u'PoolGroup', 'fc2c944c16494e58'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.service_pool_select.service_pool_uuid': ('refers_to', u'Pool', '1f88811003df4505'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.cloud_uuid': ('belongs_to', u'Cloud', '7a345026123c4b87'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.ssl_key_and_certificate_uuids': ('refers_to', u'SSLKeyAndCertificate', '8cad4b4d261b43c8'),
        'root.events.event_details.pool_deployment_success_info.prev_in_service_pool_uuid': ('disp_hyperlink_to', u'Pool', 'f08b5c973ff04333'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_ip_missing_at_start': ('hyperlink_to', u'ServiceEngine', '1033b16b816143c4'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.vs_errors.se_group_uuid': ('hyperlink_to', u'ServiceEngineGroup', '767924ebf80d49eb'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_retry_failed': ('hyperlink_to', u'ServiceEngine', '8423f9eb87c742d2'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.vrf_context_uuid': ('weak_refers_to', u'VrfContext', 'b595b4f1eb8d47a4'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.tenant_uuid': ('hyperlink_to', u'Tenant', '096b351749f34dda'),
        'root.alert_config_uuid': ('hyperlink_to', u'AlertConfig', 'fc3ab6f1146a4ece'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.dns_policies.dns_policy_uuid': ('refers_to', u'DnsPolicy', '99a3275db4cc4255'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.analytics_policy.client_insights_sampling.client_ip.group_uuids': ('refers_to', u'IpAddrGroup', 'f488c26fd84a43de'),
        'root.events.event_details.glb_info.gslb_runtime.site.rxed_site_hs.datapath_gsinfo.services.override_application_profile_uuid': ('refers_to', u'ApplicationProfile', 'c61a05d7751b4ce4'),
        'root.events.event_details.server_autoscale_failed_info.pool_uuid': ('disp_hyperlink_to', u'Pool', '790bedb243264c95'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.discovered_network_uuid': ('hyperlink_to', u'Network', '5b2483af53fe4a68'),
        'root.events.event_details.metric_threshold_up_details.entity_uuid': ('disp_hyperlink_to', u'auto', '901cb7c25ddb4f92'),
        'root.events.event_details.vs_awaitingse_details.se_assigned.uuid': ('hyperlink_to', u'ServiceEngine', '47ccb15cb1d04a7c'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy_uuid': ('refers_to', u'SSOPolicy', 'fced03bbb1164f17'),
        'root.events.event_details.se_hm_pool_details.pool': ('hyperlink_to', u'Pool', '20c5337b5cdd4aed'),
        'root.metric_info.time_series.series.header.pool_uuid': ('hyperlink_to', u'auto', '8a452bd20aff424b'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.analytics_policy.client_insights_sampling.sample_uris.string_group_uuids': ('refers_to', u'StringGroup', 'fc6d9d071c494beb'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_retry_in_progress': ('hyperlink_to', u'ServiceEngine', '10d995db4b854826'),
        'root.obj_uuid': ('hyperlink_to', u'auto', '27c5cd20ee0a4ac7'),
        'root.metric_info.time_series.entity_uuid': ('hyperlink_to', u'auto', '124180124d4945a0'),
        'root.events.event_details.se_hm_vs_details.virtual_service': ('hyperlink_to', u'VirtualService', '95b2206240c64263'),
        'root.events.event_details.vs_fsm_details.vs_rt.vip_runtime.scale_status.vip_placement_resolution_info.networks.network_uuid': ('hyperlink_to', u'Network', '56bedde31de24113'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_not_started': ('hyperlink_to', u'ServiceEngine', '6c1a46d6548b4d8e'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.se_upgrade_suspended': ('hyperlink_to', u'ServiceEngine', '0d547b5919d54280'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.topology_policies.dns_policy_uuid': ('refers_to', u'DnsPolicy', '809db53a5d774a28'),
        'root.events.event_details.disable_se_migrate_details.migrate_params.to_host_uuid': ('hyperlink_to', u'VIMgrHostRuntime', '84dcd1572cbb4fb5'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.vs_errors.vs_uuid': ('hyperlink_to', u'VirtualService', 'c050ee5ad1af4337'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.traffic_clone_profile_uuid': ('refers_to', u'TrafficCloneProfile', '0abd8f19bfd1408d'),
        'root.events.event_details.glb_info.gslb_runtime.site.rxed_site_hs.datapath_gsinfo.services.override_network_profile_uuid': ('refers_to', u'NetworkProfile', '5e5099cec54c49e9'),
        'root.events.event_details.server_autoscalein_info.pool_uuid': ('disp_hyperlink_to', u'Pool', 'b3e70857935a4fdf'),
        'root.events.event_details.se_ipfailure_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', 'ec9bf7fe98884046'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.application_profile_uuid': ('refers_to', u'ApplicationProfile', '046b4ad4f9a145c1'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_completed': ('hyperlink_to', u'ServiceEngine', 'e10e29877ca84a56'),
        'root.events.event_details.vs_initialplacement_details.se_assigned.uuid': ('hyperlink_to', u'ServiceEngine', '407bb8c43a014403'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.vs_errors.tenant_uuid': ('hyperlink_to', u'Tenant', '8fdddb8c6c41463d'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy.authorization_policy.authz_rules.match.path.string_group_uuids': ('refers_to', u'StringGroup', '81960defdf614085'),
        'root.events.event_details.se_persistence_details.pool': ('hyperlink_to', u'Pool', '2cc302a692ae4955'),
        'root.events.event_details.vs_fsm_details.vs_rt.vip_runtime.migrate_request.to_se_uuid': ('hyperlink_to', u'ServiceEngine', '3421a89874f34f16'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy.authentication_policy.auth_profile_uuid': ('refers_to', u'AuthProfile', 'd20207fb64c149bb'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.disrupted_vs_uuid': ('hyperlink_to', u'VirtualService', '676f09e7f3a74058'),
        'root.events.event_details.server_autoscalein_complete_info.pool_uuid': ('disp_hyperlink_to', u'Pool', 'd20317df51cc45f1'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.pool_uuid': ('refers_to', u'Pool', '264d926383834015'),
        'root.events.event_details.server_autoscaleout_info.alertconfig_uuid': ('disp_hyperlink_to', u'AlertConfig', '19e96b6e14954def'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.client_auth.request_uri_path.string_group_uuids': ('refers_to', u'StringGroup', 'a7993103102f445a'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.l4_policies.l4_policy_set_uuid': ('refers_to', u'L4PolicySet', 'bcafb19c4eec4cc6'),
        'root.events.event_details.vs_fsm_details.vs_rt.vip_runtime.se_list.se_uuid': ('hyperlink_to', u'ServiceEngine', '2723db4f1d974cb0'),
        'root.events.event_details.pool_deployment_failure_info.curr_in_service_pool_uuid': ('disp_hyperlink_to', u'Pool', '19b9eefc80d84d85'),
        'root.events.event_details.seupgrade_scaleout_details.scaleout_params.to_host_uuid': ('hyperlink_to', u'VIMgrHostRuntime', 'a310fd8d130445b4'),
        'root.events.event_details.se_geo_db_details.virtual_service': ('hyperlink_to', u'VirtualService', 'ea624634ecf14d1b'),
        'root.events.event_details.se_hm_gsgroup_details.gsmember.shm.health_monitor': ('hyperlink_to', u'HealthMonitor', '7d04ce81e27d44a1'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.ipam_network_subnet.network_uuid': ('hyperlink_to', u'Network', '43a674d12f9e450d'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.ssl_profile_uuid': ('refers_to', u'SSLProfile', 'cc07c760d1b14c7e'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy.authentication_policy.default_auth_profile_uuid': ('refers_to', u'AuthProfile', '81b3e506a17b405f'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.se_with_vs_not_scaledout': ('hyperlink_to', u'ServiceEngine', 'ac4c624273f6491e'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.client_auth.auth_profile_uuid': ('refers_to', u'AuthProfile', 'ceff3d2120804865'),
        'root.events.event_details.vs_fsm_details.vs_rt.vip_runtime.migrate_request.to_host_uuid': ('hyperlink_to', u'VIMgrHostRuntime', '8ed3abd1500f4e3b'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.ssl_profile_selectors.client_ip_list.group_uuids': ('refers_to', u'IpAddrGroup', 'e381d19c7fc14174'),
        'root.events.event_details.vs_fsm_details.vs_rt.vh_child_vs_uuid': ('disp_hyperlink_to', u'VirtualService', 'f9d73e9b274748cb'),
        'root.events.event_details.se_geo_db_details.geo_db_profile_uuid': ('hyperlink_to', u'GslbGeoDbProfile', 'b8455447f7fc43c2'),
        'root.metric_info.time_series.series.header.serviceengine_uuid': ('hyperlink_to', u'auto', '69a5b64d920846f2'),
        'root.events.event_details.seupgrade_migrate_details.migrate_params.from_se_uuid': ('hyperlink_to', u'ServiceEngine', '6e4f1bca90e34345'),
        'root.events.event_details.rebalance_migrate_details.migrate_params.to_se_uuid': ('hyperlink_to', u'ServiceEngine', 'd11554b8091844c2'),
        'root.events.related_uuids': ('hyperlink_to', u'auto', 'ce5b24d0cc95430c'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_retry_completed': ('hyperlink_to', u'ServiceEngine', 'b54007a5022347cb'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.waf_policy_uuid': ('refers_to', u'WafPolicy', 'fe3672bc7576401b'),
        'root.events.event_details.glb_info.gslb_runtime.site.rxed_site_hs.controller_gsinfo.services.override_application_profile_uuid': ('refers_to', u'ApplicationProfile', 'a3f2d6f35783498d'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.security_policy_uuid': ('refers_to', u'SecurityPolicy', 'eaf203a6d5a14cda'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.se_group_uuid': ('weak_refers_to', u'ServiceEngineGroup', 'f87df69ce4f140f4'),
        'root.events.event_details.se_ip6_dad_failed_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', 'c78cf61e297f48a7'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.microservice_uuid': ('refers_to', u'MicroService', 'f35a9ed766344a15'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_group_status.se_reboot_in_progress_uuid': ('hyperlink_to', u'ServiceEngine', '16369362db484ef3'),
        'root.events.event_details.gs_info.gs_runtime.groups.members.services.override_application_profile_uuid': ('refers_to', u'ApplicationProfile', '5716f98df1674a7c'),
        'root.events.event_details.system_upgrade_details.upgrade_status.se_state.se_upgrade_errors.from_se_uuid': ('hyperlink_to', u'ServiceEngine', '52b205a013b944e1'),
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.analytics_policy.client_insights_sampling.skip_uris.string_group_uuids': ('refers_to', u'StringGroup', '163f9e4f936b43b1'),
        'root.events.event_details.seupgrade_migrate_details.migrate_params.to_host_uuid': ('hyperlink_to', u'VIMgrHostRuntime', '42c08874340e4600'),
        'root.events.event_details.se_hm_gs_details.gslb_service': ('hyperlink_to', u'GslbService', '6cf9e61d8fdb4007'),
        'root.events.event_details.se_vnic_down_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', '68f121a7ad664544'),
        'root.events.event_details.vs_error_details.se_assigned.uuid': ('hyperlink_to', u'ServiceEngine', '6556eb3b360940b8'),
        'root.events.event_details.disable_se_migrate_details.migrate_params.from_se_uuid': ('hyperlink_to', u'ServiceEngine', '011db3baf2f24a69'),
        'root.events.event_details.se_vnic_tx_queue_stall_event_details.se_uuid': ('hyperlink_to', u'ServiceEngine', '25f24f9039c240af'),
    }
    sensitive_fields = {
        'root.events.event_details.cluster_leader_failover_details.leader_node.password',
        'root.events.event_details.cluster_leader_failover_details.previous_leader_node.password',
    }
    pb_check_fields = {
        'root.app_events.cipher_bytes': 'f_internal',
        'root.events.event_details.se_details.gcp_info.subnet': 'f_immutable',
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.type': 'f_immutable',
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.saml_sp_config.sp_metadata': 'f_readonly',
        'root.events.event_details.all_seupgrade_event_details.request.skip_suspended': 'f_internal',
        'root.events.event_details.se_details.gcp_info.project': 'f_immutable',
        'root.events.event_details.se_details.gcp_info.zone': 'f_immutable',
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.azure_availability_set': 'f_readonly',
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.dns_info.metadata': 'f_readonly',
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.cloud_uuid': 'f_immutable',
        'root.events.event_details.all_seupgrade_event_details.request.resume_from_suspend': 'f_internal',
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sp_pool_uuids': 'f_readonly',
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.vsvip_cloud_config_cksum': 'f_internal',
        'root.events.event_details.se_details.gcp_info.hostname': 'f_immutable',
        'root.events.event_details.se_details.gcp_info.network': 'f_immutable',
        'root.events.event_details.vip_dns_info.dns_info.metadata': 'f_readonly',
        'root.events.event_details.vs_fsm_details.vs_rt.vs_update_pending.sso_policy.authentication_policy.sp_metadata': 'f_readonly',
        'root.events.event_details.vs_fsm_details.vs_rt.datapath_debug.cloud_uuid': 'f_immutable',
    }
    disable_cache = True

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

