
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from models_se_runtime import *

from models_common_legacy import *
from models_common import *
from models_options_legacy import *
from models_options import *
from models_se_legacy import *
from models_se import *
from models_vi_mgr_runtime_legacy import *
from models_vi_mgr_runtime import *

SE_DEREG_HB_FAILURE = 0
SE_DEREG_POWERED_OFF = 1
SE_DEREG_SUSPENDED = 2
SE_DEREG_FATAL_ERROR = 3
SE_DEREG_UNREACHABLE = 4
SE_DEREG_VM_DELETED = 5
SE_DEREG_REBOOTED = 6
SE_DEREG_PURGE = 7
SE_DEREG_HEALTH_CHECK = 8
SE_DEREG_VINFRA_POWERED_OFF = 9
SE_DEREG_UPGRADING = 10
SE_DEREG_DP_HB_FAIL = 11
SE_DEREG_DISABLED_FORCE = 12
SE_DEREG_SWITCHOVER_FORCE = 13
SE_DEREG_NEWLY_DISCOVERED = 14
SE_DEREG_SE_GRP_CHANGE = 15
SeDeregReasonCodeChoices = (
    (SE_DEREG_HB_FAILURE, 'SE_DEREG_HB_FAILURE'),
    (SE_DEREG_POWERED_OFF, 'SE_DEREG_POWERED_OFF'),
    (SE_DEREG_SUSPENDED, 'SE_DEREG_SUSPENDED'),
    (SE_DEREG_FATAL_ERROR, 'SE_DEREG_FATAL_ERROR'),
    (SE_DEREG_UNREACHABLE, 'SE_DEREG_UNREACHABLE'),
    (SE_DEREG_VM_DELETED, 'SE_DEREG_VM_DELETED'),
    (SE_DEREG_REBOOTED, 'SE_DEREG_REBOOTED'),
    (SE_DEREG_PURGE, 'SE_DEREG_PURGE'),
    (SE_DEREG_HEALTH_CHECK, 'SE_DEREG_HEALTH_CHECK'),
    (SE_DEREG_VINFRA_POWERED_OFF, 'SE_DEREG_VINFRA_POWERED_OFF'),
    (SE_DEREG_UPGRADING, 'SE_DEREG_UPGRADING'),
    (SE_DEREG_DP_HB_FAIL, 'SE_DEREG_DP_HB_FAIL'),
    (SE_DEREG_DISABLED_FORCE, 'SE_DEREG_DISABLED_FORCE'),
    (SE_DEREG_SWITCHOVER_FORCE, 'SE_DEREG_SWITCHOVER_FORCE'),
    (SE_DEREG_NEWLY_DISCOVERED, 'SE_DEREG_NEWLY_DISCOVERED'),
    (SE_DEREG_SE_GRP_CHANGE, 'SE_DEREG_SE_GRP_CHANGE'),
)
SE_POWER_OFF = 1
SE_POWER_ON = 2
SE_SUSPENDED = 3
SePowerStateChoices = (
    (SE_POWER_OFF, 'SE_POWER_OFF'),
    (SE_POWER_ON, 'SE_POWER_ON'),
    (SE_SUSPENDED, 'SE_SUSPENDED'),
)
VNIC_STATE_UNKNOWN = 1
VNIC_STATE_UP = 2
VNIC_STATE_DOWN = 3
VnicStateChoices = (
    (VNIC_STATE_UNKNOWN, 'VNIC_STATE_UNKNOWN'),
    (VNIC_STATE_UP, 'VNIC_STATE_UP'),
    (VNIC_STATE_DOWN, 'VNIC_STATE_DOWN'),
)
