
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from models_gslb import *

from models_options_legacy import *
from models_options import *
from models_common_legacy import *
from models_common import *
from models_health_monitor_legacy import *
from models_health_monitor import *
from models_application_persistence_profile_legacy import *
from models_application_persistence_profile import *

NO_ERROR = 0
FILE_ERROR = 1
FILE_FORMAT_ERROR = 2
FILE_NO_RESOURCES = 3
GeoDbFailureReasonChoices = (
    (NO_ERROR, 'NO_ERROR'),
    (FILE_ERROR, 'FILE_ERROR'),
    (FILE_FORMAT_ERROR, 'FILE_FORMAT_ERROR'),
    (FILE_NO_RESOURCES, 'FILE_NO_RESOURCES'),
)
GSLB_ALGORITHM_ROUND_ROBIN = 1
GSLB_ALGORITHM_CONSISTENT_HASH = 2
GSLB_ALGORITHM_GEO = 3
GSLB_ALGORITHM_TOPOLOGY = 4
GslbAlgorithmChoices = (
    (GSLB_ALGORITHM_ROUND_ROBIN, 'GSLB_ALGORITHM_ROUND_ROBIN'),
    (GSLB_ALGORITHM_CONSISTENT_HASH, 'GSLB_ALGORITHM_CONSISTENT_HASH'),
    (GSLB_ALGORITHM_GEO, 'GSLB_ALGORITHM_GEO'),
    (GSLB_ALGORITHM_TOPOLOGY, 'GSLB_ALGORITHM_TOPOLOGY'),
)
GSLB_GEODB_FILE_FORMAT_AVI = 1
GSLB_GEODB_FILE_FORMAT_MAXMIND_CITY = 2
GslbGeoDbFileFormatChoices = (
    (GSLB_GEODB_FILE_FORMAT_AVI, 'GSLB_GEODB_FILE_FORMAT_AVI'),
    (GSLB_GEODB_FILE_FORMAT_MAXMIND_CITY, 'GSLB_GEODB_FILE_FORMAT_MAXMIND_CITY'),
)
GSLB_LOCATION_SRC_USER_CONFIGURED = 1
GSLB_LOCATION_SRC_INHERIT_FROM_SITE = 2
GSLB_LOCATION_SRC_FROM_GEODB = 3
GslbGeoLocationSourceChoices = (
    (GSLB_LOCATION_SRC_USER_CONFIGURED, 'GSLB_LOCATION_SRC_USER_CONFIGURED'),
    (GSLB_LOCATION_SRC_INHERIT_FROM_SITE, 'GSLB_LOCATION_SRC_INHERIT_FROM_SITE'),
    (GSLB_LOCATION_SRC_FROM_GEODB, 'GSLB_LOCATION_SRC_FROM_GEODB'),
)
GSLB_HEALTH_MONITOR_PROXY_ALL_MEMBERS = 1
GSLB_HEALTH_MONITOR_PROXY_PRIVATE_MEMBERS = 2
GslbHealthMonitorProxyTypeChoices = (
    (GSLB_HEALTH_MONITOR_PROXY_ALL_MEMBERS, 'GSLB_HEALTH_MONITOR_PROXY_ALL_MEMBERS'),
    (GSLB_HEALTH_MONITOR_PROXY_PRIVATE_MEMBERS, 'GSLB_HEALTH_MONITOR_PROXY_PRIVATE_MEMBERS'),
)
GSLB_IP_PUBLIC = 1
GSLB_IP_PRIVATE = 2
GslbIpAddrTypeChoices = (
    (GSLB_IP_PUBLIC, 'GSLB_IP_PUBLIC'),
    (GSLB_IP_PRIVATE, 'GSLB_IP_PRIVATE'),
)
GSLB_OBJECT_CHANGED = 1
GSLB_OBJECT_UNCHANGED = 2
GSLB_OBJECT_DELETE = 3
GslbObjectStateChoices = (
    (GSLB_OBJECT_CHANGED, 'GSLB_OBJECT_CHANGED'),
    (GSLB_OBJECT_UNCHANGED, 'GSLB_OBJECT_UNCHANGED'),
    (GSLB_OBJECT_DELETE, 'GSLB_OBJECT_DELETE'),
)
GSLB_SERVICE_ALGORITHM_PRIORITY = 1
GSLB_SERVICE_ALGORITHM_GEO = 2
GslbServiceAlgorithmChoices = (
    (GSLB_SERVICE_ALGORITHM_PRIORITY, 'GSLB_SERVICE_ALGORITHM_PRIORITY'),
    (GSLB_SERVICE_ALGORITHM_GEO, 'GSLB_SERVICE_ALGORITHM_GEO'),
)
GSLB_SERVICE_DOWN_RESPONSE_NONE = 0
GSLB_SERVICE_DOWN_RESPONSE_ALL_RECORDS = 1
GSLB_SERVICE_DOWN_RESPONSE_FALLBACK_IP = 2
GSLB_SERVICE_DOWN_RESPONSE_EMPTY = 3
GslbServiceDownResponseTypeChoices = (
    (GSLB_SERVICE_DOWN_RESPONSE_NONE, 'GSLB_SERVICE_DOWN_RESPONSE_NONE'),
    (GSLB_SERVICE_DOWN_RESPONSE_ALL_RECORDS, 'GSLB_SERVICE_DOWN_RESPONSE_ALL_RECORDS'),
    (GSLB_SERVICE_DOWN_RESPONSE_FALLBACK_IP, 'GSLB_SERVICE_DOWN_RESPONSE_FALLBACK_IP'),
    (GSLB_SERVICE_DOWN_RESPONSE_EMPTY, 'GSLB_SERVICE_DOWN_RESPONSE_EMPTY'),
)
GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS = 1
GSLB_SERVICE_HEALTH_MONITOR_ONLY_NON_AVI_MEMBERS = 2
GslbServiceHealthMonitorScopeChoices = (
    (GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS, 'GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS'),
    (GSLB_SERVICE_HEALTH_MONITOR_ONLY_NON_AVI_MEMBERS, 'GSLB_SERVICE_HEALTH_MONITOR_ONLY_NON_AVI_MEMBERS'),
)
GSLB_ACTIVE_MEMBER = 1
GSLB_PASSIVE_MEMBER = 2
SiteMemberTypeChoices = (
    (GSLB_ACTIVE_MEMBER, 'GSLB_ACTIVE_MEMBER'),
    (GSLB_PASSIVE_MEMBER, 'GSLB_PASSIVE_MEMBER'),
)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbHealthMonitorProxy as GslbHealthMonitorProxyProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbGeoLocation as GslbGeoLocationProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbSiteDnsVs as GslbSiteDnsVsProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbSite as GslbSiteProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbThirdPartySite as GslbThirdPartySiteProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import DNSConfig as DNSConfigProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbClientIpAddrGroup as GslbClientIpAddrGroupProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import Gslb as GslbProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbIpAddr as GslbIpAddrProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbPoolMember as GslbPoolMemberProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbPool as GslbPoolProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbServiceDownResponse as GslbServiceDownResponseProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbService as GslbServiceProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbGeoDbFile as GslbGeoDbFileProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbGeoDbEntry as GslbGeoDbEntryProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbGeoDbProfile as GslbGeoDbProfileProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbObj as GslbObjProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbObjectInfo as GslbObjectInfoProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbDnsUpdate as GslbDnsUpdateProto