
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_common import *
from models_options import *
from models_ssl_cipher_enums import *
from models_match import *

SSL_CERTIFICATE_GOOD = 0
SSL_CERTIFICATE_EXPIRY_WARNING = 1
SSL_CERTIFICATE_EXPIRED = 2
SSLCertificateExpiryStatusChoices = (
    (SSL_CERTIFICATE_GOOD, 'SSL_CERTIFICATE_GOOD'),
    (SSL_CERTIFICATE_EXPIRY_WARNING, 'SSL_CERTIFICATE_EXPIRY_WARNING'),
    (SSL_CERTIFICATE_EXPIRED, 'SSL_CERTIFICATE_EXPIRED'),
)
SSL_CERTIFICATE_FINISHED = 0
SSL_CERTIFICATE_PENDING = 1
SSLCertificateStatusChoices = (
    (SSL_CERTIFICATE_FINISHED, 'SSL_CERTIFICATE_FINISHED'),
    (SSL_CERTIFICATE_PENDING, 'SSL_CERTIFICATE_PENDING'),
)
SSL_CERTIFICATE_TYPE_VIRTUALSERVICE = 1
SSL_CERTIFICATE_TYPE_SYSTEM = 2
SSL_CERTIFICATE_TYPE_CA = 3
SSLCertificateTypeChoices = (
    (SSL_CERTIFICATE_TYPE_VIRTUALSERVICE, 'SSL_CERTIFICATE_TYPE_VIRTUALSERVICE'),
    (SSL_CERTIFICATE_TYPE_SYSTEM, 'SSL_CERTIFICATE_TYPE_SYSTEM'),
    (SSL_CERTIFICATE_TYPE_CA, 'SSL_CERTIFICATE_TYPE_CA'),
)
SSL_CLIENT_CERTIFICATE_NONE = 0
SSL_CLIENT_CERTIFICATE_REQUEST = 1
SSL_CLIENT_CERTIFICATE_REQUIRE = 2
SSLClientCertificateModeChoices = (
    (SSL_CLIENT_CERTIFICATE_NONE, 'SSL_CLIENT_CERTIFICATE_NONE'),
    (SSL_CLIENT_CERTIFICATE_REQUEST, 'SSL_CLIENT_CERTIFICATE_REQUEST'),
    (SSL_CLIENT_CERTIFICATE_REQUIRE, 'SSL_CLIENT_CERTIFICATE_REQUIRE'),
)
SSL_PEM = 0
SSL_PKCS12 = 1
SSLFormatChoices = (
    (SSL_PEM, 'SSL_PEM'),
    (SSL_PKCS12, 'SSL_PKCS12'),
)
SSL_KEY_ALGORITHM_RSA = 1
SSL_KEY_ALGORITHM_EC = 2
SSLKeyAlgorithmChoices = (
    (SSL_KEY_ALGORITHM_RSA, 'SSL_KEY_ALGORITHM_RSA'),
    (SSL_KEY_ALGORITHM_EC, 'SSL_KEY_ALGORITHM_EC'),
)
SSL_KEY_EC_CURVE_SECP256R1 = 1
SSL_KEY_EC_CURVE_SECP384R1 = 2
SSL_KEY_EC_CURVE_SECP521R1 = 3
SSLKeyECCurveChoices = (
    (SSL_KEY_EC_CURVE_SECP256R1, 'SSL_KEY_EC_CURVE_SECP256R1'),
    (SSL_KEY_EC_CURVE_SECP384R1, 'SSL_KEY_EC_CURVE_SECP384R1'),
    (SSL_KEY_EC_CURVE_SECP521R1, 'SSL_KEY_EC_CURVE_SECP521R1'),
)
SSL_PROFILE_TYPE_APPLICATION = 1
SSL_PROFILE_TYPE_SYSTEM = 2
SSLProfileTypeChoices = (
    (SSL_PROFILE_TYPE_APPLICATION, 'SSL_PROFILE_TYPE_APPLICATION'),
    (SSL_PROFILE_TYPE_SYSTEM, 'SSL_PROFILE_TYPE_SYSTEM'),
)
SSL_KEY_1024_BITS = 1
SSL_KEY_2048_BITS = 2
SSL_KEY_3072_BITS = 3
SSL_KEY_4096_BITS = 4
SSLRSAKeySizeChoices = (
    (SSL_KEY_1024_BITS, 'SSL_KEY_1024_BITS'),
    (SSL_KEY_2048_BITS, 'SSL_KEY_2048_BITS'),
    (SSL_KEY_3072_BITS, 'SSL_KEY_3072_BITS'),
    (SSL_KEY_4096_BITS, 'SSL_KEY_4096_BITS'),
)
SSL_SCORE_NOT_SECURE = 0
SSL_SCORE_VERY_BAD = 1
SSL_SCORE_BAD = 2
SSL_SCORE_AVERAGE = 3
SSL_SCORE_GOOD = 4
SSL_SCORE_EXCELLENT = 5
SSLScoreChoices = (
    (SSL_SCORE_NOT_SECURE, 'SSL_SCORE_NOT_SECURE'),
    (SSL_SCORE_VERY_BAD, 'SSL_SCORE_VERY_BAD'),
    (SSL_SCORE_BAD, 'SSL_SCORE_BAD'),
    (SSL_SCORE_AVERAGE, 'SSL_SCORE_AVERAGE'),
    (SSL_SCORE_GOOD, 'SSL_SCORE_GOOD'),
    (SSL_SCORE_EXCELLENT, 'SSL_SCORE_EXCELLENT'),
)
SSL_VERSION_SSLV3 = 1
SSL_VERSION_TLS1 = 2
SSL_VERSION_TLS1_1 = 3
SSL_VERSION_TLS1_2 = 4
SSLVersionTypeChoices = (
    (SSL_VERSION_SSLV3, 'SSL_VERSION_SSLV3'),
    (SSL_VERSION_TLS1, 'SSL_VERSION_TLS1'),
    (SSL_VERSION_TLS1_1, 'SSL_VERSION_TLS1_1'),
    (SSL_VERSION_TLS1_2, 'SSL_VERSION_TLS1_2'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.ssl_pb2 import SSLProfile as SSLProfileProto

from models_common import Tenant


class SSLProfile (models.Model, GenBase):
    pb_class = SSLProfileProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'sslprofile-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(SSLProfile, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(SSLProfile, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(SSLProfile, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = SSLProfileProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="sslprofile_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '266fafa7b326435e'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.dhparam': 'f_immutable',
        'root.type': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.ssl_pb2 import CertificateManagementProfile as CertificateManagementProfileProto

from models_common import Tenant


class CertificateManagementProfile (models.Model, GenBase):
    pb_class = CertificateManagementProfileProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'certificatemanagementprofile-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(CertificateManagementProfile, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(CertificateManagementProfile, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(CertificateManagementProfile, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = CertificateManagementProfileProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="certificatemanagementprofile_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '325b35d16b6641cc'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.ssl_pb2 import SSLKeyAndCertificate as SSLKeyAndCertificateProto

from models_common import Tenant


class SSLKeyAndCertificate (models.Model, GenBase):
    pb_class = SSLKeyAndCertificateProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'sslkeyandcertificate-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(SSLKeyAndCertificate, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(SSLKeyAndCertificate, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(SSLKeyAndCertificate, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = SSLKeyAndCertificateProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="sslkeyandcertificate_tenant_ref", on_delete=models.PROTECT)
    certificate_management_profile_ref_b6987ff55628401c_ref = models.ForeignKey(CertificateManagementProfile, null=True, blank=True, related_name="sslkeyandcertificate_certificate_management_profile_ref_b6987ff55628401c", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.hardwaresecuritymodulegroup_uuid': ('hyperlink_to', u'HardwareSecurityModuleGroup', 'afc66bba923242ba'),
        'root.ca_certs.ca_uuid': ('hyperlink_to', u'SSLKeyAndCertificate', '33b64cf20543482b'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'b430afbe88294d0d'),
        'root.certificate_management_profile_uuid': ('weak_refers_to', u'CertificateManagementProfile', 'b6987ff55628401c'),
    }
    sensitive_fields = {
        'root.key',
        'root.key_passphrase',
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.ssl_pb2 import PKIProfile as PKIProfileProto

from models_common import Tenant


class PKIProfile (models.Model, GenBase):
    pb_class = PKIProfileProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'pkiprofile-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(PKIProfile, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(PKIProfile, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(PKIProfile, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = PKIProfileProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('is_federated')
        if self.is_federated is not None:
            pb.is_federated = self.is_federated
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    is_federated = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="pkiprofile_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '7341d7c303374784'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.crls.last_refreshed': 'f_immutable',
        'root.is_federated': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

