
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *

from models_cloud_objects import *
from models_common import *
from models_alerts import *
SCHEDULER_ACTION_RUN_A_SCRIPT = 1
SCHEDULER_ACTION_BACKUP = 2
SchedulerActionChoices = (
    (SCHEDULER_ACTION_RUN_A_SCRIPT, 'SCHEDULER_ACTION_RUN_A_SCRIPT'),
    (SCHEDULER_ACTION_BACKUP, 'SCHEDULER_ACTION_BACKUP'),
)
SCHEDULER_FREQUENCY_UNIT_MIN = 1
SCHEDULER_FREQUENCY_UNIT_HOUR = 2
SCHEDULER_FREQUENCY_UNIT_DAY = 3
SCHEDULER_FREQUENCY_UNIT_WEEK = 4
SCHEDULER_FREQUENCY_UNIT_MONTH = 5
SchedulerFrequencyUnitChoices = (
    (SCHEDULER_FREQUENCY_UNIT_MIN, 'SCHEDULER_FREQUENCY_UNIT_MIN'),
    (SCHEDULER_FREQUENCY_UNIT_HOUR, 'SCHEDULER_FREQUENCY_UNIT_HOUR'),
    (SCHEDULER_FREQUENCY_UNIT_DAY, 'SCHEDULER_FREQUENCY_UNIT_DAY'),
    (SCHEDULER_FREQUENCY_UNIT_WEEK, 'SCHEDULER_FREQUENCY_UNIT_WEEK'),
    (SCHEDULER_FREQUENCY_UNIT_MONTH, 'SCHEDULER_FREQUENCY_UNIT_MONTH'),
)
RUN_MODE_PERIODIC = 1
RUN_MODE_AT = 2
RUN_MODE_NOW = 3
SchedulerRunModeChoices = (
    (RUN_MODE_PERIODIC, 'RUN_MODE_PERIODIC'),
    (RUN_MODE_AT, 'RUN_MODE_AT'),
    (RUN_MODE_NOW, 'RUN_MODE_NOW'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.scheduler_pb2 import BackupConfiguration as BackupConfigurationProto



class BackupConfiguration (models.Model, GenBase):
    pb_class = BackupConfigurationProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'backupconfiguration-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(BackupConfiguration, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(BackupConfiguration, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(BackupConfiguration, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = BackupConfigurationProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="backupconfiguration_tenant_ref", on_delete=models.PROTECT)
    ssh_user_ref_01eab625d43441d7_ref = models.ForeignKey(CloudConnectorUser, null=True, blank=True, related_name="backupconfiguration_ssh_user_ref_01eab625d43441d7", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'ec2ade772bf44096'),
        'root.ssh_user_uuid': ('weak_refers_to', u'CloudConnectorUser', '01eab625d43441d7'),
    }
    sensitive_fields = {
        'root.backup_passphrase',
        'root.aws_access_key',
        'root.aws_secret_access',
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.scheduler_pb2 import Scheduler as SchedulerProto



class Scheduler (models.Model, GenBase):
    pb_class = SchedulerProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'scheduler-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(Scheduler, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(Scheduler, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(Scheduler, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = SchedulerProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('enabled')
        if self.enabled is not None:
            pb.enabled = self.enabled
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    enabled = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="scheduler_tenant_ref", on_delete=models.PROTECT)
    backup_config_ref_76b36da840904693_ref = models.ForeignKey(BackupConfiguration, null=True, blank=True, related_name="scheduler_backup_config_ref_76b36da840904693", on_delete=models.PROTECT)
    run_script_ref_eeb7c67f6c224a36_ref = models.ForeignKey(AlertScriptConfig, null=True, blank=True, related_name="scheduler_run_script_ref_eeb7c67f6c224a36", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.backup_config_uuid': ('weak_refers_to', u'BackupConfiguration', '76b36da840904693'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', '2fb3e669b6274313'),
        'root.run_script_uuid': ('weak_refers_to', u'AlertScriptConfig', 'eeb7c67f6c224a36'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

