
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from models_anomalyzer import *

from models_options_legacy import *
from models_options import *

ANZ_PRIORITY_HIGH = 0
ANZ_PRIORITY_MEDIUM = 1
ANZ_PRIORITY_LOW = 2
AnomalyzerPriorityChoices = (
    (ANZ_PRIORITY_HIGH, 'ANZ_PRIORITY_HIGH'),
    (ANZ_PRIORITY_MEDIUM, 'ANZ_PRIORITY_MEDIUM'),
    (ANZ_PRIORITY_LOW, 'ANZ_PRIORITY_LOW'),
)
