
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from models_analytics_profile import *

from models_options_legacy import *
from models_options import *
from models_match_legacy import *
from models_match import *

from models_common_legacy import *
from models_common import *
AP_HTTP_RSP_4XX = 4
AP_HTTP_RSP_5XX = 5
AnalyticsProfileRespCodeBlockChoices = (
    (AP_HTTP_RSP_4XX, 'AP_HTTP_RSP_4XX'),
    (AP_HTTP_RSP_5XX, 'AP_HTTP_RSP_5XX'),
)
LOG_STREAMING_PROTOCOL_UDP = 0
LOG_STREAMING_PROTOCOL_SYSLOG_OVER_UDP = 1
LOG_STREAMING_PROTOCOL_TCP = 2
LOG_STREAMING_PROTOCOL_SYSLOG_OVER_TCP = 3
LOG_STREAMING_PROTOCOL_RAW_OVER_UDP = 4
ClientLogStreamingProtocolChoices = (
    (LOG_STREAMING_PROTOCOL_UDP, 'LOG_STREAMING_PROTOCOL_UDP'),
    (LOG_STREAMING_PROTOCOL_SYSLOG_OVER_UDP, 'LOG_STREAMING_PROTOCOL_SYSLOG_OVER_UDP'),
    (LOG_STREAMING_PROTOCOL_TCP, 'LOG_STREAMING_PROTOCOL_TCP'),
    (LOG_STREAMING_PROTOCOL_SYSLOG_OVER_TCP, 'LOG_STREAMING_PROTOCOL_SYSLOG_OVER_TCP'),
    (LOG_STREAMING_PROTOCOL_RAW_OVER_UDP, 'LOG_STREAMING_PROTOCOL_RAW_OVER_UDP'),
)
LOG_FIELD_REMOVE = 0
LOG_FIELD_MASKOFF = 1
LogActionChoices = (
    (LOG_FIELD_REMOVE, 'LOG_FIELD_REMOVE'),
    (LOG_FIELD_MASKOFF, 'LOG_FIELD_MASKOFF'),
)
LOGS_PROCESSING_NONE = 1
LOGS_PROCESSING_SYNC_AND_INDEX_ON_DEMAND = 2
LOGS_PROCESSING_AUTO_SYNC_AND_INDEX = 3
LOGS_PROCESSING_AUTO_SYNC_BUT_INDEX_ON_DEMAND = 4
LogsProcessingTypeChoices = (
    (LOGS_PROCESSING_NONE, 'LOGS_PROCESSING_NONE'),
    (LOGS_PROCESSING_SYNC_AND_INDEX_ON_DEMAND, 'LOGS_PROCESSING_SYNC_AND_INDEX_ON_DEMAND'),
    (LOGS_PROCESSING_AUTO_SYNC_AND_INDEX, 'LOGS_PROCESSING_AUTO_SYNC_AND_INDEX'),
    (LOGS_PROCESSING_AUTO_SYNC_BUT_INDEX_ON_DEMAND, 'LOGS_PROCESSING_AUTO_SYNC_BUT_INDEX_ON_DEMAND'),
)
LOGS_SIGNIFICANT_ONLY = 1
LOGS_UDF_ONLY = 2
LOGS_UDF_SIGNIFICANT = 3
LOGS_ALL = 4
LogsTypeChoices = (
    (LOGS_SIGNIFICANT_ONLY, 'LOGS_SIGNIFICANT_ONLY'),
    (LOGS_UDF_ONLY, 'LOGS_UDF_ONLY'),
    (LOGS_UDF_SIGNIFICANT, 'LOGS_UDF_SIGNIFICANT'),
    (LOGS_ALL, 'LOGS_ALL'),
)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.analytics_profile_pb2 import ClientLogConfiguration as ClientLogConfigurationProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.analytics_profile_pb2 import StreamingSyslogConfig as StreamingSyslogConfigProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.analytics_profile_pb2 import ClientLogStreamingConfig as ClientLogStreamingConfigProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.analytics_profile_pb2 import SensitiveFieldRule as SensitiveFieldRuleProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.analytics_profile_pb2 import SensitiveLogProfile as SensitiveLogProfileProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.analytics_profile_pb2 import AnalyticsProfile as AnalyticsProfileProto