
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *
from models_vs_runtime import *
from models_common import *

SC_UPDATE = 1
SC_DELETE = 2
SCActionChoices = (
    (SC_UPDATE, 'SC_UPDATE'),
    (SC_DELETE, 'SC_DELETE'),
)
SC_OBJ_RUNTIME_UPDATE = 1
SC_OBJ_DELETE = 2
SC_OBJ_STATE_UPDATE = 3
SC_HEARTBEAT = 4
SC_INTERNALS = 5
SC_OBJ_CONFIG_UPDATE = 6
SC_SYNC_STATES_TO_SE = 7
SCInfoTypeChoices = (
    (SC_OBJ_RUNTIME_UPDATE, 'SC_OBJ_RUNTIME_UPDATE'),
    (SC_OBJ_DELETE, 'SC_OBJ_DELETE'),
    (SC_OBJ_STATE_UPDATE, 'SC_OBJ_STATE_UPDATE'),
    (SC_HEARTBEAT, 'SC_HEARTBEAT'),
    (SC_INTERNALS, 'SC_INTERNALS'),
    (SC_OBJ_CONFIG_UPDATE, 'SC_OBJ_CONFIG_UPDATE'),
    (SC_SYNC_STATES_TO_SE, 'SC_SYNC_STATES_TO_SE'),
)
SC_KEY_VIRTUALSERVICE = 1
SC_KEY_POOL = 2
SC_KEY_POOLSERVER = 3
SC_KEY_SERVICEENGINE = 4
SC_KEY_SEGROUP = 5
SC_KEY_GS = 6
SCKeyTypeChoices = (
    (SC_KEY_VIRTUALSERVICE, 'SC_KEY_VIRTUALSERVICE'),
    (SC_KEY_POOL, 'SC_KEY_POOL'),
    (SC_KEY_POOLSERVER, 'SC_KEY_POOLSERVER'),
    (SC_KEY_SERVICEENGINE, 'SC_KEY_SERVICEENGINE'),
    (SC_KEY_SEGROUP, 'SC_KEY_SEGROUP'),
    (SC_KEY_GS, 'SC_KEY_GS'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.se_state_cache_pb2 import SCVsStateInfo as SCVsStateInfoProto



class SCVsStateInfo (models.Model, GenBase):
    pb_class = SCVsStateInfoProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'scvsstateinfo-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(SCVsStateInfo, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(SCVsStateInfo, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(SCVsStateInfo, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = SCVsStateInfoProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('vip_id')
        if self.vip_id is not None:
            pb.vip_id = self.vip_id
        pb.ClearField('vs_id')
        if self.vs_id is not None:
            pb.vs_id = self.vs_id
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    vip_id = models.TextField(null=True, blank=True)
    vs_id = models.TextField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="scvsstateinfo_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'adbbf7f4ede6444c'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }
    disable_cache = True

    @staticmethod
    def get_extension_fields():
        return []



############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.se_state_cache_pb2 import SCPoolServerStateInfo as SCPoolServerStateInfoProto



class SCPoolServerStateInfo (models.Model, GenBase):
    pb_class = SCPoolServerStateInfoProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'scpoolserverstateinfo-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(SCPoolServerStateInfo, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(SCPoolServerStateInfo, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(SCPoolServerStateInfo, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = SCPoolServerStateInfoProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('pool_id')
        if self.pool_id is not None:
            pb.pool_id = self.pool_id
        pb.ClearField('is_server')
        if self.is_server is not None:
            pb.is_server = self.is_server
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    pool_id = models.TextField(null=True, blank=True)
    is_server = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="scpoolserverstateinfo_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '553172e687524256'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }
    disable_cache = True

    @staticmethod
    def get_extension_fields():
        return []


