
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from models_debug_se import *

from models_common_legacy import *
from models_common import *
from models_options_legacy import *
from models_options import *
from models_debug_controller_legacy import *
from models_debug_controller import *

from models_cloud_objects_legacy import *
from models_cloud_objects import *
DEBUG_DISPATCHER_FLOW = 0
DEBUG_DISPATCHER_FLOW_DETAIL = 1
DEBUG_DISPATCHER_FLOW_ALL = 2
DEBUG_CONFIG = 3
DEBUG_IP = 4
DEBUG_IP_PKT_IN = 5
DEBUG_IP_PKT_OUT = 6
DEBUG_ARP = 7
DEBUG_ARP_PKT_IN = 8
DEBUG_ARP_PKT_OUT = 9
DEBUG_ETHERNET = 10
DEBUG_ETHERNET_PKT_IN = 11
DEBUG_ETHERNET_PKT_OUT = 12
DEBUG_ICMP = 13
DEBUG_PCAP_RX = 14
DEBUG_PCAP_TX = 15
DEBUG_PCAP_DROP = 16
DEBUG_PCAP_ALL = 17
DEBUG_MISC = 18
DEBUG_CRUD = 19
DEBUG_POOL = 20
DEBUG_PCAP_DOS = 21
DEBUG_PCAP_HM = 22
DEBUG_SE_APP = 23
DEBUG_UDP = 24
DEBUG_SE_VS_HB = 25
DEBUG_ND = 26
DEBUG_ERROR = 49
DEBUG_NONE = 50
DEBUG_ALL = 51
DEBUG_STRICT = 52
DEBUG_FLOW_MIRROR = 53
DEBUG_NAT = 54
DEBUG_NAT_ERROR = 55
DEBUG_NAT_PKT = 56
DEBUG_NAT_END2END = 57
DEBUG_NAT_ALL = 58
DEBUG_PCAP_SE_IPC = 59
DebugSeDataplaneFlagsChoices = (
    (DEBUG_DISPATCHER_FLOW, 'DEBUG_DISPATCHER_FLOW'),
    (DEBUG_DISPATCHER_FLOW_DETAIL, 'DEBUG_DISPATCHER_FLOW_DETAIL'),
    (DEBUG_DISPATCHER_FLOW_ALL, 'DEBUG_DISPATCHER_FLOW_ALL'),
    (DEBUG_CONFIG, 'DEBUG_CONFIG'),
    (DEBUG_IP, 'DEBUG_IP'),
    (DEBUG_IP_PKT_IN, 'DEBUG_IP_PKT_IN'),
    (DEBUG_IP_PKT_OUT, 'DEBUG_IP_PKT_OUT'),
    (DEBUG_ARP, 'DEBUG_ARP'),
    (DEBUG_ARP_PKT_IN, 'DEBUG_ARP_PKT_IN'),
    (DEBUG_ARP_PKT_OUT, 'DEBUG_ARP_PKT_OUT'),
    (DEBUG_ETHERNET, 'DEBUG_ETHERNET'),
    (DEBUG_ETHERNET_PKT_IN, 'DEBUG_ETHERNET_PKT_IN'),
    (DEBUG_ETHERNET_PKT_OUT, 'DEBUG_ETHERNET_PKT_OUT'),
    (DEBUG_ICMP, 'DEBUG_ICMP'),
    (DEBUG_PCAP_RX, 'DEBUG_PCAP_RX'),
    (DEBUG_PCAP_TX, 'DEBUG_PCAP_TX'),
    (DEBUG_PCAP_DROP, 'DEBUG_PCAP_DROP'),
    (DEBUG_PCAP_ALL, 'DEBUG_PCAP_ALL'),
    (DEBUG_MISC, 'DEBUG_MISC'),
    (DEBUG_CRUD, 'DEBUG_CRUD'),
    (DEBUG_POOL, 'DEBUG_POOL'),
    (DEBUG_PCAP_DOS, 'DEBUG_PCAP_DOS'),
    (DEBUG_PCAP_HM, 'DEBUG_PCAP_HM'),
    (DEBUG_SE_APP, 'DEBUG_SE_APP'),
    (DEBUG_UDP, 'DEBUG_UDP'),
    (DEBUG_SE_VS_HB, 'DEBUG_SE_VS_HB'),
    (DEBUG_ND, 'DEBUG_ND'),
    (DEBUG_ERROR, 'DEBUG_ERROR'),
    (DEBUG_NONE, 'DEBUG_NONE'),
    (DEBUG_ALL, 'DEBUG_ALL'),
    (DEBUG_STRICT, 'DEBUG_STRICT'),
    (DEBUG_FLOW_MIRROR, 'DEBUG_FLOW_MIRROR'),
    (DEBUG_NAT, 'DEBUG_NAT'),
    (DEBUG_NAT_ERROR, 'DEBUG_NAT_ERROR'),
    (DEBUG_NAT_PKT, 'DEBUG_NAT_PKT'),
    (DEBUG_NAT_END2END, 'DEBUG_NAT_END2END'),
    (DEBUG_NAT_ALL, 'DEBUG_NAT_ALL'),
    (DEBUG_PCAP_SE_IPC, 'DEBUG_PCAP_SE_IPC'),
)
DEBUG_VS_HM_NONE = 1
DEBUG_VS_HM_ONLY = 2
DEBUG_VS_HM_INCLUDE = 3
DebugVirtualServiceHMChoices = (
    (DEBUG_VS_HM_NONE, 'DEBUG_VS_HM_NONE'),
    (DEBUG_VS_HM_ONLY, 'DEBUG_VS_HM_ONLY'),
    (DEBUG_VS_HM_INCLUDE, 'DEBUG_VS_HM_INCLUDE'),
)
DEBUG_VS_TCP_CONNECTION = 0
DEBUG_VS_TCP_PKT = 1
DEBUG_VS_TCP_APP = 2
DEBUG_VS_TCP_APP_PKT = 3
DEBUG_VS_TCP_RETRANSMIT = 4
DEBUG_VS_TCP_TIMER = 5
DEBUG_VS_TCP_CONN_ERROR = 6
DEBUG_VS_TCP_PKT_ERROR = 7
DEBUG_VS_TCP_REXMT = 8
DEBUG_VS_TCP_ALL = 9
DEBUG_VS_CREDIT = 10
DEBUG_VS_PROXY_CONNECTION = 11
DEBUG_VS_PROXY_PKT = 12
DEBUG_VS_PROXY_ERR = 13
DEBUG_VS_UDP = 14
DEBUG_VS_UDP_PKT = 15
DEBUG_VS_HM = 19
DEBUG_VS_HM_ERR = 20
DEBUG_VS_HM_PKT = 21
DEBUG_VS_HTTP_CORE = 22
DEBUG_VS_HTTP_ALL = 23
DEBUG_VS_CONFIG = 24
DEBUG_VS_EVENTS = 25
DEBUG_VS_HTTP_RULES = 26
DEBUG_VS_HM_EXT = 27
DEBUG_VS_SSL = 28
DEBUG_VS_WAF = 29
DEBUG_VS_DNS = 30
DEBUG_VS_PAA = 31
DEBUG_VS_ALL = 50
DEBUG_VS_ERROR = 51
DEBUG_VS_NONE = 52
DebugVsDataplaneFlagsChoices = (
    (DEBUG_VS_TCP_CONNECTION, 'DEBUG_VS_TCP_CONNECTION'),
    (DEBUG_VS_TCP_PKT, 'DEBUG_VS_TCP_PKT'),
    (DEBUG_VS_TCP_APP, 'DEBUG_VS_TCP_APP'),
    (DEBUG_VS_TCP_APP_PKT, 'DEBUG_VS_TCP_APP_PKT'),
    (DEBUG_VS_TCP_RETRANSMIT, 'DEBUG_VS_TCP_RETRANSMIT'),
    (DEBUG_VS_TCP_TIMER, 'DEBUG_VS_TCP_TIMER'),
    (DEBUG_VS_TCP_CONN_ERROR, 'DEBUG_VS_TCP_CONN_ERROR'),
    (DEBUG_VS_TCP_PKT_ERROR, 'DEBUG_VS_TCP_PKT_ERROR'),
    (DEBUG_VS_TCP_REXMT, 'DEBUG_VS_TCP_REXMT'),
    (DEBUG_VS_TCP_ALL, 'DEBUG_VS_TCP_ALL'),
    (DEBUG_VS_CREDIT, 'DEBUG_VS_CREDIT'),
    (DEBUG_VS_PROXY_CONNECTION, 'DEBUG_VS_PROXY_CONNECTION'),
    (DEBUG_VS_PROXY_PKT, 'DEBUG_VS_PROXY_PKT'),
    (DEBUG_VS_PROXY_ERR, 'DEBUG_VS_PROXY_ERR'),
    (DEBUG_VS_UDP, 'DEBUG_VS_UDP'),
    (DEBUG_VS_UDP_PKT, 'DEBUG_VS_UDP_PKT'),
    (DEBUG_VS_HM, 'DEBUG_VS_HM'),
    (DEBUG_VS_HM_ERR, 'DEBUG_VS_HM_ERR'),
    (DEBUG_VS_HM_PKT, 'DEBUG_VS_HM_PKT'),
    (DEBUG_VS_HTTP_CORE, 'DEBUG_VS_HTTP_CORE'),
    (DEBUG_VS_HTTP_ALL, 'DEBUG_VS_HTTP_ALL'),
    (DEBUG_VS_CONFIG, 'DEBUG_VS_CONFIG'),
    (DEBUG_VS_EVENTS, 'DEBUG_VS_EVENTS'),
    (DEBUG_VS_HTTP_RULES, 'DEBUG_VS_HTTP_RULES'),
    (DEBUG_VS_HM_EXT, 'DEBUG_VS_HM_EXT'),
    (DEBUG_VS_SSL, 'DEBUG_VS_SSL'),
    (DEBUG_VS_WAF, 'DEBUG_VS_WAF'),
    (DEBUG_VS_DNS, 'DEBUG_VS_DNS'),
    (DEBUG_VS_PAA, 'DEBUG_VS_PAA'),
    (DEBUG_VS_ALL, 'DEBUG_VS_ALL'),
    (DEBUG_VS_ERROR, 'DEBUG_VS_ERROR'),
    (DEBUG_VS_NONE, 'DEBUG_VS_NONE'),
)
ETH_TYPE_IPV4 = 2048
EtherTypesChoices = (
    (ETH_TYPE_IPV4, 'ETH_TYPE_IPV4'),
)
IP_TYPE_TCP = 6
IPTypesChoices = (
    (IP_TYPE_TCP, 'IP_TYPE_TCP'),
)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugVsDataplane as DebugVsDataplaneProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugVirtualServiceCapture as DebugVirtualServiceCaptureProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugIpAddr as DebugIpAddrProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import CaptureIPC as CaptureIPCProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import CaptureFilters as CaptureFiltersProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugVirtualServiceSeParams as DebugVirtualServiceSeParamsProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugVirtualService as DebugVirtualServiceProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugSeCpuShares as DebugSeCpuSharesProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugSeFault as DebugSeFaultProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugSeDataplane as DebugSeDataplaneProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugSeAgent as DebugSeAgentProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugServiceEngine as DebugServiceEngineProto

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.debug_se_pb2 import DebugDnsOptions as DebugDnsOptionsProto