
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

#GENERATED FILE FROM MODEL GENERATOR
#pylint:  skip-file
from models import *

MODEL_ENUM_DICT = {
'ErrorPageBody': {
    'format': ErrorPageFormatChoices ,
                 
},
'SCVsStateInfo': {
    'oper_status__state': OperationalStateChoices ,
                 
},
'ActionGroupConfig': {
    'level': AlertLevelChoices ,
                 
},
'VrfContext': {
    'gateway_mon__gateway_ip__type': IpAddrTypeChoices ,
    'bgp_profile__ip_communities__ip_begin__type': IpAddrTypeChoices ,
    'gateway_mon__subnet__ip_addr__type': IpAddrTypeChoices ,
    'bgp_profile__peers__subnet__ip_addr__type': IpAddrTypeChoices ,
    'bgp_profile__peers__peer_ip6__type': IpAddrTypeChoices ,
    'bgp_profile__peers__peer_ip__type': IpAddrTypeChoices ,
    'bgp_profile__peers__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'static_routes__prefix__ip_addr__type': IpAddrTypeChoices ,
    'debugvrfcontext__flags__flag': DebugVrfFlagChoices ,
    'static_routes__next_hop__type': IpAddrTypeChoices ,
    'bgp_profile__ip_communities__ip_end__type': IpAddrTypeChoices ,
                 
},
'ControllerLicense': {
    'license_tiers__tier_type': LicenseTierTypeChoices ,
    'licenses__se_bandwidth_limits__type': SEBandwidthTypeChoices ,
    'expired_burst_resources__license_tier': LicenseTierTypeChoices ,
    'license_tiers__se_bandwidth_limits__type': SEBandwidthTypeChoices ,
    'active_burst_resources__license_tier': LicenseTierTypeChoices ,
    'se_bandwidth_limits__type': SEBandwidthTypeChoices ,
    'licenses__tier_type': LicenseTierTypeChoices ,
                 
},
'JobEntry': {
    'subjobs__type': JobTypeChoices ,
                 
},
'SystemConfiguration': {
    'mgmt_ip_access_control__api_access__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__sysint_access__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__ssh_access__addrs__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__sysint_access__addrs__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__sysint_access__match_criteria': MatchOperationChoices ,
    'mgmt_ip_access_control__snmp_access__ranges__begin__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__ssh_access__ranges__begin__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__snmp_access__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'snmp_configuration__snmp_v3_config__user__auth_type': SNMP_V3_AUTHChoices ,
    'mgmt_ip_access_control__ssh_access__ranges__end__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__api_access__ranges__end__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__snmp_access__ranges__end__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__snmp_access__addrs__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__shell_server_access__addrs__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__api_access__match_criteria': MatchOperationChoices ,
    'ntp_configuration__ntp_servers__server__type': IpAddrTypeChoices ,
    'admin_auth_configuration__mapping_rules__group_match__criteria': AuthMatchOperationChoices ,
    'mgmt_ip_access_control__shell_server_access__match_criteria': MatchOperationChoices ,
    'snmp_configuration__version': SNMP_VERChoices ,
    'admin_auth_configuration__mapping_rules__attribute_match__criteria': AuthMatchOperationChoices ,
    'mgmt_ip_access_control__ssh_access__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'snmp_configuration__snmp_v3_config__user__priv_type': SNMP_V3_PRIVChoices ,
    'mgmt_ip_access_control__ssh_access__match_criteria': MatchOperationChoices ,
    'email_configuration__smtp_type': SMTPTypeChoices ,
    'ntp_configuration__ntp_authentication_keys__algorithm': NTPAuthAlgorithmChoices ,
    'mgmt_ip_access_control__snmp_access__match_criteria': MatchOperationChoices ,
    'mgmt_ip_access_control__api_access__addrs__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__sysint_access__ranges__end__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__api_access__ranges__begin__type': IpAddrTypeChoices ,
    'dns_configuration__server_list__type': IpAddrTypeChoices ,
    'admin_auth_configuration__mapping_rules__assign_role': AuthRuleAssignmentChoices ,
    'mgmt_ip_access_control__shell_server_access__ranges__begin__type': IpAddrTypeChoices ,
    'default_license_tier': LicenseTierTypeChoices ,
    'admin_auth_configuration__mapping_rules__assign_tenant': AuthRuleAssignmentChoices ,
    'mgmt_ip_access_control__shell_server_access__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__sysint_access__ranges__begin__type': IpAddrTypeChoices ,
    'ntp_configuration__ntp_server_list__type': IpAddrTypeChoices ,
    'mgmt_ip_access_control__shell_server_access__ranges__end__type': IpAddrTypeChoices ,
                 
},
'PoolGroup': {
    'members__deployment_state': PoolDeploymentStateChoices ,
    'fail_action__type': FailActionEnumChoices ,
    'fail_action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'fail_action__redirect__protocol': HTTPProtocolChoices ,
    'fail_action__local_rsp__status_code': FailHttpStatusCodeChoices ,
                 
},
'VIMgrClusterRuntime': {
    'type': CloudTypeChoices ,
                 
},
'AlertSyslogConfig': {
    'syslog_servers__format': SyslogFormatChoices ,
                 
},
'ErrorPageProfile': {
    'error_pages__match__match_criteria': MatchOperationChoices ,
                 
},
'VSDataScriptSet': {
    'datascript__evt': VSDataScriptEventChoices ,
                 
},
'Role': {
    'privileges__type': PrivilegeChoices ,
    'privileges__resource': AviPermissionResourceChoices ,
                 
},
'DebugController': {
    'sub_module': DebugControllerModuleTypeChoices ,
    'log_level': LogLevelChoices ,
    'filters__mesos_metrics_debug_filter__metric_entity': MetricsEntityTypeChoices ,
    'filters__hs_debug_filter__metric_entity': MetricsEntityTypeChoices ,
    'trace_level': TraceLevelChoices ,
    'filters__type': DebugControllerModuleTypeChoices ,
                 
},
'WafPolicy': {
    'whitelist__rules__match__path__match_case': MatchCaseChoices ,
    'pre_crs_groups__exclude_list__uri_match_criteria__match_case': MatchCaseChoices ,
    'pre_crs_groups__exclude_list__client_subnet__ip_addr__type': IpAddrTypeChoices ,
    'crs_groups__exclude_list__uri_match_criteria__match_op': StringOperationChoices ,
    'pre_crs_groups__rules__exclude_list__match_element_criteria__match_op': StringOperationChoices ,
    'post_crs_groups__exclude_list__match_element_criteria__match_case': MatchCaseChoices ,
    'whitelist__rules__match__path__match_criteria': StringOperationChoices ,
    'crs_groups__rules__exclude_list__client_subnet__ip_addr__type': IpAddrTypeChoices ,
    'failure_mode': WafFailureModeChoices ,
    'post_crs_groups__rules__exclude_list__uri_match_criteria__match_case': MatchCaseChoices ,
    'post_crs_groups__rules__exclude_list__client_subnet__ip_addr__type': IpAddrTypeChoices ,
    'whitelist__rules__match__client_ip__addrs__type': IpAddrTypeChoices ,
    'post_crs_groups__rules__exclude_list__match_element_criteria__match_case': MatchCaseChoices ,
    'pre_crs_groups__rules__exclude_list__uri_match_criteria__match_op': StringOperationChoices ,
    'whitelist__rules__match__version__versions': HTTPVersionChoices ,
    'crs_groups__rules__exclude_list__match_element_criteria__match_case': MatchCaseChoices ,
    'post_crs_groups__exclude_list__uri_match_criteria__match_op': StringOperationChoices ,
    'crs_groups__exclude_list__uri_match_criteria__match_case': MatchCaseChoices ,
    'whitelist__rules__match__hdrs__match_criteria': HdrMatchOperationChoices ,
    'whitelist__rules__match__hdrs__match_case': MatchCaseChoices ,
    'post_crs_groups__rules__mode': WafModeChoices ,
    'whitelist__rules__match__vs_port__match_criteria': MatchOperationChoices ,
    'whitelist__rules__match__method__methods': HTTPMethodChoices ,
    'crs_groups__exclude_list__match_element_criteria__match_op': StringOperationChoices ,
    'post_crs_groups__exclude_list__match_element_criteria__match_op': StringOperationChoices ,
    'whitelist__rules__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'pre_crs_groups__rules__exclude_list__uri_match_criteria__match_case': MatchCaseChoices ,
    'whitelist__rules__match__client_ip__match_criteria': MatchOperationChoices ,
    'crs_groups__exclude_list__match_element_criteria__match_case': MatchCaseChoices ,
    'whitelist__rules__match__query__match_criteria': QueryMatchOperationChoices ,
    'whitelist__rules__match__protocol__match_criteria': MatchOperationChoices ,
    'pre_crs_groups__rules__exclude_list__client_subnet__ip_addr__type': IpAddrTypeChoices ,
    'whitelist__rules__match__host_hdr__match_criteria': HdrMatchOperationChoices ,
    'whitelist__rules__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'whitelist__rules__match__query__match_case': MatchCaseChoices ,
    'pre_crs_groups__exclude_list__match_element_criteria__match_case': MatchCaseChoices ,
    'crs_groups__rules__exclude_list__uri_match_criteria__match_op': StringOperationChoices ,
    'crs_groups__rules__exclude_list__uri_match_criteria__match_case': MatchCaseChoices ,
    'paranoia_level': WafParanoiaLevelChoices ,
    'whitelist__rules__match__cookie__match_case': MatchCaseChoices ,
    'whitelist__rules__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'pre_crs_groups__exclude_list__uri_match_criteria__match_op': StringOperationChoices ,
    'crs_groups__rules__mode': WafModeChoices ,
    'whitelist__rules__match__method__match_criteria': MatchOperationChoices ,
    'post_crs_groups__rules__exclude_list__match_element_criteria__match_op': StringOperationChoices ,
    'pre_crs_groups__rules__mode': WafModeChoices ,
    'whitelist__rules__match__cookie__match_criteria': HdrMatchOperationChoices ,
    'crs_groups__exclude_list__client_subnet__ip_addr__type': IpAddrTypeChoices ,
    'whitelist__rules__actions': WafPolicyWhitelistActionChoices ,
    'whitelist__rules__match__host_hdr__match_case': MatchCaseChoices ,
    'whitelist__rules__match__version__match_criteria': MatchOperationChoices ,
    'whitelist__rules__match__protocol__protocols': HTTPProtocolChoices ,
    'mode': WafModeChoices ,
    'post_crs_groups__exclude_list__uri_match_criteria__match_case': MatchCaseChoices ,
    'post_crs_groups__rules__exclude_list__uri_match_criteria__match_op': StringOperationChoices ,
    'pre_crs_groups__rules__exclude_list__match_element_criteria__match_case': MatchCaseChoices ,
    'pre_crs_groups__exclude_list__match_element_criteria__match_op': StringOperationChoices ,
    'post_crs_groups__exclude_list__client_subnet__ip_addr__type': IpAddrTypeChoices ,
    'crs_groups__rules__exclude_list__match_element_criteria__match_op': StringOperationChoices ,
                 
},
'IpAddrGroup': {
    'ranges__end__type': IpAddrTypeChoices ,
    'addrs__type': IpAddrTypeChoices ,
    'ranges__begin__type': IpAddrTypeChoices ,
    'prefixes__ip_addr__type': IpAddrTypeChoices ,
    'ip_ports__ip__type': IpAddrTypeChoices ,
                 
},
'VirtualService': {
    'vip__ip_address__type': IpAddrTypeChoices ,
    'vip__discovered_networks__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'flow_dist': SeFlowDistChoices ,
    'analytics_policy__client_log_filters__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'dns_info__type': DnsRecordTypeChoices ,
    'vip__subnet__ip_addr__type': IpAddrTypeChoices ,
    'requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'sso_policy__authorization_policy__authz_rules__action__status_code': AuthorizationActionHttpStatusCodeChoices ,
    'analytics_policy__client_insights_sampling__skip_uris__match_criteria': StringOperationChoices ,
    'analytics_policy__client_log_filters__client_ip__addrs__type': IpAddrTypeChoices ,
    'requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'ssl_profile_selectors__client_ip_list__ranges__begin__type': IpAddrTypeChoices ,
    'static_dns_records__algorithm': DnsRecordResponseAlgorithmChoices ,
    'subnet__ip_addr__type': IpAddrTypeChoices ,
    'static_dns_records__ip6_address__ip6_address__type': IpAddrTypeChoices ,
    'active_standby_se_tag': ActiveStandbySeTagChoices ,
    'sso_policy__authentication_policy__authn_rules__match__host_hdr__match_criteria': HdrMatchOperationChoices ,
    'ssl_profile_selectors__client_ip_list__addrs__type': IpAddrTypeChoices ,
    'sso_policy__authorization_policy__authz_rules__match__host_hdr__match_case': MatchCaseChoices ,
    'analytics_policy__client_insights_sampling__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'dns_info__algorithm': DnsRecordResponseAlgorithmChoices ,
    'sideband_profile__ip__type': IpAddrTypeChoices ,
    'requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'static_dns_records__ip_address__ip_address__type': IpAddrTypeChoices ,
    'sso_policy__authentication_policy__authn_rules__match__client_ip__addrs__type': IpAddrTypeChoices ,
    'client_auth__type': HTTPClientAuthenticationTypeChoices ,
    'connections_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'analytics_policy__client_insights_sampling__client_ip__addrs__type': IpAddrTypeChoices ,
    'vip__floating_ip6__type': IpAddrTypeChoices ,
    'vip__ip6_address__type': IpAddrTypeChoices ,
    'content_rewrite__rsp_match_replace_pair__replacement_string__type': ReplaceStringTypeChoices ,
    'sso_policy__authentication_policy__authn_rules__match__client_ip__match_criteria': MatchOperationChoices ,
    'analytics_policy__client_insights_sampling__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'analytics_policy__client_log_filters__uri__match_criteria': StringOperationChoices ,
    'sso_policy__authentication_policy__authn_rules__match__path__match_case': MatchCaseChoices ,
    'ipam_network_subnet__subnet__ip_addr__type': IpAddrTypeChoices ,
    'sso_policy__authorization_policy__authz_rules__match__method__methods': HTTPMethodChoices ,
    'analytics_policy__client_insights_sampling__sample_uris__match_criteria': StringOperationChoices ,
    'ipam_network_subnet__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'connections_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'connections_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'connections_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'analytics_policy__client_insights': ClientInsightsChoices ,
    'static_dns_records__type': DnsRecordTypeChoices ,
    'ssl_profile_selectors__client_ip_list__ranges__end__type': IpAddrTypeChoices ,
    'static_dns_records__ns__ip_address__type': IpAddrTypeChoices ,
    'sso_policy__authentication_policy__authn_rules__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'sso_policy__authentication_policy__authn_rules__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'sso_policy__type': SSOPolicyTypeChoices ,
    'sso_policy__authorization_policy__authz_rules__action__type': AuthorizationActionEnumChoices ,
    'analytics_policy__client_insights_sampling__client_ip__match_criteria': MatchOperationChoices ,
    'vip__auto_allocate_ip_type': IpAddressVersionsChoices ,
    'vip__discovered_networks__subnet__ip_addr__type': IpAddrTypeChoices ,
    'sso_policy__authorization_policy__authz_rules__match__path__match_criteria': StringOperationChoices ,
    'client_auth__request_uri_path__match_criteria': StringOperationChoices ,
    'vip__ipam_network_subnet__subnet__ip_addr__type': IpAddrTypeChoices ,
    'static_dns_records__ns__ip6_address__type': IpAddrTypeChoices ,
    'vip__ipam_network_subnet__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'sso_policy__authorization_policy__authz_rules__match__attr_matches__attribute_value_list__match_criteria': StringOperationChoices ,
    'discovered_networks__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'type': VirtualServiceTypeChoices ,
    'vip__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'analytics_policy__client_log_filters__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'sso_policy__authentication_policy__authn_rules__action__type': AuthenticationActionEnumChoices ,
    'analytics_policy__client_log_filters__client_ip__match_criteria': MatchOperationChoices ,
    'connections_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'snat_ip__type': IpAddrTypeChoices ,
    'content_rewrite__req_match_replace_pair__replacement_string__type': ReplaceStringTypeChoices ,
    'flow_label_type': FlowLabelTypeChoices ,
    'sso_policy__authentication_policy__authn_rules__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'discovered_networks__subnet__ip_addr__type': IpAddrTypeChoices ,
    'ssl_profile_selectors__client_ip_list__match_criteria': MatchOperationChoices ,
    'requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'sso_policy__authorization_policy__authz_rules__match__method__match_criteria': MatchOperationChoices ,
    'ip_address__type': IpAddrTypeChoices ,
    'sso_policy__authorization_policy__authz_rules__match__host_hdr__match_criteria': HdrMatchOperationChoices ,
    'vip__floating_ip__type': IpAddrTypeChoices ,
    'cloud_type': CloudTypeChoices ,
    'analytics_policy__client_log_filters__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'ssl_profile_selectors__client_ip_list__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'analytics_policy__client_insights_sampling__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'connections_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'connections_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'sso_policy__authentication_policy__authn_rules__match__path__match_criteria': StringOperationChoices ,
    'floating_ip__type': IpAddrTypeChoices ,
    'sso_policy__authentication_policy__authn_rules__match__host_hdr__match_case': MatchCaseChoices ,
    'requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'discovered_subnet__ip_addr__type': IpAddrTypeChoices ,
    'sso_policy__authorization_policy__authz_rules__match__path__match_case': MatchCaseChoices ,
    'service_pool_select__service_protocol': ProtocolTypeChoices ,
    'connections_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
                 
},
'AuthProfile': {
    'tacacs_plus__service': AuthTacacsPlusServiceChoices ,
    'saml__sp__saml_entity_type': AuthSamlEntityTypeChoices ,
    'ldap__security_mode': AuthLdapSecurityModeChoices ,
    'ldap__settings__user_search_scope': AuthLdapSearchScopeChoices ,
    'ldap__settings__group_search_scope': AuthLdapSearchScopeChoices ,
    'type': AuthProfileTypeChoices ,
                 
},
'VIMgrControllerRuntime': {
    'type': CloudTypeChoices ,
                 
},
'WafCRS': {
    'groups__rules__exclude_list__client_subnet__ip_addr__type': IpAddrTypeChoices ,
    'groups__rules__exclude_list__match_element_criteria__match_case': MatchCaseChoices ,
    'groups__exclude_list__match_element_criteria__match_op': StringOperationChoices ,
    'groups__exclude_list__match_element_criteria__match_case': MatchCaseChoices ,
    'groups__exclude_list__uri_match_criteria__match_op': StringOperationChoices ,
    'groups__exclude_list__client_subnet__ip_addr__type': IpAddrTypeChoices ,
    'groups__rules__mode': WafModeChoices ,
    'groups__rules__exclude_list__uri_match_criteria__match_op': StringOperationChoices ,
    'groups__rules__exclude_list__match_element_criteria__match_op': StringOperationChoices ,
    'groups__rules__exclude_list__uri_match_criteria__match_case': MatchCaseChoices ,
    'groups__exclude_list__uri_match_criteria__match_case': MatchCaseChoices ,
                 
},
'SSOPolicy': {
    'authentication_policy__authn_rules__match__host_hdr__match_criteria': HdrMatchOperationChoices ,
    'authorization_policy__authz_rules__action__status_code': AuthorizationActionHttpStatusCodeChoices ,
    'authorization_policy__authz_rules__match__method__match_criteria': MatchOperationChoices ,
    'authorization_policy__authz_rules__match__host_hdr__match_criteria': HdrMatchOperationChoices ,
    'authentication_policy__authn_rules__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'authorization_policy__authz_rules__action__type': AuthorizationActionEnumChoices ,
    'authentication_policy__authn_rules__match__client_ip__match_criteria': MatchOperationChoices ,
    'authorization_policy__authz_rules__match__host_hdr__match_case': MatchCaseChoices ,
    'authorization_policy__authz_rules__match__method__methods': HTTPMethodChoices ,
    'authentication_policy__authn_rules__match__client_ip__addrs__type': IpAddrTypeChoices ,
    'authentication_policy__authn_rules__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'authorization_policy__authz_rules__match__attr_matches__attribute_value_list__match_criteria': StringOperationChoices ,
    'authorization_policy__authz_rules__match__path__match_case': MatchCaseChoices ,
    'authorization_policy__authz_rules__match__path__match_criteria': StringOperationChoices ,
    'authentication_policy__authn_rules__match__path__match_criteria': StringOperationChoices ,
    'authentication_policy__authn_rules__match__path__match_case': MatchCaseChoices ,
    'authentication_policy__authn_rules__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'type': SSOPolicyTypeChoices ,
    'authentication_policy__authn_rules__match__host_hdr__match_case': MatchCaseChoices ,
    'authentication_policy__authn_rules__action__type': AuthenticationActionEnumChoices ,
                 
},
'Network': {
    'configured_subnets__prefix__ip_addr__type': IpAddrTypeChoices ,
    'configured_subnets__static_ips__type': IpAddrTypeChoices ,
    'configured_subnets__static_ranges__begin__type': IpAddrTypeChoices ,
    'configured_subnets__static_ranges__end__type': IpAddrTypeChoices ,
                 
},
'LogControllerMapping': {
    'metrics_mgr_port': MetricsMgrPortsChoices ,
    'prev_metrics_mgr_port': MetricsMgrPortsChoices ,
                 
},
'SnmpTrapProfile': {
    'trap_servers__user__priv_type': SNMP_V3_PRIVChoices ,
    'trap_servers__user__auth_type': SNMP_V3_AUTHChoices ,
    'trap_servers__ip_addr__type': IpAddrTypeChoices ,
    'trap_servers__version': SNMP_VERChoices ,
                 
},
'DnsPolicy': {
    'rule__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'rule__match__query_type__query_type': DnsRecordTypeChoices ,
    'rule__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'rule__match__protocol__protocol': DnsTransportProtocolChoices ,
    'rule__action__response__resource_record_sets__resource_record_set__ip6_addresses__ip6_address__type': IpAddrTypeChoices ,
    'rule__match__client_ip_address__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'rule__match__client_ip__match_criteria': MatchOperationChoices ,
    'rule__match__query_name__match_criteria': StringOperationChoices ,
    'rule__match__client_ip_address__client_ip__match_criteria': MatchOperationChoices ,
    'rule__action__response__rcode': DnsRcodeChoices ,
    'rule__action__response__resource_record_sets__resource_record_set__type': DnsRecordTypeChoices ,
    'rule__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'rule__action__response__resource_record_sets__section': DnsMessageSectionChoices ,
    'rule__match__client_ip_address__client_ip__addrs__type': IpAddrTypeChoices ,
    'rule__match__client_ip__addrs__type': IpAddrTypeChoices ,
    'rule__match__query_type__match_criteria': MatchOperationChoices ,
    'rule__match__protocol__match_criteria': MatchOperationChoices ,
    'rule__match__geo_location__match_criteria': MatchOperationChoices ,
    'rule__match__client_ip_address__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'rule__action__response__resource_record_sets__resource_record_set__nses__ip_address__type': IpAddrTypeChoices ,
    'rule__match__client_ip_address__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'rule__action__response__resource_record_sets__resource_record_set__ip_addresses__ip_address__type': IpAddrTypeChoices ,
    'rule__action__response__resource_record_sets__resource_record_set__nses__ip6_address__type': IpAddrTypeChoices ,
                 
},
'VIMgrVcenterRuntime': {
    'privilege': PrivilegeChoices ,
    'inventory_state': VCENTER_DISCOVERY_STATEChoices ,
    'type': CloudTypeChoices ,
                 
},
'PKIProfile': {
    'ca_certs__key_params__ec_params__curve': SSLKeyECCurveChoices ,
    'ca_certs__key_params__algorithm': SSLKeyAlgorithmChoices ,
    'ca_certs__key_params__rsa_params__key_size': SSLRSAKeySizeChoices ,
    'ca_certs__expiry_status': SSLCertificateExpiryStatusChoices ,
                 
},
'VsVip': {
    'vip__floating_ip__type': IpAddrTypeChoices ,
    'dns_info__algorithm': DnsRecordResponseAlgorithmChoices ,
    'vip__ip_address__type': IpAddrTypeChoices ,
    'vip__discovered_networks__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'vip__ipam_network_subnet__subnet__ip_addr__type': IpAddrTypeChoices ,
    'vip__ip6_address__type': IpAddrTypeChoices ,
    'vip__auto_allocate_ip_type': IpAddressVersionsChoices ,
    'dns_info__type': DnsRecordTypeChoices ,
    'vip__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'vip__floating_ip6__type': IpAddrTypeChoices ,
    'vip__ipam_network_subnet__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'vip__discovered_networks__subnet__ip_addr__type': IpAddrTypeChoices ,
    'vip__subnet__ip_addr__type': IpAddrTypeChoices ,
                 
},
'VIMgrNWRuntime': {
    'ip_subnet__prefix__ip_addr__type': IpAddrTypeChoices ,
    'type': CloudTypeChoices ,
    'ip_subnet__floatingip_subnets__prefix__ip_addr__type': IpAddrTypeChoices ,
                 
},
'PoolGroupDeploymentPolicy': {
    'rules__operator': ComparisonOperatorChoices ,
    'scheme': PoolGroupDeploymentSchemeChoices ,
                 
},
'ControllerProperties': {
    'se_from_marketplace': SeFromMarketplaceChoices ,
                 
},
'AnalyticsProfile': {
    'sensitive_log_profile__waf_field_rules__match__match_criteria': StringOperationChoices ,
    'resp_code_block': AnalyticsProfileRespCodeBlockChoices ,
    'client_log_config__non_significant_log_processing': LogsProcessingTypeChoices ,
    'client_log_streaming_config__log_types_to_send': LogsTypeChoices ,
    'sensitive_log_profile__waf_field_rules__action': LogActionChoices ,
    'sensitive_log_profile__header_field_rules__action': LogActionChoices ,
    'client_log_config__filtered_log_processing': LogsProcessingTypeChoices ,
    'client_log_config__significant_log_processing': LogsProcessingTypeChoices ,
    'client_log_streaming_config__protocol': ClientLogStreamingProtocolChoices ,
    'sensitive_log_profile__header_field_rules__match__match_criteria': StringOperationChoices ,
                 
},
'ApplicationProfile': {
    'dos_rl_profile__rl_profile__client_ip_scanners_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__uri_scanners_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dns_service_profile__error_response': DnsErrorResponseTypeChoices ,
    'tcp_app_profile__ssl_client_certificate_mode': SSLClientCertificateModeChoices ,
    'dos_rl_profile__rl_profile__http_header_rate_limits__action__redirect__protocol': HTTPProtocolChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__custom_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__uri_failed_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__uri_scanners_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__uri_failed_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'http_profile__compression_profile__type': CompressionTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_failed_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__uri_scanners_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_failed_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__http_header_rate_limits__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_failed_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_failed_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'dos_rl_profile__rl_profile__uri_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'dos_rl_profile__rl_profile__client_ip_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'dos_rl_profile__rl_profile__custom_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__custom_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'http_profile__ssl_client_certificate_action__headers__request_header_value': HTTPPolicyVarChoices ,
    'dos_rl_profile__rl_profile__custom_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__http_header_rate_limits__action__redirect__host__type': URIParamTypeChoices ,
    'http_profile__ssl_client_certificate_mode': SSLClientCertificateModeChoices ,
    'dos_rl_profile__rl_profile__client_ip_failed_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__uri_failed_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__uri_failed_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__uri_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__uri_failed_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_failed_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_connections_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__http_header_rate_limits__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__dos_profile__thresh_info__attack': AttackTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_failed_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_failed_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_scanners_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_scanners_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__uri_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__custom_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_connections_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'http_profile__cache_config__uri_non_cacheable__match_criteria': StringOperationChoices ,
    'dos_rl_profile__rl_profile__uri_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'tcp_app_profile__proxy_protocol_version': ProxyProtocolVersionChoices ,
    'dos_rl_profile__rl_profile__client_ip_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__uri_scanners_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__uri_scanners_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__uri_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'http_profile__compression_profile__filter__ip_addrs__type': IpAddrTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_failed_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_failed_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_failed_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_scanners_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_connections_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'dos_rl_profile__rl_profile__client_ip_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_connections_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'type': ApplicationProfileTypeChoices ,
    'dos_rl_profile__rl_profile__uri_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__http_header_rate_limits__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__uri_scanners_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__custom_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_connections_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__uri_failed_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'http_profile__cache_config__uri_non_cacheable__match_case': MatchCaseChoices ,
    'http_profile__compression_profile__filter__ip_addr_ranges__end__type': IpAddrTypeChoices ,
    'dos_rl_profile__rl_profile__uri_scanners_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'dos_rl_profile__rl_profile__client_ip_connections_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_scanners_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'http_profile__compression_profile__filter__ip_addr_ranges__begin__type': IpAddrTypeChoices ,
    'http_profile__compression_profile__filter__ip_addr_prefixes__ip_addr__type': IpAddrTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_failed_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'dos_rl_profile__rl_profile__custom_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'dos_rl_profile__rl_profile__uri_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_failed_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__uri_failed_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'http_profile__compression_profile__filter__level': CompressionFilterLevelChoices ,
    'dos_rl_profile__rl_profile__client_ip_connections_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__uri_failed_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_failed_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__custom_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_scanners_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__http_header_rate_limits__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__http_header_rate_limits__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_failed_requests_rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_to_uri_requests_rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'http_profile__compression_profile__filter__match': MatchOperationChoices ,
    'dos_rl_profile__rl_profile__client_ip_requests_rate_limit__action__type': RateLimiterActionTypeChoices ,
    'dos_rl_profile__rl_profile__uri_scanners_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_scanners_requests_rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_requests_rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__uri_requests_rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_failed_requests_rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__client_ip_scanners_requests_rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'dos_rl_profile__rl_profile__http_header_rate_limits__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'dos_rl_profile__rl_profile__client_ip_connections_rate_limit__action__type': RateLimiterActionTypeChoices ,
                 
},
'GslbGeoDbProfile': {
    'entries__file__format': GslbGeoDbFileFormatChoices ,
                 
},
'L4PolicySet': {
    'l4_connection_policy__rules__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'l4_connection_policy__rules__match__port__match_criteria': MatchOperationChoices ,
    'l4_connection_policy__rules__match__protocol__match_criteria': MatchOperationChoices ,
    'l4_connection_policy__rules__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'l4_connection_policy__rules__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'l4_connection_policy__rules__match__protocol__protocol': ProtocolChoices ,
    'l4_connection_policy__rules__match__client_ip__match_criteria': MatchOperationChoices ,
    'l4_connection_policy__rules__action__select_pool__action_type': L4RuleActionSelectPoolTypeChoices ,
    'l4_connection_policy__rules__match__client_ip__addrs__type': IpAddrTypeChoices ,
                 
},
'Scheduler': {
    'scheduler_action': SchedulerActionChoices ,
    'frequency_unit': SchedulerFrequencyUnitChoices ,
    'run_mode': SchedulerRunModeChoices ,
                 
},
'Alert': {
    'conn_events__proxy_protocol': ProxyProtocolVersionChoices ,
    'app_events__client_cipher_list__identified_ciphers': AllCipherEnumsChoices ,
    'metric_info__time_series__metric_entity': MetricsEntityTypeChoices ,
    'conn_events__dns_response__records__type': DnsRecordTypeChoices ,
    'metric_info__time_series__series__header__derivation_data__join_tables': MetricsTableIdChoices ,
    'events__obj_type': AviObjectTypeChoices ,
    'app_events__compression': AviCompressionStatusChoices ,
    'metric_info__time_series__series__header__units': MetricUnitsChoices ,
    'app_events__waf_log__psm_logs__actions': WafActionChoices ,
    'events__event_id': EventIdChoices ,
    'state': AlertStateChoices ,
    'metric_info__time_series__series__header__dimension_data__dimension': MetricsDimensionChoices ,
    'events__internal': EventInternalTypeChoices ,
    'app_events__significant_log': AviDefinedFiltersChoices ,
    'conn_events__dns_request__opcode': DnsOpcodeChoices ,
    'conn_events__dns_response__opcode': DnsOpcodeChoices ,
    'conn_events__sip_log__server_protocol': ProtocolChoices ,
    'conn_events__dns_response__opt_record__options__code': DnsEdnsOptionCodeChoices ,
    'conn_events__dns_etype': DnsEntryTypeChoices ,
    'conn_events__dns_qtype': DnsRecordTypeChoices ,
    'app_events__request_state': AviHTTPRequestStateChoices ,
    'metric_info__time_series__series__header__obj_id_type': MetricsDataObjIdTypeChoices ,
    'events__context': EventContextChoices ,
    'events__reason_code': SyserrChoices ,
    'conn_events__dns_response__response_code': DnsRcodeChoices ,
    'metric_info__time_series__series__header__derivation_data__derivation_fn': MetricsDerivationFnChoices ,
    'events__module': EventModuleChoices ,
    'level': AlertLevelChoices ,
    'conn_events__dns_request__opt_record__options__code': DnsEdnsOptionCodeChoices ,
    'app_events__client_insights': AviClientInsightsStatusChoices ,
    'app_events__body_updated': AviHTTPResponseBodyUpdatedChoices ,
    'app_events__waf_log__whitelist_logs__actions': WafPolicyWhitelistActionChoices ,
    'app_events__waf_log__status': WafStatusCodeChoices ,
    'conn_events__protocol': ProtocolChoices ,
    'conn_events__significant_log': AviDefinedFiltersChoices ,
                 
},
'VIMgrVMRuntime': {
    'vcenter_vm_type': VM_TypeChoices ,
    'guest_nic__guest_ip__floatingip_subnets__prefix__ip_addr__type': IpAddrTypeChoices ,
    'guest_nic__guest_ip__prefix__ip_addr__type': IpAddrTypeChoices ,
    'vcenter_se_type': VIMGR_SE_TYPEChoices ,
    'guest_nic__type': CloudTypeChoices ,
    'type': CloudTypeChoices ,
                 
},
'WafProfile': {
    'config__allowed_http_versions': HTTPVersionChoices ,
    'config__allowed_methods': HTTPMethodChoices ,
    'config__min_confidence': AppLearningConfidenceLabelChoices ,
    'config__status_code_for_rejected_requests': HTTPResponseCodesChoices ,
                 
},
'DebugServiceEngine': {
    'seagent_debug__trace_level': TraceLevelChoices ,
    'flags__flag': DebugSeDataplaneFlagsChoices ,
    'capture_filters__capture_ip__ranges__begin__type': IpAddrTypeChoices ,
    'debug_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'capture_filters__capture_ip__addrs__type': IpAddrTypeChoices ,
    'capture_filters__capture_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'capture_filters__capture_ip__ranges__end__type': IpAddrTypeChoices ,
    'debug_ip__addrs__type': IpAddrTypeChoices ,
    'debug_ip__ranges__end__type': IpAddrTypeChoices ,
    'capture_filters__eth_proto': EtherTypesChoices ,
    'seagent_debug__log_level': LogLevelChoices ,
    'debug_ip__ranges__begin__type': IpAddrTypeChoices ,
    'capture_filters__ip_proto': IPTypesChoices ,
    'seagent_debug__sub_module': DebugControllerModuleTypeChoices ,
                 
},
'Pool': {
    'lb_algorithm': LbAlgorithmChoices ,
    'servers__discovered_networks__subnet__ip_addr__type': IpAddrTypeChoices ,
    'fail_action__type': FailActionEnumChoices ,
    'max_conn_rate_per_server__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'max_conn_rate_per_server__action__redirect__host__type': URIParamTypeChoices ,
    'max_conn_rate_per_server__action__type': RateLimiterActionTypeChoices ,
    'max_conn_rate_per_server__action__redirect__path__type': URIParamTypeChoices ,
    'server_reselect__svr_resp_code__resp_code_block': HttpReselectRespCodeBlockChoices ,
    'servers__discovered_subnet__ip_addr__type': IpAddrTypeChoices ,
    'fail_action__redirect__protocol': HTTPProtocolChoices ,
    'fail_action__local_rsp__status_code': FailHttpStatusCodeChoices ,
    'max_conn_rate_per_server__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'max_conn_rate_per_server__action__redirect__protocol': HTTPProtocolChoices ,
    'servers__ip__type': IpAddrTypeChoices ,
    'max_conn_rate_per_server__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'placement_networks__subnet__ip_addr__type': IpAddrTypeChoices ,
    'fail_action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'max_conn_rate_per_server__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'servers__discovered_networks__subnet6__ip_addr__type': IpAddrTypeChoices ,
    'lb_algorithm_hash': LbAlgorithmConsistentHashChoices ,
                 
},
'SeProperties': {
    'se_runtime_properties__service_ip_subnets__ip_addr__type': IpAddrTypeChoices ,
    'se_runtime_properties__app_headers__hdr_string_op': StringOperationChoices ,
    'se_runtime_properties__app_headers__hdr_match_case': MatchCaseChoices ,
    'se_runtime_properties__dos_profile__thresh_info__attack': AttackTypeChoices ,
                 
},
'HTTPPolicySet': {
    'http_security_policy__rules__match__hdrs__match_criteria': HdrMatchOperationChoices ,
    'http_request_policy__rules__switching_action__server__ip__type': IpAddrTypeChoices ,
    'http_response_policy__rules__match__method__methods': HTTPMethodChoices ,
    'http_request_policy__rules__redirect_action__status_code': HTTPRedirectStatusCodeChoices ,
    'http_security_policy__rules__action__rate_limit__action__redirect__path__type': URIParamTypeChoices ,
    'http_security_policy__rules__action__rate_limit__action__redirect__status_code': HTTPRedirectStatusCodeChoices ,
    'http_response_policy__rules__match__loc_hdr__match_criteria': HdrMatchOperationChoices ,
    'http_security_policy__rules__match__version__match_criteria': MatchOperationChoices ,
    'http_response_policy__rules__match__query__match_criteria': QueryMatchOperationChoices ,
    'http_request_policy__rules__match__hdrs__match_case': MatchCaseChoices ,
    'http_request_policy__rules__rewrite_url_action__host_hdr__type': URIParamTypeChoices ,
    'http_security_policy__rules__match__method__methods': HTTPMethodChoices ,
    'http_request_policy__rules__redirect_action__protocol': HTTPProtocolChoices ,
    'http_request_policy__rules__match__method__match_criteria': MatchOperationChoices ,
    'http_response_policy__rules__match__query__match_case': MatchCaseChoices ,
    'http_security_policy__rules__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'http_response_policy__rules__match__client_ip__addrs__type': IpAddrTypeChoices ,
    'http_response_policy__rules__match__path__match_criteria': StringOperationChoices ,
    'http_security_policy__rules__action__action': HTTPSecurityActionTypeChoices ,
    'http_request_policy__rules__match__query__match_case': MatchCaseChoices ,
    'http_request_policy__rules__match__protocol__protocols': HTTPProtocolChoices ,
    'http_response_policy__rules__hdr_action__action': HTTPHdrActionTypeChoices ,
    'http_request_policy__rules__redirect_action__path__type': URIParamTypeChoices ,
    'http_request_policy__rules__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'http_request_policy__rules__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'http_response_policy__rules__match__rsp_hdrs__match_case': MatchCaseChoices ,
    'http_response_policy__rules__match__hdrs__match_criteria': HdrMatchOperationChoices ,
    'http_response_policy__rules__match__client_ip__match_criteria': MatchOperationChoices ,
    'http_request_policy__rules__match__method__methods': HTTPMethodChoices ,
    'http_response_policy__rules__match__loc_hdr__match_case': MatchCaseChoices ,
    'http_security_policy__rules__match__path__match_criteria': StringOperationChoices ,
    'http_security_policy__rules__match__hdrs__match_case': MatchCaseChoices ,
    'http_response_policy__rules__match__path__match_case': MatchCaseChoices ,
    'http_response_policy__rules__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'http_request_policy__rules__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'http_request_policy__rules__match__query__match_criteria': QueryMatchOperationChoices ,
    'http_request_policy__rules__redirect_action__path__tokens__type': URITokenTypeChoices ,
    'http_request_policy__rules__hdr_action__hdr__value__var': HTTPPolicyVarChoices ,
    'http_request_policy__rules__match__host_hdr__match_case': MatchCaseChoices ,
    'http_response_policy__rules__match__hdrs__match_case': MatchCaseChoices ,
    'http_response_policy__rules__match__status__match_criteria': MatchOperationChoices ,
    'http_request_policy__rules__match__path__match_criteria': StringOperationChoices ,
    'http_request_policy__rules__redirect_action__host__type': URIParamTypeChoices ,
    'http_security_policy__rules__match__query__match_criteria': QueryMatchOperationChoices ,
    'http_request_policy__rules__match__cookie__match_criteria': HdrMatchOperationChoices ,
    'http_request_policy__rules__switching_action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'http_security_policy__rules__match__host_hdr__match_case': MatchCaseChoices ,
    'http_request_policy__rules__match__cookie__match_case': MatchCaseChoices ,
    'http_response_policy__rules__loc_hdr_action__path__type': URIParamTypeChoices ,
    'http_response_policy__rules__hdr_action__hdr__value__var': HTTPPolicyVarChoices ,
    'http_response_policy__rules__loc_hdr_action__path__tokens__type': URITokenTypeChoices ,
    'http_response_policy__rules__loc_hdr_action__protocol': HTTPProtocolChoices ,
    'http_request_policy__rules__match__path__match_case': MatchCaseChoices ,
    'http_response_policy__rules__match__host_hdr__match_criteria': HdrMatchOperationChoices ,
    'http_response_policy__rules__match__protocol__match_criteria': MatchOperationChoices ,
    'http_request_policy__rules__match__client_ip__match_criteria': MatchOperationChoices ,
    'http_request_policy__rules__match__host_hdr__match_criteria': HdrMatchOperationChoices ,
    'http_security_policy__rules__action__rate_limit__action__type': RateLimiterActionTypeChoices ,
    'http_response_policy__rules__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'http_response_policy__rules__match__vs_port__match_criteria': MatchOperationChoices ,
    'http_response_policy__rules__match__method__match_criteria': MatchOperationChoices ,
    'http_security_policy__rules__match__host_hdr__match_criteria': HdrMatchOperationChoices ,
    'http_security_policy__rules__match__query__match_case': MatchCaseChoices ,
    'http_request_policy__rules__match__client_ip__addrs__type': IpAddrTypeChoices ,
    'http_request_policy__rules__rewrite_url_action__path__tokens__type': URITokenTypeChoices ,
    'http_security_policy__rules__match__protocol__match_criteria': MatchOperationChoices ,
    'http_security_policy__rules__action__rate_limit__action__redirect__path__tokens__type': URITokenTypeChoices ,
    'http_security_policy__rules__match__client_ip__match_criteria': MatchOperationChoices ,
    'http_request_policy__rules__match__vs_port__match_criteria': MatchOperationChoices ,
    'http_security_policy__rules__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'http_response_policy__rules__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'http_response_policy__rules__match__host_hdr__match_case': MatchCaseChoices ,
    'http_security_policy__rules__match__path__match_case': MatchCaseChoices ,
    'http_security_policy__rules__match__version__versions': HTTPVersionChoices ,
    'http_security_policy__rules__action__rate_limit__action__status_code': HTTPLocalResponseStatusCodeChoices ,
    'http_security_policy__rules__match__protocol__protocols': HTTPProtocolChoices ,
    'http_request_policy__rules__rewrite_url_action__path__type': URIParamTypeChoices ,
    'http_security_policy__rules__match__vs_port__match_criteria': MatchOperationChoices ,
    'http_request_policy__rules__hdr_action__action': HTTPHdrActionTypeChoices ,
    'http_security_policy__rules__action__rate_limit__action__redirect__protocol': HTTPProtocolChoices ,
    'http_security_policy__rules__action__rate_limit__action__redirect__host__tokens__type': URITokenTypeChoices ,
    'http_request_policy__rules__redirect_action__host__tokens__type': URITokenTypeChoices ,
    'http_request_policy__rules__rewrite_url_action__host_hdr__tokens__type': URITokenTypeChoices ,
    'http_response_policy__rules__match__version__match_criteria': MatchOperationChoices ,
    'http_response_policy__rules__match__protocol__protocols': HTTPProtocolChoices ,
    'http_security_policy__rules__match__client_ip__addrs__type': IpAddrTypeChoices ,
    'http_request_policy__rules__match__protocol__match_criteria': MatchOperationChoices ,
    'http_security_policy__rules__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'http_security_policy__rules__match__method__match_criteria': MatchOperationChoices ,
    'http_security_policy__rules__action__rate_limit__action__redirect__host__type': URIParamTypeChoices ,
    'http_response_policy__rules__match__cookie__match_case': MatchCaseChoices ,
    'http_security_policy__rules__match__cookie__match_case': MatchCaseChoices ,
    'http_response_policy__rules__match__rsp_hdrs__match_criteria': HdrMatchOperationChoices ,
    'http_response_policy__rules__loc_hdr_action__host__tokens__type': URITokenTypeChoices ,
    'http_request_policy__rules__match__version__match_criteria': MatchOperationChoices ,
    'http_response_policy__rules__loc_hdr_action__host__type': URIParamTypeChoices ,
    'http_request_policy__rules__match__hdrs__match_criteria': HdrMatchOperationChoices ,
    'http_response_policy__rules__match__version__versions': HTTPVersionChoices ,
    'http_request_policy__rules__match__version__versions': HTTPVersionChoices ,
    'http_response_policy__rules__match__cookie__match_criteria': HdrMatchOperationChoices ,
    'http_request_policy__rules__switching_action__action': HTTPSwitchingActionTypeChoices ,
    'http_security_policy__rules__match__cookie__match_criteria': HdrMatchOperationChoices ,
    'http_security_policy__rules__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
                 
},
'HardwareSecurityModuleGroup': {
    'hsm__rfs__ip__type': IpAddrTypeChoices ,
    'hsm__nethsm__remote_ip__type': IpAddrTypeChoices ,
    'hsm__type': HSMTypeChoices ,
                 
},
'VIMgrDCRuntime': {
    'type': CloudTypeChoices ,
                 
},
'CloudProperties': {
    'info__controller_props__se_from_marketplace': SeFromMarketplaceChoices ,
    'info__htypes': HypervisorChoices ,
    'cc_vtypes': CloudTypeChoices ,
    'hyp_props__htype': HypervisorChoices ,
    'info__vtype': CloudTypeChoices ,
                 
},
'SSLKeyAndCertificate': {
    'status': SSLCertificateStatusChoices ,
    'key_params__rsa_params__key_size': SSLRSAKeySizeChoices ,
    'format': SSLFormatChoices ,
    'key_params__ec_params__curve': SSLKeyECCurveChoices ,
    'certificate__expiry_status': SSLCertificateExpiryStatusChoices ,
    'certificate__key_params__ec_params__curve': SSLKeyECCurveChoices ,
    'certificate__key_params__algorithm': SSLKeyAlgorithmChoices ,
    'key_params__algorithm': SSLKeyAlgorithmChoices ,
    'certificate__key_params__rsa_params__key_size': SSLRSAKeySizeChoices ,
    'type': SSLCertificateTypeChoices ,
                 
},
'NatPolicy': {
    'rules__match__destination_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'rules__match__source_ip__ranges__end__type': IpAddrTypeChoices ,
    'rules__match__destination_ip__match_criteria': MatchOperationChoices ,
    'rules__match__destination_port__match_criteria': MatchOperationChoices ,
    'rules__match__source_ip__ranges__begin__type': IpAddrTypeChoices ,
    'rules__match__destination_ip__addrs__type': IpAddrTypeChoices ,
    'rules__match__source_ip__addrs__type': IpAddrTypeChoices ,
    'rules__action_param__nat_info__nat_ip__type': IpAddrTypeChoices ,
    'rules__match__source_ip__match_criteria': MatchOperationChoices ,
    'rules__action_param__nat_info__nat_ip_range__end__type': IpAddrTypeChoices ,
    'rules__match__source_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'rules__action_param__nat_info__nat_ip_range__begin__type': IpAddrTypeChoices ,
    'rules__action': NatPolicyActionTypeChoices ,
    'rules__match__source_port__match_criteria': MatchOperationChoices ,
    'rules__match__destination_ip__ranges__begin__type': IpAddrTypeChoices ,
    'rules__match__destination_ip__ranges__end__type': IpAddrTypeChoices ,
                 
},
'SecureChannelMapping': {
    'status': SecureChannelStatusChoices ,
                 
},
'DebugVirtualService': {
    'flags__flag': DebugVsDataplaneFlagsChoices ,
    'debug_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'debug_ip__addrs__type': IpAddrTypeChoices ,
    'debug_ip__ranges__end__type': IpAddrTypeChoices ,
    'debug_hm': DebugVirtualServiceHMChoices ,
    'debug_ip__ranges__begin__type': IpAddrTypeChoices ,
                 
},
'GslbService': {
    'groups__algorithm': GslbAlgorithmChoices ,
    'groups__fallback_algorithm': GslbAlgorithmChoices ,
    'groups__members__hm_proxies__proxy_type': GslbHealthMonitorProxyTypeChoices ,
    'groups__members__location__source': GslbGeoLocationSourceChoices ,
    'groups__members__ip__type': IpAddrTypeChoices ,
    'down_response__fallback_ip__type': IpAddrTypeChoices ,
    'down_response__type': GslbServiceDownResponseTypeChoices ,
    'health_monitor_scope': GslbServiceHealthMonitorScopeChoices ,
    'groups__members__public_ip__ip__type': IpAddrTypeChoices ,
    'pool_algorithm': GslbServiceAlgorithmChoices ,
                 
},
'AlertConfig': {
    'category': AlertCategoryChoices ,
    'alert_rule__sys_event_rule__event_id': EventIdChoices ,
    'object_type': AviObjectTypeChoices ,
    'alert_rule__operator': AlertRuleOperatorChoices ,
    'alert_rule__sys_event_rule__event_details__comparator': AlertOperationChoices ,
    'source': AlertSourceChoices ,
    'alert_rule__metrics_rule__metric_threshold__comparator': AlertOperationChoices ,
                 
},
'IpamDnsProviderProfile': {
    'infoblox_profile__usable_subnets__ip_addr__type': IpAddrTypeChoices ,
    'infoblox_profile__ip_address__type': IpAddrTypeChoices ,
    'type': IpamDnsTypeChoices ,
    'custom_profile__usable_subnets__ip_addr__type': IpAddrTypeChoices ,
                 
},
'SCPoolServerStateInfo': {
    'server_states__oper_status__state': OperationalStateChoices ,
    'server_states__server_ip__type': IpAddrTypeChoices ,
    'oper_status__state': OperationalStateChoices ,
                 
},
'StringGroup': {
    'type': StringGroupTypeChoices ,
                 
},
'AlertObjectList': {
    'source': AlertSourceChoices ,
    'objects': AviObjectTypeChoices ,
                 
},
'NetworkSecurityPolicy': {
    'rules__match__vs_port__match_criteria': MatchOperationChoices ,
    'rules__match__client_ip__ranges__begin__type': IpAddrTypeChoices ,
    'rules__match__client_ip__match_criteria': MatchOperationChoices ,
    'rules__match__microservice__match_criteria': MatchOperationChoices ,
    'rules__match__client_ip__ranges__end__type': IpAddrTypeChoices ,
    'rules__action': NetworkSecurityPolicyActionTypeChoices ,
    'rules__match__client_ip__prefixes__ip_addr__type': IpAddrTypeChoices ,
    'rules__match__client_ip__addrs__type': IpAddrTypeChoices ,
                 
},
'VIMgrSEVMRuntime': {
    'vcenter_vm_type': VM_TypeChoices ,
    'hypervisor': HypervisorChoices ,
    'guest_nic__guest_ip__floatingip_subnets__prefix__ip_addr__type': IpAddrTypeChoices ,
    'guest_nic__guest_ip__prefix__ip_addr__type': IpAddrTypeChoices ,
    'vcenter_se_type': VIMGR_SE_TYPEChoices ,
    'guest_nic__type': CloudTypeChoices ,
    'type': CloudTypeChoices ,
                 
},
'PingAccessAgent': {
    'primary_server__ip__type': IpAddrTypeChoices ,
                 
},
'NetworkProfile': {
    'profile__type': ProtocolTypeChoices ,
    'profile__tcp_fast_path_profile__dsr_profile__dsr_type': DsrTypeChoices ,
    'profile__udp_fast_path_profile__dsr_profile__dsr_encap_type': EncapTypeChoices ,
    'profile__tcp_fast_path_profile__dsr_profile__dsr_encap_type': EncapTypeChoices ,
    'profile__udp_fast_path_profile__dsr_profile__dsr_type': DsrTypeChoices ,
    'profile__tcp_proxy_profile__cc_algo': CongestionAlgoChoices ,
    'profile__tcp_proxy_profile__idle_connection_type': IdleConnectionTypeChoices ,
                 
},
'TrafficCloneProfile': {
    'clone_servers__subnet__ip_addr__type': IpAddrTypeChoices ,
    'clone_servers__ip_address__type': IpAddrTypeChoices ,
                 
},
'ServiceEngineGroup': {
    'ingress_access_data': SecurityGroupIngressAccessChoices ,
    'se_dos_profile__thresh_info__attack': AttackTypeChoices ,
    'iptables__rules__dnat_ip__type': IpAddrTypeChoices ,
    'iptables__rules__dst_ip__ip_addr__type': IpAddrTypeChoices ,
    'service_ip_subnets__ip_addr__type': IpAddrTypeChoices ,
    'ha_mode': HaModeChoices ,
    'ingress_access_mgmt': SecurityGroupIngressAccessChoices ,
    'service_ip6_subnets__ip_addr__type': IpAddrTypeChoices ,
    'placement_mode': PlacementModeChoices ,
    'iptables__rules__src_ip__ip_addr__type': IpAddrTypeChoices ,
    'license_type': LicenseTypeChoices ,
    'mgmt_subnet__ip_addr__type': IpAddrTypeChoices ,
    'floating_intf_ip__type': IpAddrTypeChoices ,
    'iptables__rules__proto': IptableRuleProtocolChoices ,
    'iptables__rules__action': IptableRuleActionChoices ,
    'floating_intf_ip_se_2__type': IpAddrTypeChoices ,
    'license_tier': LicenseTierTypeChoices ,
    'hypervisor': HypervisorChoices ,
    'vcenter_datastore_mode': VcenterDatastoreModeChoices ,
    'auto_rebalance_criteria': AutoRebalanceCriterionChoices ,
    'algo': PlacementAlgorithmChoices ,
    'se_bandwidth_type': SEBandwidthTypeChoices ,
                 
},
'MicroService': {
    'containers__ip__type': IpAddrTypeChoices ,
                 
},
'Cluster': {
    'virtual_ip__type': IpAddrTypeChoices ,
    'nodes__public_ip_or_name__type': IpAddrTypeChoices ,
    'nodes__ip__type': IpAddrTypeChoices ,
                 
},
'ServiceEngine': {
    'hypervisor': HypervisorChoices ,
    'data_vnics__vnic_networks__mode': IpAddrModeChoices ,
    'enable_state': ServiceEngineEnableStateChoices ,
    'container_type': ContainerTypeChoices ,
    'mgmt_vnic__vnic_networks__ip__ip_addr__type': IpAddrTypeChoices ,
    'mgmt_vnic__vlan_interfaces__vnic_networks__mode': IpAddrModeChoices ,
    'mgmt_vnic__vnic_networks__mode': IpAddrModeChoices ,
    'data_vnics__vlan_interfaces__vnic_networks__mode': IpAddrModeChoices ,
    'mgmt_vnic__vlan_interfaces__vnic_networks__ip__ip_addr__type': IpAddrTypeChoices ,
    'data_vnics__vnic_networks__ip__ip_addr__type': IpAddrTypeChoices ,
    'data_vnics__vlan_interfaces__vnic_networks__ip__ip_addr__type': IpAddrTypeChoices ,
                 
},
'SSLProfile': {
    'ssl_rating__performance_rating': SSLScoreChoices ,
    'ssl_rating__compatibility_rating': SSLScoreChoices ,
    'accepted_versions__type': SSLVersionTypeChoices ,
    'tags__type': TagTypeChoices ,
    'cipher_enums': AcceptedCipherEnumsChoices ,
    'type': SSLProfileTypeChoices ,
                 
},
'WafPolicyPSMGroup': {
    'locations__rules__match_elements__name': WafVariableChoices ,
    'locations__rules__match_case': MatchCaseChoices ,
    'locations__match__path__match_criteria': StringOperationChoices ,
    'locations__match__path__match_case': MatchCaseChoices ,
    'locations__match__methods__match_criteria': MatchOperationChoices ,
    'locations__rules__mode': WafModeChoices ,
    'locations__match__methods__methods': HTTPMethodChoices ,
    'hit_action': WafActionChoices ,
    'locations__rules__paranoia_level': WafParanoiaLevelChoices ,
    'locations__match__host__match_criteria': HdrMatchOperationChoices ,
    'locations__match__host__match_case': MatchCaseChoices ,
    'miss_action': WafActionChoices ,
                 
},
'HealthMonitor': {
    'sip_monitor__sip_monitor_transport': SipMonTransportChoices ,
    'dns_monitor__qtype': HealthMonitorDNSQueryTypeChoices ,
    'https_monitor__http_response_code': HttpResponseCodeChoices ,
    'dns_monitor__record_type': DnsRecordTypeChoices ,
    'sip_monitor__sip_request_code': SipRequestCodeChoices ,
    'http_monitor__http_response_code': HttpResponseCodeChoices ,
    'type': HealthMonitorTypeChoices ,
    'dns_monitor__rcode': HealthMonitorDNSRcodeChoices ,
                 
},
'SecurityPolicy': {
    'dns_attacks__oper_mode': OperationModeChoices ,
    'oper_mode': OperationModeChoices ,
    'dns_attacks__attacks__attack_vector': DnsAttackVectorChoices ,
                 
},
'NetworkRuntime': {
    'subnet_runtime__ip_alloced__ip__type': IpAddrTypeChoices ,
    'subnet_runtime__prefix__ip_addr__type': IpAddrTypeChoices ,
                 
},
'VIMgrHostRuntime': {
    'pnics__switch_info_type': PNIC_SWITCH_INFOChoices ,
    'type': CloudTypeChoices ,
                 
},
'Gslb': {
    'client_ip_addr_group__addrs__type': IpAddrTypeChoices ,
    'third_party_sites__hm_proxies__proxy_type': GslbHealthMonitorProxyTypeChoices ,
    'third_party_sites__location__source': GslbGeoLocationSourceChoices ,
    'sites__hm_proxies__proxy_type': GslbHealthMonitorProxyTypeChoices ,
    'client_ip_addr_group__ranges__end__type': IpAddrTypeChoices ,
    'client_ip_addr_group__ranges__begin__type': IpAddrTypeChoices ,
    'sites__member_type': SiteMemberTypeChoices ,
    'client_ip_addr_group__type': GslbIpAddrTypeChoices ,
    'sites__location__source': GslbGeoLocationSourceChoices ,
    'sites__ip_addresses__type': IpAddrTypeChoices ,
    'client_ip_addr_group__prefixes__ip_addr__type': IpAddrTypeChoices ,
                 
},
'Cloud': {
    'aws_configuration__ebs_encryption__mode': AwsEncryptionModeChoices ,
    'oshiftk8s_configuration__se_pod_tolerations__operator': PodTolerationOperatorChoices ,
    'docker_configuration__docker_registry_se__oshift_registry__registry_vip__type': IpAddrTypeChoices ,
    'linuxserver_configuration__docker_registry_se__oshift_registry__registry_vip__type': IpAddrTypeChoices ,
    'mesos_configuration__se_deployment_method': SeCreateMethodMesosChoices ,
    'rancher_configuration__east_west_placement_subnet__ip_addr__type': IpAddrTypeChoices ,
    'docker_configuration__se_deployment_method': SeCreateMethodContainerChoices ,
    'vtype': CloudTypeChoices ,
    'mesos_configuration__feproxy_route_publish__mode': FeProxyRoutePublishChoices ,
    'oshiftk8s_configuration__east_west_placement_subnet__ip_addr__type': IpAddrTypeChoices ,
    'oshiftk8s_configuration__vip_default_gateway__type': IpAddrTypeChoices ,
    'mesos_configuration__east_west_placement_subnet__ip_addr__type': IpAddrTypeChoices ,
    'apic_configuration__context_aware': ApicContextChoices ,
    'openstack_configuration__hypervisor': HypervisorChoices ,
    'oshiftk8s_configuration__docker_registry_se__oshift_registry__registry_vip__type': IpAddrTypeChoices ,
    'aws_configuration__sqs_encryption__mode': AwsEncryptionModeChoices ,
    'cloudstack_configuration__hypervisor': HypervisorChoices ,
    'rancher_configuration__docker_registry_se__oshift_registry__registry_vip__type': IpAddrTypeChoices ,
    'docker_configuration__east_west_placement_subnet__ip_addr__type': IpAddrTypeChoices ,
    'rancher_configuration__se_deployment_method': SeCreateMethodContainerChoices ,
    'mesos_configuration__docker_registry_se__oshift_registry__registry_vip__type': IpAddrTypeChoices ,
    'oshiftk8s_configuration__se_pod_tolerations__effect': PodTolerationEffectChoices ,
    'oshiftk8s_configuration__avi_bridge_subnet__ip_addr__type': IpAddrTypeChoices ,
    'license_tier': LicenseTierTypeChoices ,
    'linuxserver_configuration__hosts__host_ip__type': IpAddrTypeChoices ,
    'vcenter_configuration__management_ip_subnet__ip_addr__type': IpAddrTypeChoices ,
    'gcp_configuration__network_config__config': GCPNetworkConfigModeChoices ,
    'openstack_configuration__privilege': PrivilegeChoices ,
    'mesos_configuration__vip__type': IpAddrTypeChoices ,
    'vca_configuration__privilege': PrivilegeChoices ,
    'openstack_configuration__img_format': OpenStackImgFormatChoices ,
    'vcenter_configuration__privilege': PrivilegeChoices ,
    'openstack_configuration__hypervisor_properties__hypervisor': HypervisorChoices ,
    'license_type': LicenseTypeChoices ,
    'aws_configuration__s3_encryption__mode': AwsEncryptionModeChoices ,
    'oshiftk8s_configuration__se_deployment_method': SeCreateMethodContainerChoices ,
                 
},
'ApplicationPersistenceProfile': {
    'persistence_type': PersistenceProfileTypeChoices ,
    'server_hm_down_recovery': PersistentServerHMDownRecoveryChoices ,
                 
},
                   
}