
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_common import *
from models_options import *
from models_vs import *
from models_gslb import *
from models_health_monitor import *
from models_health_monitor_runtime import *
from models_metrics import *
from models_syserr import *
from models_application_profile import *

GSLB_FULL_UPDATE_PENDING = 1
GSLB_PARTIAL_UPDATE_PENDING = 2
GslbDnsGsStatusStateChoices = (
    (GSLB_FULL_UPDATE_PENDING, 'GSLB_FULL_UPDATE_PENDING'),
    (GSLB_PARTIAL_UPDATE_PENDING, 'GSLB_PARTIAL_UPDATE_PENDING'),
)
GSLB_NO_UPDATE = 1
GSLB_FULL_UPDATE = 2
GSLB_PARTIAL_UPDATE = 3
GslbDnsGsStatusTypeChoices = (
    (GSLB_NO_UPDATE, 'GSLB_NO_UPDATE'),
    (GSLB_FULL_UPDATE, 'GSLB_FULL_UPDATE'),
    (GSLB_PARTIAL_UPDATE, 'GSLB_PARTIAL_UPDATE'),
)
GSLB_DOWNLOAD_NONE = 0
GSLB_DOWNLOAD_DONE = 1
GSLB_DOWNLOAD_PENDING = 2
GSLB_DOWNLOAD_ERROR = 3
GslbDownloadStateChoices = (
    (GSLB_DOWNLOAD_NONE, 'GSLB_DOWNLOAD_NONE'),
    (GSLB_DOWNLOAD_DONE, 'GSLB_DOWNLOAD_DONE'),
    (GSLB_DOWNLOAD_PENDING, 'GSLB_DOWNLOAD_PENDING'),
    (GSLB_DOWNLOAD_ERROR, 'GSLB_DOWNLOAD_ERROR'),
)
GSLB_SITE_NONE = 0
GSLB_SITE_CONFIG = 1
GSLB_SITE_HS = 2
GSLB_SITE_MMODE = 3
GSLB_SITE_FILE_CONFIG = 4
GslbMsgTypeChoices = (
    (GSLB_SITE_NONE, 'GSLB_SITE_NONE'),
    (GSLB_SITE_CONFIG, 'GSLB_SITE_CONFIG'),
    (GSLB_SITE_HS, 'GSLB_SITE_HS'),
    (GSLB_SITE_MMODE, 'GSLB_SITE_MMODE'),
    (GSLB_SITE_FILE_CONFIG, 'GSLB_SITE_FILE_CONFIG'),
)
GSLB_NONE = 0
GSLB_CREATE = 1
GSLB_UPDATE = 2
GSLB_DELETE = 3
GSLB_PURGE = 4
GSLB_DECL = 5
GslbOpsChoices = (
    (GSLB_NONE, 'GSLB_NONE'),
    (GSLB_CREATE, 'GSLB_CREATE'),
    (GSLB_UPDATE, 'GSLB_UPDATE'),
    (GSLB_DELETE, 'GSLB_DELETE'),
    (GSLB_PURGE, 'GSLB_PURGE'),
    (GSLB_DECL, 'GSLB_DECL'),
)
GSLB_LEADER = 0
GSLB_MEMBER = 1
GSLB_NOT_A_MEMBER = 2
GslbRoleChoices = (
    (GSLB_LEADER, 'GSLB_LEADER'),
    (GSLB_MEMBER, 'GSLB_MEMBER'),
    (GSLB_NOT_A_MEMBER, 'GSLB_NOT_A_MEMBER'),
)
GSLB_SITE_CFG_IN_SYNC = 1
GSLB_SITE_CFG_OUT_OF_SYNC = 2
GSLB_SITE_CFG_SYNC_DISABLED = 3
GSLB_SITE_CFG_SYNC_IN_PROGRESS = 4
GSLB_SITE_CFG_SYNC_NOT_APPLICABLE = 5
GslbSiteCfgSyncStateChoices = (
    (GSLB_SITE_CFG_IN_SYNC, 'GSLB_SITE_CFG_IN_SYNC'),
    (GSLB_SITE_CFG_OUT_OF_SYNC, 'GSLB_SITE_CFG_OUT_OF_SYNC'),
    (GSLB_SITE_CFG_SYNC_DISABLED, 'GSLB_SITE_CFG_SYNC_DISABLED'),
    (GSLB_SITE_CFG_SYNC_IN_PROGRESS, 'GSLB_SITE_CFG_SYNC_IN_PROGRESS'),
    (GSLB_SITE_CFG_SYNC_NOT_APPLICABLE, 'GSLB_SITE_CFG_SYNC_NOT_APPLICABLE'),
)
GSLB_AVI_SITE = 1
GSLB_THIRD_PARTY_SITE = 2
GslbSiteTypeChoices = (
    (GSLB_AVI_SITE, 'GSLB_AVI_SITE'),
    (GSLB_THIRD_PARTY_SITE, 'GSLB_THIRD_PARTY_SITE'),
)
REPL_NONE = 0
REPL_ENABLED = 1
REPL_DISABLED = 2
ReplStateChoices = (
    (REPL_NONE, 'REPL_NONE'),
    (REPL_ENABLED, 'REPL_ENABLED'),
    (REPL_DISABLED, 'REPL_DISABLED'),
)
SITE_STATE_NULL = 0
SITE_STATE_JOIN_IN_PROGRESS = 1
SITE_STATE_LEAVE_IN_PROGRESS = 2
SITE_STATE_INIT = 3
SITE_STATE_UNREACHABLE = 4
SITE_STATE_MMODE = 5
SITE_STATE_DISABLE_IN_PROGRESS = 6
SITE_STATE_DISABLED = 7
SiteStateChoices = (
    (SITE_STATE_NULL, 'SITE_STATE_NULL'),
    (SITE_STATE_JOIN_IN_PROGRESS, 'SITE_STATE_JOIN_IN_PROGRESS'),
    (SITE_STATE_LEAVE_IN_PROGRESS, 'SITE_STATE_LEAVE_IN_PROGRESS'),
    (SITE_STATE_INIT, 'SITE_STATE_INIT'),
    (SITE_STATE_UNREACHABLE, 'SITE_STATE_UNREACHABLE'),
    (SITE_STATE_MMODE, 'SITE_STATE_MMODE'),
    (SITE_STATE_DISABLE_IN_PROGRESS, 'SITE_STATE_DISABLE_IN_PROGRESS'),
    (SITE_STATE_DISABLED, 'SITE_STATE_DISABLED'),
)
NON_AVI_VIP = 0
AVI_VIP = 1
VipTypeChoices = (
    (NON_AVI_VIP, 'NON_AVI_VIP'),
    (AVI_VIP, 'AVI_VIP'),
)
