
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from models_health_score import *

from models_common_legacy import *
from models_common import *
from models_options_legacy import *
from models_options import *
from models_metrics_query_legacy import *
from models_metrics_query import *

HEALTH_AGG_SUM = 1
HEALTH_AGG_MIN = 3
HEATLH_AGG_AVG = 2
HealthScoreAggregationOpChoices = (
    (HEALTH_AGG_SUM, 'HEALTH_AGG_SUM'),
    (HEALTH_AGG_MIN, 'HEALTH_AGG_MIN'),
    (HEATLH_AGG_AVG, 'HEATLH_AGG_AVG'),
)
HEALTH_SUMMARY = 0
HEALTH_DETAIL = 1
HealthScoreLevelChoices = (
    (HEALTH_SUMMARY, 'HEALTH_SUMMARY'),
    (HEALTH_DETAIL, 'HEALTH_DETAIL'),
)
HEALTH_SCORE = 0
HEALTH_PERFORMANCE_SCORE = 1
HEALTH_ANOMALY_SCORE = 2
HEALTH_RESOURCES_SCORE = 3
HEALTH_SECURITY_THREAT_LEVEL = 4
HealthScoreTypeChoices = (
    (HEALTH_SCORE, 'HEALTH_SCORE'),
    (HEALTH_PERFORMANCE_SCORE, 'HEALTH_PERFORMANCE_SCORE'),
    (HEALTH_ANOMALY_SCORE, 'HEALTH_ANOMALY_SCORE'),
    (HEALTH_RESOURCES_SCORE, 'HEALTH_RESOURCES_SCORE'),
    (HEALTH_SECURITY_THREAT_LEVEL, 'HEALTH_SECURITY_THREAT_LEVEL'),
)
HEALTHTREE_NODE_TYPE_HEALTH = 1
HEALTHTREE_NODE_TYPE_PERFORMANCE = 2
HEALTHTREE_NODE_TYPE_ANOMALY = 3
HEALTHTREE_NODE_TYPE_SECURITY = 4
HEALTHTREE_NODE_TYPE_RESOURCES = 5
HEALTHTREE_NODE_TYPE_METRIC = 6
HEALTHTREE_NODE_TYPE_INTERMEDIATE = 7
HEALTHTREE_NODE_TYPE_OTHER = 8
HealthTreeNodeTypeChoices = (
    (HEALTHTREE_NODE_TYPE_HEALTH, 'HEALTHTREE_NODE_TYPE_HEALTH'),
    (HEALTHTREE_NODE_TYPE_PERFORMANCE, 'HEALTHTREE_NODE_TYPE_PERFORMANCE'),
    (HEALTHTREE_NODE_TYPE_ANOMALY, 'HEALTHTREE_NODE_TYPE_ANOMALY'),
    (HEALTHTREE_NODE_TYPE_SECURITY, 'HEALTHTREE_NODE_TYPE_SECURITY'),
    (HEALTHTREE_NODE_TYPE_RESOURCES, 'HEALTHTREE_NODE_TYPE_RESOURCES'),
    (HEALTHTREE_NODE_TYPE_METRIC, 'HEALTHTREE_NODE_TYPE_METRIC'),
    (HEALTHTREE_NODE_TYPE_INTERMEDIATE, 'HEALTHTREE_NODE_TYPE_INTERMEDIATE'),
    (HEALTHTREE_NODE_TYPE_OTHER, 'HEALTHTREE_NODE_TYPE_OTHER'),
)
