
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *
from models_dns import *
from models_system import *
from models_common import *
from models_credentials import *

DOMAIN_DEFAULT = 0
DOMAIN_PRIVATE = 1
DOMAIN_PUBLIC = 2
DOMAIN_PRIVATE_PUBLIC = 3
DomainTypeChoices = (
    (DOMAIN_DEFAULT, 'DOMAIN_DEFAULT'),
    (DOMAIN_PRIVATE, 'DOMAIN_PRIVATE'),
    (DOMAIN_PUBLIC, 'DOMAIN_PUBLIC'),
    (DOMAIN_PRIVATE_PUBLIC, 'DOMAIN_PRIVATE_PUBLIC'),
)
IPAMDNS_TYPE_INFOBLOX = 1
IPAMDNS_TYPE_AWS = 2
IPAMDNS_TYPE_OPENSTACK = 3
IPAMDNS_TYPE_GCP = 4
IPAMDNS_TYPE_INFOBLOX_DNS = 5
IPAMDNS_TYPE_CUSTOM = 6
IPAMDNS_TYPE_CUSTOM_DNS = 7
IPAMDNS_TYPE_AZURE = 8
IPAMDNS_TYPE_OCI = 9
IPAMDNS_TYPE_TENCENT = 10
IPAMDNS_TYPE_INTERNAL = 100
IPAMDNS_TYPE_INTERNAL_DNS = 101
IPAMDNS_TYPE_AWS_DNS = 102
IPAMDNS_TYPE_AZURE_DNS = 103
IpamDnsTypeChoices = (
    (IPAMDNS_TYPE_INFOBLOX, 'IPAMDNS_TYPE_INFOBLOX'),
    (IPAMDNS_TYPE_AWS, 'IPAMDNS_TYPE_AWS'),
    (IPAMDNS_TYPE_OPENSTACK, 'IPAMDNS_TYPE_OPENSTACK'),
    (IPAMDNS_TYPE_GCP, 'IPAMDNS_TYPE_GCP'),
    (IPAMDNS_TYPE_INFOBLOX_DNS, 'IPAMDNS_TYPE_INFOBLOX_DNS'),
    (IPAMDNS_TYPE_CUSTOM, 'IPAMDNS_TYPE_CUSTOM'),
    (IPAMDNS_TYPE_CUSTOM_DNS, 'IPAMDNS_TYPE_CUSTOM_DNS'),
    (IPAMDNS_TYPE_AZURE, 'IPAMDNS_TYPE_AZURE'),
    (IPAMDNS_TYPE_OCI, 'IPAMDNS_TYPE_OCI'),
    (IPAMDNS_TYPE_TENCENT, 'IPAMDNS_TYPE_TENCENT'),
    (IPAMDNS_TYPE_INTERNAL, 'IPAMDNS_TYPE_INTERNAL'),
    (IPAMDNS_TYPE_INTERNAL_DNS, 'IPAMDNS_TYPE_INTERNAL_DNS'),
    (IPAMDNS_TYPE_AWS_DNS, 'IPAMDNS_TYPE_AWS_DNS'),
    (IPAMDNS_TYPE_AZURE_DNS, 'IPAMDNS_TYPE_AZURE_DNS'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.ipam_profile_pb2 import CustomIpamDnsProfile as CustomIpamDnsProfileProto

from models_common import Tenant


class CustomIpamDnsProfile (models.Model, GenBase):
    pb_class = CustomIpamDnsProfileProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'customipamdnsprofile-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(CustomIpamDnsProfile, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(CustomIpamDnsProfile, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(CustomIpamDnsProfile, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = CustomIpamDnsProfileProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('name')
        if self.name is not None:
            pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="customipamdnsprofile_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '499de975d2e64e0f'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.ipam_profile_pb2 import IpamDnsProviderProfile as IpamDnsProviderProfileProto

from models_common import Tenant


class IpamDnsProviderProfile (models.Model, GenBase):
    pb_class = IpamDnsProviderProfileProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'ipamdnsproviderprofile-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(IpamDnsProviderProfile, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(IpamDnsProviderProfile, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(IpamDnsProviderProfile, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = IpamDnsProviderProfileProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="ipamdnsproviderprofile_tenant_ref", on_delete=models.PROTECT)
    custom_ipam_dns_profile_ref_5eedec22057d4c3f_ref = models.ForeignKey(CustomIpamDnsProfile, null=True, blank=True, related_name="ipamdnscustomprofile_custom_ipam_dns_profile_ref_5eedec22057d4c3f", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.custom_profile.custom_ipam_dns_profile_uuid': ('refers_to', u'CustomIpamDnsProfile', '5eedec22057d4c3f'),
        'root.tencent_profile.cloud_credentials_uuid': ('hyperlink_to', u'CloudConnectorUser', 'b0e9bbb87e4c4261'),
        'root.internal_profile.dns_virtualservice_uuid': ('disp_hyperlink_to', u'VirtualService', '691dcf94050644c9'),
        'root.oci_profile.cloud_credentials_uuid': ('hyperlink_to', u'CloudConnectorUser', '3c7cbc01654f4e5e'),
        'root.internal_profile.usable_network_uuids': ('disp_hyperlink_to', u'Network', 'ad0782284122407f'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'ac8db737b4044c76'),
        'root.gcp_profile.usable_network_uuids': ('disp_hyperlink_to', u'Network', 'a6ec32008ecb40c7'),
    }
    sensitive_fields = {
        'root.infoblox_profile.password',
        'root.aws_profile.access_key_id',
        'root.aws_profile.secret_access_key',
        'root.openstack_profile.password',
        'root.azure_profile.azure_userpass.password',
        'root.azure_profile.azure_serviceprincipal.authentication_token',
        'root.proxy_configuration.password',
    }
    pb_check_fields = {
        'root.type': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

