
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_common import *
from models_options import *
from models_snmp import *
from models_auth import *
from models_match import *
from models_license_tier_type import *
from models_credentials import *

from models_ssl import *
NTP_AUTH_ALGORITHM_MD5 = 1
NTP_AUTH_ALGORITHM_SHA1 = 2
NTPAuthAlgorithmChoices = (
    (NTP_AUTH_ALGORITHM_MD5, 'NTP_AUTH_ALGORITHM_MD5'),
    (NTP_AUTH_ALGORITHM_SHA1, 'NTP_AUTH_ALGORITHM_SHA1'),
)
SMTP_NONE = 0
SMTP_LOCAL_HOST = 1
SMTP_SERVER = 2
SMTP_ANONYMOUS_SERVER = 3
SMTPTypeChoices = (
    (SMTP_NONE, 'SMTP_NONE'),
    (SMTP_LOCAL_HOST, 'SMTP_LOCAL_HOST'),
    (SMTP_SERVER, 'SMTP_SERVER'),
    (SMTP_ANONYMOUS_SERVER, 'SMTP_ANONYMOUS_SERVER'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.system_pb2 import SystemConfiguration as SystemConfigurationProto

from models_django_internal import Role
from models_auth import AuthProfile
from models_common import Tenant
from models_match import IpAddrGroup


class SystemConfiguration (models.Model, GenBase):
    pb_class = SystemConfigurationProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'systemconfiguration-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(SystemConfiguration, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(SystemConfiguration, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(SystemConfiguration, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = SystemConfigurationProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    sslprofile_ref_5c51886a3cc34045_ref = models.ForeignKey(SSLProfile, null=True, blank=True, related_name="portalconfiguration_sslprofile_ref_5c51886a3cc34045", on_delete=models.PROTECT)
    auth_profile_ref_37afd9ce22094719_ref = models.ForeignKey(AuthProfile, null=True, blank=True, related_name="adminauthconfiguration_auth_profile_ref_37afd9ce22094719", on_delete=models.PROTECT)
    group_refs = models.ManyToManyField(IpAddrGroup, related_name="systemconfiguration_ipaddrgroup", through="SysConIpAddGro")
    role_refs = models.ManyToManyField(Role, related_name="systemconfiguration_role", through="SysConRol")
    tenant_refs = models.ManyToManyField(Tenant, related_name="systemconfiguration_tenant", through="SysConTen")
    sslkeyandcertificate_refs = models.ManyToManyField(SSLKeyAndCertificate, related_name="systemconfiguration_sslkeyandcertificate", through="SysConSSLKeyAndCer")
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.dns_virtualservice_uuids': ('disp_hyperlink_to', u'VirtualService', 'bbde545875ed4f6d'),
        'root.mgmt_ip_access_control.shell_server_access.group_uuids': ('refers_to', u'IpAddrGroup', 'e32c89c22e32447d'),
        'root.admin_auth_configuration.mapping_rules.tenant_uuids': ('refers_to', u'Tenant', 'f3ee8d742dad40da'),
        'root.admin_auth_configuration.auth_profile_uuid': ('refers_to', u'AuthProfile', '37afd9ce22094719'),
        'root.mgmt_ip_access_control.sysint_access.group_uuids': ('refers_to', u'IpAddrGroup', '68dc0924ce2842ee'),
        'root.portal_configuration.sslprofile_uuid': ('refers_to', u'SSLProfile', '5c51886a3cc34045'),
        'root.mgmt_ip_access_control.snmp_access.group_uuids': ('refers_to', u'IpAddrGroup', '2df6e6d554574eb9'),
        'root.mgmt_ip_access_control.api_access.group_uuids': ('refers_to', u'IpAddrGroup', '728b5ef160514e46'),
        'root.mgmt_ip_access_control.ssh_access.group_uuids': ('refers_to', u'IpAddrGroup', '60e4e87814a344de'),
        'root.admin_auth_configuration.mapping_rules.role_uuids': ('refers_to', u'Role', '8c029a1d1e2148db'),
        'root.secure_channel_configuration.sslkeyandcertificate_uuids': ('refers_to', u'SSLKeyAndCertificate', '163e53836b984f96'),
        'root.portal_configuration.sslkeyandcertificate_uuids': ('refers_to', u'SSLKeyAndCertificate', 'c41b3f8d75ae47e7'),
    }
    sensitive_fields = {
        'root.email_configuration.auth_password',
        'root.snmp_configuration.community',
        'root.snmp_configuration.snmp_v3_config.user.auth_passphrase',
        'root.snmp_configuration.snmp_v3_config.user.priv_passphrase',
        'root.proxy_configuration.password',
    }
    pb_check_fields = {
        'root.docker_mode': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []


class SysConIpAddGro (models.Model):
    systemconfiguration = models.ForeignKey(SystemConfiguration, null=True, blank=True, on_delete=models.PROTECT) 
    ipaddrgroup = models.ForeignKey(IpAddrGroup, null=True, blank=True, on_delete=models.PROTECT) 

class SysConRol (models.Model):
    systemconfiguration = models.ForeignKey(SystemConfiguration, null=True, blank=True, on_delete=models.PROTECT) 
    role = models.ForeignKey(Role, null=True, blank=True, on_delete=models.PROTECT) 

class SysConTen (models.Model):
    systemconfiguration = models.ForeignKey(SystemConfiguration, null=True, blank=True, on_delete=models.PROTECT) 
    tenant = models.ForeignKey(Tenant, null=True, blank=True, on_delete=models.PROTECT) 

class SysConSSLKeyAndCer (models.Model):
    systemconfiguration = models.ForeignKey(SystemConfiguration, null=True, blank=True, on_delete=models.PROTECT) 
    sslkeyandcertificate = models.ForeignKey(SSLKeyAndCertificate, null=True, blank=True, on_delete=models.PROTECT) 


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.system_pb2 import ControllerSite as ControllerSiteProto

from models_common import Tenant


class ControllerSite (models.Model, GenBase):
    pb_class = ControllerSiteProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'controllersite-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(ControllerSite, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(ControllerSite, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(ControllerSite, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = ControllerSiteProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('name')
        if self.name is not None:
            pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="controllersite_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'e659adfe80004715'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

