
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_common import *
from models_options import *
from models_rate import *
from models_match import *
from models_analytics_policy import *

from models_health_monitor import *
from models_application_persistence_profile import *
from models_ssl import *
from models_server_autoscale import *
from models_vrf import *
from models_analytics_profile import *
from models_cloud_objects import *
FAIL_ACTION_HTTP_REDIRECT = 1
FAIL_ACTION_HTTP_LOCAL_RSP = 2
FAIL_ACTION_CLOSE_CONN = 3
FAIL_ACTION_BACKUP_POOL = 4
FailActionEnumChoices = (
    (FAIL_ACTION_HTTP_REDIRECT, 'FAIL_ACTION_HTTP_REDIRECT'),
    (FAIL_ACTION_HTTP_LOCAL_RSP, 'FAIL_ACTION_HTTP_LOCAL_RSP'),
    (FAIL_ACTION_CLOSE_CONN, 'FAIL_ACTION_CLOSE_CONN'),
    (FAIL_ACTION_BACKUP_POOL, 'FAIL_ACTION_BACKUP_POOL'),
)
FAIL_HTTP_STATUS_CODE_200 = 200
FAIL_HTTP_STATUS_CODE_503 = 503
FailHttpStatusCodeChoices = (
    (FAIL_HTTP_STATUS_CODE_200, 'FAIL_HTTP_STATUS_CODE_200'),
    (FAIL_HTTP_STATUS_CODE_503, 'FAIL_HTTP_STATUS_CODE_503'),
)
HTTP_RSP_4XX = 4
HTTP_RSP_5XX = 5
HttpReselectRespCodeBlockChoices = (
    (HTTP_RSP_4XX, 'HTTP_RSP_4XX'),
    (HTTP_RSP_5XX, 'HTTP_RSP_5XX'),
)
LB_ALGORITHM_LEAST_CONNECTIONS = 1
LB_ALGORITHM_ROUND_ROBIN = 2
LB_ALGORITHM_FASTEST_RESPONSE = 3
LB_ALGORITHM_CONSISTENT_HASH = 4
LB_ALGORITHM_LEAST_LOAD = 5
LB_ALGORITHM_FEWEST_SERVERS = 6
LB_ALGORITHM_RANDOM = 7
LB_ALGORITHM_FEWEST_TASKS = 8
LB_ALGORITHM_NEAREST_SERVER = 9
LB_ALGORITHM_CORE_AFFINITY = 10
LB_ALGORITHM_TOPOLOGY = 11
LbAlgorithmChoices = (
    (LB_ALGORITHM_LEAST_CONNECTIONS, 'LB_ALGORITHM_LEAST_CONNECTIONS'),
    (LB_ALGORITHM_ROUND_ROBIN, 'LB_ALGORITHM_ROUND_ROBIN'),
    (LB_ALGORITHM_FASTEST_RESPONSE, 'LB_ALGORITHM_FASTEST_RESPONSE'),
    (LB_ALGORITHM_CONSISTENT_HASH, 'LB_ALGORITHM_CONSISTENT_HASH'),
    (LB_ALGORITHM_LEAST_LOAD, 'LB_ALGORITHM_LEAST_LOAD'),
    (LB_ALGORITHM_FEWEST_SERVERS, 'LB_ALGORITHM_FEWEST_SERVERS'),
    (LB_ALGORITHM_RANDOM, 'LB_ALGORITHM_RANDOM'),
    (LB_ALGORITHM_FEWEST_TASKS, 'LB_ALGORITHM_FEWEST_TASKS'),
    (LB_ALGORITHM_NEAREST_SERVER, 'LB_ALGORITHM_NEAREST_SERVER'),
    (LB_ALGORITHM_CORE_AFFINITY, 'LB_ALGORITHM_CORE_AFFINITY'),
    (LB_ALGORITHM_TOPOLOGY, 'LB_ALGORITHM_TOPOLOGY'),
)
LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS = 1
LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS_AND_PORT = 2
LB_ALGORITHM_CONSISTENT_HASH_URI = 3
LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_HEADER = 4
LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_STRING = 5
LB_ALGORITHM_CONSISTENT_HASH_CALLID = 6
LbAlgorithmConsistentHashChoices = (
    (LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS, 'LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS'),
    (LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS_AND_PORT, 'LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS_AND_PORT'),
    (LB_ALGORITHM_CONSISTENT_HASH_URI, 'LB_ALGORITHM_CONSISTENT_HASH_URI'),
    (LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_HEADER, 'LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_HEADER'),
    (LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_STRING, 'LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_STRING'),
    (LB_ALGORITHM_CONSISTENT_HASH_CALLID, 'LB_ALGORITHM_CONSISTENT_HASH_CALLID'),
)
PERSISTENT_SERVER_INVALID = 0
PERSISTENT_SERVER_DOWN = 1
SRVR_DOWN = 2
ADD_PENDING = 3
SLOW_START_MAX_CONN = 4
MAX_CONN = 5
NO_LPORT = 6
SUSPECT_STATE = 7
MAX_CONN_RATE = 8
CAPEST_RAND_MAX_CONN = 9
GET_NEXT = 10
LbFailureChoices = (
    (PERSISTENT_SERVER_INVALID, 'PERSISTENT_SERVER_INVALID'),
    (PERSISTENT_SERVER_DOWN, 'PERSISTENT_SERVER_DOWN'),
    (SRVR_DOWN, 'SRVR_DOWN'),
    (ADD_PENDING, 'ADD_PENDING'),
    (SLOW_START_MAX_CONN, 'SLOW_START_MAX_CONN'),
    (MAX_CONN, 'MAX_CONN'),
    (NO_LPORT, 'NO_LPORT'),
    (SUSPECT_STATE, 'SUSPECT_STATE'),
    (MAX_CONN_RATE, 'MAX_CONN_RATE'),
    (CAPEST_RAND_MAX_CONN, 'CAPEST_RAND_MAX_CONN'),
    (GET_NEXT, 'GET_NEXT'),
)
EVALUATION_IN_PROGRESS = 0
IN_SERVICE = 1
OUT_OF_SERVICE = 2
EVALUATION_FAILED = 3
PoolDeploymentStateChoices = (
    (EVALUATION_IN_PROGRESS, 'EVALUATION_IN_PROGRESS'),
    (IN_SERVICE, 'IN_SERVICE'),
    (OUT_OF_SERVICE, 'OUT_OF_SERVICE'),
    (EVALUATION_FAILED, 'EVALUATION_FAILED'),
)
BLUE_GREEN = 1
CANARY = 2
PoolGroupDeploymentSchemeChoices = (
    (BLUE_GREEN, 'BLUE_GREEN'),
    (CANARY, 'CANARY'),
)
POOL_SERVER_UP = 1
POOL_SERVER_DOWN = 2
PoolServerStateEnumChoices = (
    (POOL_SERVER_UP, 'POOL_SERVER_UP'),
    (POOL_SERVER_DOWN, 'POOL_SERVER_DOWN'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.pool_pb2 import Pool as PoolProto

from models_common import Tenant


class Pool (models.Model, GenBase):
    pb_class = PoolProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'pool-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(Pool, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(Pool, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(Pool, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = PoolProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('apic_epg_name')
        if self.apic_epg_name is not None:
            pb.apic_epg_name = self.apic_epg_name
        pb.ClearField('ipaddrgroup_uuid')
        if self.ipaddrgroup_ref is not None:
            pb.ipaddrgroup_uuid = self.ipaddrgroup_ref
        pb.ClearField('enabled')
        if self.enabled is not None:
            pb.enabled = self.enabled
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        pb.ClearField('cloud_uuid')
        if self.cloud_ref is not None:
            pb.cloud_uuid = self.cloud_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    apic_epg_name = models.TextField(null=True, blank=True)
    ipaddrgroup_ref = models.TextField(null=True, blank=True)
    enabled = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="pool_tenant_ref", on_delete=models.PROTECT)
    cloud_ref = models.ForeignKey(Cloud, null=True, blank=True, related_name="pool_cloud_ref", on_delete=models.PROTECT)
    application_persistence_profile_ref_b4ceeda2241e46c3_ref = models.ForeignKey(ApplicationPersistenceProfile, null=True, blank=True, related_name="pool_application_persistence_profile_ref_b4ceeda2241e46c3", on_delete=models.PROTECT)
    ssl_profile_ref_434f9b8ab09e4837_ref = models.ForeignKey(SSLProfile, null=True, blank=True, related_name="pool_ssl_profile_ref_434f9b8ab09e4837", on_delete=models.PROTECT)
    backup_pool_ref_92225b69cc464f3a_ref = models.ForeignKey('self', null=True, blank=True, related_name="failactionbackuppool_backup_pool_ref_92225b69cc464f3a", on_delete=models.PROTECT)
    pki_profile_ref_e0a187c4b9084568_ref = models.ForeignKey(PKIProfile, null=True, blank=True, related_name="pool_pki_profile_ref_e0a187c4b9084568", on_delete=models.PROTECT)
    ssl_key_and_certificate_ref_d5a59e71b89c4fc2_ref = models.ForeignKey(SSLKeyAndCertificate, null=True, blank=True, related_name="pool_ssl_key_and_certificate_ref_d5a59e71b89c4fc2", on_delete=models.PROTECT)
    autoscale_policy_ref_27533dc008d74fdc_ref = models.ForeignKey(ServerAutoScalePolicy, null=True, blank=True, related_name="pool_autoscale_policy_ref_27533dc008d74fdc", on_delete=models.PROTECT)
    autoscale_launch_config_ref_f396d4a73c86418c_ref = models.ForeignKey(AutoScaleLaunchConfig, null=True, blank=True, related_name="pool_autoscale_launch_config_ref_f396d4a73c86418c", on_delete=models.PROTECT)
    vrf_ref_0532ead95c8b4e35_ref = models.ForeignKey(VrfContext, null=True, blank=True, related_name="pool_vrf_ref_0532ead95c8b4e35", on_delete=models.PROTECT)
    pool_ref_7965e29fb48847e5_ref = models.ForeignKey('self', null=True, blank=True, related_name="abpool_pool_ref_7965e29fb48847e5", on_delete=models.PROTECT)
    analytics_profile_ref_911a040655814b20_ref = models.ForeignKey(AnalyticsProfile, null=True, blank=True, related_name="pool_analytics_profile_ref_911a040655814b20", on_delete=models.PROTECT)
    health_monitor_refs = models.ManyToManyField(HealthMonitor, related_name="pool_healthmonitor", through="PooHeaMon")
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'bb49e0aeb21d4714'),
        'root.pki_profile_uuid': ('refers_to', u'PKIProfile', 'e0a187c4b9084568'),
        'root.ipaddrgroup_uuid': ('hyperlink_to', u'IpAddrGroup', '647ea0df17aa4512'),
        'root.servers.discovered_network_uuid': ('hyperlink_to', u'Network', 'caea6a4e948c44fd'),
        'root.cloud_uuid': ('belongs_to', u'Cloud', 'da291b15df274032'),
        'root.ssl_profile_uuid': ('refers_to', u'SSLProfile', '434f9b8ab09e4837'),
        'root.autoscale_policy_uuid': ('refers_to', u'ServerAutoScalePolicy', '27533dc008d74fdc'),
        'root.autoscale_launch_config_uuid': ('refers_to', u'AutoScaleLaunchConfig', 'f396d4a73c86418c'),
        'root.health_monitor_uuids': ('refers_to', u'HealthMonitor', 'e6c42a58c4bc467a'),
        'root.application_persistence_profile_uuid': ('refers_to', u'ApplicationPersistenceProfile', 'b4ceeda2241e46c3'),
        'root.networks.network_uuid': ('hyperlink_to', u'VIMgrNWRuntime', 'f027ac07599e4794'),
        'root.servers.vm_uuid': ('hyperlink_to', u'VIMgrVMRuntime', '2cf677c3af3d45b8'),
        'root.fail_action.backup_pool.backup_pool_uuid': ('refers_to', u'Pool', '92225b69cc464f3a'),
        'root.servers.discovered_networks.network_uuid': ('hyperlink_to', u'Network', '12764d2760bf43a7'),
        'root.ab_pool.pool_uuid': ('refers_to', u'Pool', '7965e29fb48847e5'),
        'root.servers.nw_uuid': ('hyperlink_to', u'VIMgrNWRuntime', '7ccb64c0b88240d8'),
        'root.placement_networks.network_uuid': ('hyperlink_to', u'Network', '38e8a8a8b7ab41b2'),
        'root.analytics_profile_uuid': ('refers_to', u'AnalyticsProfile', '911a040655814b20'),
        'root.ssl_key_and_certificate_uuid': ('refers_to', u'SSLKeyAndCertificate', 'd5a59e71b89c4fc2'),
        'root.vrf_uuid': ('weak_refers_to', u'VrfContext', '0532ead95c8b4e35'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.cloud_uuid': 'f_immutable',
        'root.servers.location': 'f_immutable',
        'root.created_by': 'f_immutable',
        'root.gslb_sp_enabled': 'f_readonly',
        'root.vrf_uuid': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref','cloud_ref',)

class PooHeaMon (models.Model):
    pool = models.ForeignKey(Pool, null=True, blank=True, on_delete=models.PROTECT) 
    healthmonitor = models.ForeignKey(HealthMonitor, null=True, blank=True, on_delete=models.PROTECT) 


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.pool_pb2 import PriorityLabels as PriorityLabelsProto

from models_common import Tenant


class PriorityLabels (models.Model, GenBase):
    pb_class = PriorityLabelsProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'prioritylabels-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(PriorityLabels, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(PriorityLabels, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(PriorityLabels, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = PriorityLabelsProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        pb.ClearField('cloud_uuid')
        if self.cloud_ref is not None:
            pb.cloud_uuid = self.cloud_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="prioritylabels_tenant_ref", on_delete=models.PROTECT)
    cloud_ref = models.ForeignKey(Cloud, null=True, blank=True, related_name="prioritylabels_cloud_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '7557fe6317724602'),
        'root.cloud_uuid': ('belongs_to', u'Cloud', '491d7f32181f44c4'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.cloud_uuid': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref','cloud_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.pool_pb2 import PoolGroupDeploymentPolicy as PoolGroupDeploymentPolicyProto

from models_common import Tenant


class PoolGroupDeploymentPolicy (models.Model, GenBase):
    pb_class = PoolGroupDeploymentPolicyProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'poolgroupdeploymentpolicy-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(PoolGroupDeploymentPolicy, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(PoolGroupDeploymentPolicy, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(PoolGroupDeploymentPolicy, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = PoolGroupDeploymentPolicyProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="poolgroupdeploymentpolicy_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '96192426eb2940d3'),
        'root.webhook_uuid': ('disp_hyperlink_to', u'Webhook', '935cc245b38f4970'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.pool_pb2 import PoolGroup as PoolGroupProto

from models_common import Tenant


class PoolGroup (models.Model, GenBase):
    pb_class = PoolGroupProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'poolgroup-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(PoolGroup, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(PoolGroup, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(PoolGroup, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = PoolGroupProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        pb.ClearField('cloud_uuid')
        if self.cloud_ref is not None:
            pb.cloud_uuid = self.cloud_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="poolgroup_tenant_ref", on_delete=models.PROTECT)
    cloud_ref = models.ForeignKey(Cloud, null=True, blank=True, related_name="poolgroup_cloud_ref", on_delete=models.PROTECT)
    pool_ref_f1ddf4512a854eb0_ref = models.ForeignKey(Pool, null=True, blank=True, related_name="poolgroupmember_pool_ref_f1ddf4512a854eb0", on_delete=models.PROTECT)
    priority_labels_ref_5a757f83d8d34031_ref = models.ForeignKey(PriorityLabels, null=True, blank=True, related_name="poolgroup_priority_labels_ref_5a757f83d8d34031", on_delete=models.PROTECT)
    backup_pool_ref_432e4dfc1139421b_ref = models.ForeignKey(Pool, null=True, blank=True, related_name="failactionbackuppool_backup_pool_ref_432e4dfc1139421b", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.cloud_uuid': ('belongs_to', u'Cloud', 'dffc1e84df5a438b'),
        'root.priority_labels_uuid': ('refers_to', u'PriorityLabels', '5a757f83d8d34031'),
        'root.members.pool_uuid': ('refers_to', u'Pool', 'f1ddf4512a854eb0'),
        'root.fail_action.backup_pool.backup_pool_uuid': ('refers_to', u'Pool', '432e4dfc1139421b'),
        'root.deployment_policy_uuid': ('disp_hyperlink_to', u'PoolGroupDeploymentPolicy', 'd8308927f28e4d92'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', '5f4cbe03b2b047a9'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.cloud_uuid': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref','cloud_ref',)

