
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *

from models_common import *
TASK_QUEUE_DEBUG = 0
RPC_INFRA_DEBUG = 1
JOB_MGR_DEBUG = 2
TRANSACTION_DEBUG = 3
SE_AGENT_DEBUG = 4
SE_AGENT_METRICS_DEBUG = 5
VIRTUALSERVICE_DEBUG = 7
RES_MGR_DEBUG = 8
SE_MGR_DEBUG = 9
VI_MGR_DEBUG = 10
METRICS_MANAGER_DEBUG = 11
METRICS_MGR_DEBUG = 12
EVENT_API_DEBUG = 13
HS_MGR_DEBUG = 14
ALERT_MGR_DEBUG = 15
AUTOSCALE_MGR_DEBUG = 16
APIC_AGENT_DEBUG = 17
REDIS_INFRA_DEBUG = 18
CLOUD_CONNECTOR_DEBUG = 19
MESOS_METRICS_DEBUG = 20
STATECACHE_MGR_DEBUG = 21
NSX_AGENT_DEBUG = 22
SE_AGENT_CPU_UTIL_DEBUG = 23
SE_AGENT_MEM_UTIL_DEBUG = 24
SE_RPC_PROXY_DEBUG = 25
SE_AGENT_GSLB_DEBUG = 26
METRICSAPI_SRV_DEBUG = 27
DebugControllerModuleTypeChoices = (
    (TASK_QUEUE_DEBUG, 'TASK_QUEUE_DEBUG'),
    (RPC_INFRA_DEBUG, 'RPC_INFRA_DEBUG'),
    (JOB_MGR_DEBUG, 'JOB_MGR_DEBUG'),
    (TRANSACTION_DEBUG, 'TRANSACTION_DEBUG'),
    (SE_AGENT_DEBUG, 'SE_AGENT_DEBUG'),
    (SE_AGENT_METRICS_DEBUG, 'SE_AGENT_METRICS_DEBUG'),
    (VIRTUALSERVICE_DEBUG, 'VIRTUALSERVICE_DEBUG'),
    (RES_MGR_DEBUG, 'RES_MGR_DEBUG'),
    (SE_MGR_DEBUG, 'SE_MGR_DEBUG'),
    (VI_MGR_DEBUG, 'VI_MGR_DEBUG'),
    (METRICS_MANAGER_DEBUG, 'METRICS_MANAGER_DEBUG'),
    (METRICS_MGR_DEBUG, 'METRICS_MGR_DEBUG'),
    (EVENT_API_DEBUG, 'EVENT_API_DEBUG'),
    (HS_MGR_DEBUG, 'HS_MGR_DEBUG'),
    (ALERT_MGR_DEBUG, 'ALERT_MGR_DEBUG'),
    (AUTOSCALE_MGR_DEBUG, 'AUTOSCALE_MGR_DEBUG'),
    (APIC_AGENT_DEBUG, 'APIC_AGENT_DEBUG'),
    (REDIS_INFRA_DEBUG, 'REDIS_INFRA_DEBUG'),
    (CLOUD_CONNECTOR_DEBUG, 'CLOUD_CONNECTOR_DEBUG'),
    (MESOS_METRICS_DEBUG, 'MESOS_METRICS_DEBUG'),
    (STATECACHE_MGR_DEBUG, 'STATECACHE_MGR_DEBUG'),
    (NSX_AGENT_DEBUG, 'NSX_AGENT_DEBUG'),
    (SE_AGENT_CPU_UTIL_DEBUG, 'SE_AGENT_CPU_UTIL_DEBUG'),
    (SE_AGENT_MEM_UTIL_DEBUG, 'SE_AGENT_MEM_UTIL_DEBUG'),
    (SE_RPC_PROXY_DEBUG, 'SE_RPC_PROXY_DEBUG'),
    (SE_AGENT_GSLB_DEBUG, 'SE_AGENT_GSLB_DEBUG'),
    (METRICSAPI_SRV_DEBUG, 'METRICSAPI_SRV_DEBUG'),
)
LOG_LEVEL_DISABLED = 0
LOG_LEVEL_INFO = 1
LOG_LEVEL_WARNING = 2
LOG_LEVEL_ERROR = 3
LogLevelChoices = (
    (LOG_LEVEL_DISABLED, 'LOG_LEVEL_DISABLED'),
    (LOG_LEVEL_INFO, 'LOG_LEVEL_INFO'),
    (LOG_LEVEL_WARNING, 'LOG_LEVEL_WARNING'),
    (LOG_LEVEL_ERROR, 'LOG_LEVEL_ERROR'),
)
TRACE_LEVEL_DISABLED = 0
TRACE_LEVEL_ERROR = 1
TRACE_LEVEL_DEBUG = 2
TRACE_LEVEL_DEBUG_DETAIL = 3
TraceLevelChoices = (
    (TRACE_LEVEL_DISABLED, 'TRACE_LEVEL_DISABLED'),
    (TRACE_LEVEL_ERROR, 'TRACE_LEVEL_ERROR'),
    (TRACE_LEVEL_DEBUG, 'TRACE_LEVEL_DEBUG'),
    (TRACE_LEVEL_DEBUG_DETAIL, 'TRACE_LEVEL_DEBUG_DETAIL'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.debug_controller_pb2 import DebugController as DebugControllerProto



class DebugController (models.Model, GenBase):
    pb_class = DebugControllerProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'debugcontroller-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(DebugController, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(DebugController, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(DebugController, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = DebugControllerProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="debugcontroller_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.filters.state_cache_mgr_debug_filter.pool_uuid': ('disp_hyperlink_to', u'Pool', '2420bb91dde14e4d'),
        'root.filters.autoscale_mgr_debug_filter.pool_uuid': ('disp_hyperlink_to', u'Pool', 'd8355dbdfb504f19'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', '339d100ee3c84804'),
        'root.filters.state_cache_mgr_debug_filter.vs_uuid': ('disp_hyperlink_to', u'VirtualService', '9da0ccac3be64686'),
        'root.filters.metricsapi_srv_debug_filter.entity_uuid': ('disp_hyperlink_to', u'Virtualservice', '410140e82d284891'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

