
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *

from models_common import *
JOB_TYPE_VS_FULL_LOGS = 1
JOB_TYPE_VS_UDF = 2
JOB_TYPE_VS_METRICS_RT = 3
JOB_TYPE_SSL_CERT = 4
JOB_TYPE_DEBUGVS_PKT_CAPTURE = 5
JOB_TYPE_CONSISTENCY_CHECK = 6
JOB_TYPE_TECHSUPPORT = 7
JOB_TYPE_PKI_PROFILE = 8
JOB_TYPE_NSP_RULE = 9
JOB_TYPE_SEGROUP_METRICS_RT = 10
JOB_TYPE_POSTGRES_STATUS = 11
JOB_TYPE_VS_ROTATE_KEYS = 12
JOB_TYPE_POOL_DNS = 13
JOB_TYPE_GSLB_SERVICE = 14
JOB_TYPE_APP_PERSISTENCE = 15
JOB_TYPE_PROCESS_LOCKED_USER_ACCOUNTS = 16
JOB_TYPE_SESSION = 17
JOB_TYPE_AUTHTOKEN = 18
JOB_TYPE_CLUSTER = 19
JOB_TYPE_SE_SECURE_CHANNEL_CLEANUP = 20
JobTypeChoices = (
    (JOB_TYPE_VS_FULL_LOGS, 'JOB_TYPE_VS_FULL_LOGS'),
    (JOB_TYPE_VS_UDF, 'JOB_TYPE_VS_UDF'),
    (JOB_TYPE_VS_METRICS_RT, 'JOB_TYPE_VS_METRICS_RT'),
    (JOB_TYPE_SSL_CERT, 'JOB_TYPE_SSL_CERT'),
    (JOB_TYPE_DEBUGVS_PKT_CAPTURE, 'JOB_TYPE_DEBUGVS_PKT_CAPTURE'),
    (JOB_TYPE_CONSISTENCY_CHECK, 'JOB_TYPE_CONSISTENCY_CHECK'),
    (JOB_TYPE_TECHSUPPORT, 'JOB_TYPE_TECHSUPPORT'),
    (JOB_TYPE_PKI_PROFILE, 'JOB_TYPE_PKI_PROFILE'),
    (JOB_TYPE_NSP_RULE, 'JOB_TYPE_NSP_RULE'),
    (JOB_TYPE_SEGROUP_METRICS_RT, 'JOB_TYPE_SEGROUP_METRICS_RT'),
    (JOB_TYPE_POSTGRES_STATUS, 'JOB_TYPE_POSTGRES_STATUS'),
    (JOB_TYPE_VS_ROTATE_KEYS, 'JOB_TYPE_VS_ROTATE_KEYS'),
    (JOB_TYPE_POOL_DNS, 'JOB_TYPE_POOL_DNS'),
    (JOB_TYPE_GSLB_SERVICE, 'JOB_TYPE_GSLB_SERVICE'),
    (JOB_TYPE_APP_PERSISTENCE, 'JOB_TYPE_APP_PERSISTENCE'),
    (JOB_TYPE_PROCESS_LOCKED_USER_ACCOUNTS, 'JOB_TYPE_PROCESS_LOCKED_USER_ACCOUNTS'),
    (JOB_TYPE_SESSION, 'JOB_TYPE_SESSION'),
    (JOB_TYPE_AUTHTOKEN, 'JOB_TYPE_AUTHTOKEN'),
    (JOB_TYPE_CLUSTER, 'JOB_TYPE_CLUSTER'),
    (JOB_TYPE_SE_SECURE_CHANNEL_CLEANUP, 'JOB_TYPE_SE_SECURE_CHANNEL_CLEANUP'),
)
SINGLETON_JOB_AUTHTOKEN = 1
SINGLETON_JOB_SESSION = 2
SINGLETON_JOB_CLUSTER = 3
SINGLETON_JOB_PROCESS_LOCKED_USER_ACCOUNTS = 4
SINGLETON_JOB_CONSISTENCY_CHECK = 5
SINGLETON_JOB_TECH_SUPPORT = 6
SINGLETON_JOB_SE_SECURE_CHANNEL_CLEANUP = 7
SingletonJobUuidChoices = (
    (SINGLETON_JOB_AUTHTOKEN, 'SINGLETON_JOB_AUTHTOKEN'),
    (SINGLETON_JOB_SESSION, 'SINGLETON_JOB_SESSION'),
    (SINGLETON_JOB_CLUSTER, 'SINGLETON_JOB_CLUSTER'),
    (SINGLETON_JOB_PROCESS_LOCKED_USER_ACCOUNTS, 'SINGLETON_JOB_PROCESS_LOCKED_USER_ACCOUNTS'),
    (SINGLETON_JOB_CONSISTENCY_CHECK, 'SINGLETON_JOB_CONSISTENCY_CHECK'),
    (SINGLETON_JOB_TECH_SUPPORT, 'SINGLETON_JOB_TECH_SUPPORT'),
    (SINGLETON_JOB_SE_SECURE_CHANNEL_CLEANUP, 'SINGLETON_JOB_SE_SECURE_CHANNEL_CLEANUP'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.job_db_pb2 import JobEntry as JobEntryProto



class JobEntry (models.Model, GenBase):
    pb_class = JobEntryProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'jobentry-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(JobEntry, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(JobEntry, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(JobEntry, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = JobEntryProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.obj_key = self.obj_key
        pb.expires_at = self.expires_at
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    obj_key = models.TextField(null=False, blank=False)
    expires_at = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="jobentry_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'd7d9d9e4fb46450f'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

