
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *

from models_common import *
PERSISTENCE_TYPE_CLIENT_IP_ADDRESS = 1
PERSISTENCE_TYPE_HTTP_COOKIE = 2
PERSISTENCE_TYPE_TLS = 3
PERSISTENCE_TYPE_CLIENT_IPV6_ADDRESS = 4
PERSISTENCE_TYPE_CUSTOM_HTTP_HEADER = 5
PERSISTENCE_TYPE_APP_COOKIE = 6
PERSISTENCE_TYPE_GSLB_SITE = 7
PersistenceProfileTypeChoices = (
    (PERSISTENCE_TYPE_CLIENT_IP_ADDRESS, 'PERSISTENCE_TYPE_CLIENT_IP_ADDRESS'),
    (PERSISTENCE_TYPE_HTTP_COOKIE, 'PERSISTENCE_TYPE_HTTP_COOKIE'),
    (PERSISTENCE_TYPE_TLS, 'PERSISTENCE_TYPE_TLS'),
    (PERSISTENCE_TYPE_CLIENT_IPV6_ADDRESS, 'PERSISTENCE_TYPE_CLIENT_IPV6_ADDRESS'),
    (PERSISTENCE_TYPE_CUSTOM_HTTP_HEADER, 'PERSISTENCE_TYPE_CUSTOM_HTTP_HEADER'),
    (PERSISTENCE_TYPE_APP_COOKIE, 'PERSISTENCE_TYPE_APP_COOKIE'),
    (PERSISTENCE_TYPE_GSLB_SITE, 'PERSISTENCE_TYPE_GSLB_SITE'),
)
HM_DOWN_PICK_NEW_SERVER = 1
HM_DOWN_ABORT_CONNECTION = 2
HM_DOWN_CONTINUE_PERSISTENT_SERVER = 3
PersistentServerHMDownRecoveryChoices = (
    (HM_DOWN_PICK_NEW_SERVER, 'HM_DOWN_PICK_NEW_SERVER'),
    (HM_DOWN_ABORT_CONNECTION, 'HM_DOWN_ABORT_CONNECTION'),
    (HM_DOWN_CONTINUE_PERSISTENT_SERVER, 'HM_DOWN_CONTINUE_PERSISTENT_SERVER'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.application_persistence_profile_pb2 import ApplicationPersistenceProfile as ApplicationPersistenceProfileProto



class ApplicationPersistenceProfile (models.Model, GenBase):
    pb_class = ApplicationPersistenceProfileProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'applicationpersistenceprofile-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(ApplicationPersistenceProfile, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(ApplicationPersistenceProfile, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(ApplicationPersistenceProfile, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = ApplicationPersistenceProfileProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('is_federated')
        if self.is_federated is not None:
            pb.is_federated = self.is_federated
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    is_federated = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="applicationpersistenceprofile_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '699e4ba4f70b436c'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.persistence_type': 'f_immutable',
        'root.is_federated': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

