
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *
from models_common import *
from models_health_monitor import *
from models_application_persistence_profile import *

NO_ERROR = 0
FILE_ERROR = 1
FILE_FORMAT_ERROR = 2
FILE_NO_RESOURCES = 3
GeoDbFailureReasonChoices = (
    (NO_ERROR, 'NO_ERROR'),
    (FILE_ERROR, 'FILE_ERROR'),
    (FILE_FORMAT_ERROR, 'FILE_FORMAT_ERROR'),
    (FILE_NO_RESOURCES, 'FILE_NO_RESOURCES'),
)
GSLB_ALGORITHM_ROUND_ROBIN = 1
GSLB_ALGORITHM_CONSISTENT_HASH = 2
GSLB_ALGORITHM_GEO = 3
GSLB_ALGORITHM_TOPOLOGY = 4
GslbAlgorithmChoices = (
    (GSLB_ALGORITHM_ROUND_ROBIN, 'GSLB_ALGORITHM_ROUND_ROBIN'),
    (GSLB_ALGORITHM_CONSISTENT_HASH, 'GSLB_ALGORITHM_CONSISTENT_HASH'),
    (GSLB_ALGORITHM_GEO, 'GSLB_ALGORITHM_GEO'),
    (GSLB_ALGORITHM_TOPOLOGY, 'GSLB_ALGORITHM_TOPOLOGY'),
)
GSLB_GEODB_FILE_FORMAT_AVI = 1
GSLB_GEODB_FILE_FORMAT_MAXMIND_CITY = 2
GslbGeoDbFileFormatChoices = (
    (GSLB_GEODB_FILE_FORMAT_AVI, 'GSLB_GEODB_FILE_FORMAT_AVI'),
    (GSLB_GEODB_FILE_FORMAT_MAXMIND_CITY, 'GSLB_GEODB_FILE_FORMAT_MAXMIND_CITY'),
)
GSLB_LOCATION_SRC_USER_CONFIGURED = 1
GSLB_LOCATION_SRC_INHERIT_FROM_SITE = 2
GSLB_LOCATION_SRC_FROM_GEODB = 3
GslbGeoLocationSourceChoices = (
    (GSLB_LOCATION_SRC_USER_CONFIGURED, 'GSLB_LOCATION_SRC_USER_CONFIGURED'),
    (GSLB_LOCATION_SRC_INHERIT_FROM_SITE, 'GSLB_LOCATION_SRC_INHERIT_FROM_SITE'),
    (GSLB_LOCATION_SRC_FROM_GEODB, 'GSLB_LOCATION_SRC_FROM_GEODB'),
)
GSLB_HEALTH_MONITOR_PROXY_ALL_MEMBERS = 1
GSLB_HEALTH_MONITOR_PROXY_PRIVATE_MEMBERS = 2
GslbHealthMonitorProxyTypeChoices = (
    (GSLB_HEALTH_MONITOR_PROXY_ALL_MEMBERS, 'GSLB_HEALTH_MONITOR_PROXY_ALL_MEMBERS'),
    (GSLB_HEALTH_MONITOR_PROXY_PRIVATE_MEMBERS, 'GSLB_HEALTH_MONITOR_PROXY_PRIVATE_MEMBERS'),
)
GSLB_IP_PUBLIC = 1
GSLB_IP_PRIVATE = 2
GslbIpAddrTypeChoices = (
    (GSLB_IP_PUBLIC, 'GSLB_IP_PUBLIC'),
    (GSLB_IP_PRIVATE, 'GSLB_IP_PRIVATE'),
)
GSLB_OBJECT_CHANGED = 1
GSLB_OBJECT_UNCHANGED = 2
GSLB_OBJECT_DELETE = 3
GslbObjectStateChoices = (
    (GSLB_OBJECT_CHANGED, 'GSLB_OBJECT_CHANGED'),
    (GSLB_OBJECT_UNCHANGED, 'GSLB_OBJECT_UNCHANGED'),
    (GSLB_OBJECT_DELETE, 'GSLB_OBJECT_DELETE'),
)
GSLB_SERVICE_ALGORITHM_PRIORITY = 1
GSLB_SERVICE_ALGORITHM_GEO = 2
GslbServiceAlgorithmChoices = (
    (GSLB_SERVICE_ALGORITHM_PRIORITY, 'GSLB_SERVICE_ALGORITHM_PRIORITY'),
    (GSLB_SERVICE_ALGORITHM_GEO, 'GSLB_SERVICE_ALGORITHM_GEO'),
)
GSLB_SERVICE_DOWN_RESPONSE_NONE = 0
GSLB_SERVICE_DOWN_RESPONSE_ALL_RECORDS = 1
GSLB_SERVICE_DOWN_RESPONSE_FALLBACK_IP = 2
GSLB_SERVICE_DOWN_RESPONSE_EMPTY = 3
GslbServiceDownResponseTypeChoices = (
    (GSLB_SERVICE_DOWN_RESPONSE_NONE, 'GSLB_SERVICE_DOWN_RESPONSE_NONE'),
    (GSLB_SERVICE_DOWN_RESPONSE_ALL_RECORDS, 'GSLB_SERVICE_DOWN_RESPONSE_ALL_RECORDS'),
    (GSLB_SERVICE_DOWN_RESPONSE_FALLBACK_IP, 'GSLB_SERVICE_DOWN_RESPONSE_FALLBACK_IP'),
    (GSLB_SERVICE_DOWN_RESPONSE_EMPTY, 'GSLB_SERVICE_DOWN_RESPONSE_EMPTY'),
)
GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS = 1
GSLB_SERVICE_HEALTH_MONITOR_ONLY_NON_AVI_MEMBERS = 2
GslbServiceHealthMonitorScopeChoices = (
    (GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS, 'GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS'),
    (GSLB_SERVICE_HEALTH_MONITOR_ONLY_NON_AVI_MEMBERS, 'GSLB_SERVICE_HEALTH_MONITOR_ONLY_NON_AVI_MEMBERS'),
)
GSLB_ACTIVE_MEMBER = 1
GSLB_PASSIVE_MEMBER = 2
SiteMemberTypeChoices = (
    (GSLB_ACTIVE_MEMBER, 'GSLB_ACTIVE_MEMBER'),
    (GSLB_PASSIVE_MEMBER, 'GSLB_PASSIVE_MEMBER'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.gslb_pb2 import GslbSite as GslbSiteProto



class GslbSite (models.Model, GenBase):
    pb_class = GslbSiteProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'gslbsite-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(GslbSite, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(GslbSite, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(GslbSite, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = GslbSiteProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('name')
        if self.name is not None:
            pb.name = self.name
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
    }
    sensitive_fields = {
        'root.password',
    }
    pb_check_fields = {
        'root.uuid': 'f_internal',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.gslb_pb2 import GslbThirdPartySite as GslbThirdPartySiteProto



class GslbThirdPartySite (models.Model, GenBase):
    pb_class = GslbThirdPartySiteProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'gslbthirdpartysite-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(GslbThirdPartySite, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(GslbThirdPartySite, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(GslbThirdPartySite, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = GslbThirdPartySiteProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('name')
        if self.name is not None:
            pb.name = self.name
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.cluster_uuid': 'f_readonly',
        'root.uuid': 'f_internal',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.gslb_pb2 import Gslb as GslbProto

from models_common import Tenant


class Gslb (models.Model, GenBase):
    pb_class = GslbProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'gslb-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(Gslb, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(Gslb, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(Gslb, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = GslbProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('is_federated')
        if self.is_federated is not None:
            pb.is_federated = self.is_federated
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    is_federated = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="gslb_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '62520fae010e48ee'),
    }
    sensitive_fields = {
        'root.sites.password',
    }
    pb_check_fields = {
        'root.third_party_sites.uuid': 'f_internal',
        'root.third_party_sites.cluster_uuid': 'f_readonly',
        'root.view_id': 'f_immutable',
        'root.send_interval_prior_to_maintenance_mode': 'f_internal',
        'root.is_federated': 'f_immutable',
        'root.maintenance_mode': 'f_immutable',
        'root.sites.uuid': 'f_internal',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.gslb_pb2 import GslbService as GslbServiceProto

from models_health_monitor import HealthMonitor
from models_application_persistence_profile import ApplicationPersistenceProfile
from models_common import Tenant


class GslbService (models.Model, GenBase):
    pb_class = GslbServiceProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'gslbservice-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(GslbService, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(GslbService, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(GslbService, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = GslbServiceProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('is_federated')
        if self.is_federated is not None:
            pb.is_federated = self.is_federated
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    is_federated = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="gslbservice_tenant_ref", on_delete=models.PROTECT)
    application_persistence_profile_ref_83daf57254af4302_ref = models.ForeignKey(ApplicationPersistenceProfile, null=True, blank=True, related_name="gslbservice_application_persistence_profile_ref_83daf57254af4302", on_delete=models.PROTECT)
    health_monitor_refs = models.ManyToManyField(HealthMonitor, related_name="gslbservice_healthmonitor", through="GslSerHeaMon")
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.application_persistence_profile_uuid': ('refers_to', u'ApplicationPersistenceProfile', '83daf57254af4302'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', '08dee8ef600a405a'),
        'root.health_monitor_uuids': ('refers_to', u'HealthMonitor', 'fe6d248cb3a646df'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.groups.members.hm_proxies': 'f_internal',
        'root.is_federated': 'f_immutable',
        'root.hm_off': 'f_internal',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

class GslSerHeaMon (models.Model):
    gslbservice = models.ForeignKey(GslbService, null=True, blank=True, on_delete=models.PROTECT) 
    healthmonitor = models.ForeignKey(HealthMonitor, null=True, blank=True, on_delete=models.PROTECT) 


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.gslb_pb2 import GslbGeoDbProfile as GslbGeoDbProfileProto

from models_common import Tenant


class GslbGeoDbProfile (models.Model, GenBase):
    pb_class = GslbGeoDbProfileProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'gslbgeodbprofile-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(GslbGeoDbProfile, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(GslbGeoDbProfile, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(GslbGeoDbProfile, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = GslbGeoDbProfileProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.ClearField('is_federated')
        if self.is_federated is not None:
            pb.is_federated = self.is_federated
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    is_federated = models.NullBooleanField(null=True, blank=True)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="gslbgeodbprofile_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '5bdc0af3e5b94ff2'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.entries.file.format': 'f_immutable',
        'root.is_federated': 'f_immutable',
        'root.entries.file.file_id': 'f_readonly',
        'root.entries.file.filename': 'f_immutable',
        'root.entries.file.checksum': 'f_readonly',
        'root.entries.file.timestamp': 'f_readonly',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.gslb_pb2 import GslbDnsUpdate as GslbDnsUpdateProto



class GslbDnsUpdate (models.Model, GenBase):
    pb_class = GslbDnsUpdateProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'gslbdnsupdate-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(GslbDnsUpdate, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(GslbDnsUpdate, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(GslbDnsUpdate, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = GslbDnsUpdateProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []


