
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *
from models_common import *
from models_match import *
from models_http_codes import *
from models_app_learning import *

WAF_FAILURE_MODE_OPEN = 0
WAF_FAILURE_MODE_CLOSED = 1
WafFailureModeChoices = (
    (WAF_FAILURE_MODE_OPEN, 'WAF_FAILURE_MODE_OPEN'),
    (WAF_FAILURE_MODE_CLOSED, 'WAF_FAILURE_MODE_CLOSED'),
)
WAF_MODE_DETECTION_ONLY = 0
WAF_MODE_ENFORCEMENT = 1
WafModeChoices = (
    (WAF_MODE_DETECTION_ONLY, 'WAF_MODE_DETECTION_ONLY'),
    (WAF_MODE_ENFORCEMENT, 'WAF_MODE_ENFORCEMENT'),
)
WAF_PARANOIA_LEVEL_LOW = 0
WAF_PARANOIA_LEVEL_MEDIUM = 1
WAF_PARANOIA_LEVEL_HIGH = 2
WAF_PARANOIA_LEVEL_EXTREME = 3
WafParanoiaLevelChoices = (
    (WAF_PARANOIA_LEVEL_LOW, 'WAF_PARANOIA_LEVEL_LOW'),
    (WAF_PARANOIA_LEVEL_MEDIUM, 'WAF_PARANOIA_LEVEL_MEDIUM'),
    (WAF_PARANOIA_LEVEL_HIGH, 'WAF_PARANOIA_LEVEL_HIGH'),
    (WAF_PARANOIA_LEVEL_EXTREME, 'WAF_PARANOIA_LEVEL_EXTREME'),
)
WAF_VARIABLE_ARGS = 0
WAF_VARIABLE_ARGS_GET = 1
WAF_VARIABLE_ARGS_POST = 2
WAF_VARIABLE_ARGS_NAMES = 3
WAF_VARIABLE_REQUEST_COOKIES = 4
WAF_VARIABLE_QUERY_STRING = 5
WAF_VARIABLE_REQUEST_BASENAME = 6
WAF_VARIABLE_REQUEST_URI = 7
WAF_VARIABLE_PATH_INFO = 8
WafVariableChoices = (
    (WAF_VARIABLE_ARGS, 'WAF_VARIABLE_ARGS'),
    (WAF_VARIABLE_ARGS_GET, 'WAF_VARIABLE_ARGS_GET'),
    (WAF_VARIABLE_ARGS_POST, 'WAF_VARIABLE_ARGS_POST'),
    (WAF_VARIABLE_ARGS_NAMES, 'WAF_VARIABLE_ARGS_NAMES'),
    (WAF_VARIABLE_REQUEST_COOKIES, 'WAF_VARIABLE_REQUEST_COOKIES'),
    (WAF_VARIABLE_QUERY_STRING, 'WAF_VARIABLE_QUERY_STRING'),
    (WAF_VARIABLE_REQUEST_BASENAME, 'WAF_VARIABLE_REQUEST_BASENAME'),
    (WAF_VARIABLE_REQUEST_URI, 'WAF_VARIABLE_REQUEST_URI'),
    (WAF_VARIABLE_PATH_INFO, 'WAF_VARIABLE_PATH_INFO'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.waf_pb2 import WafProfile as WafProfileProto

from models_common import Tenant


class WafProfile (models.Model, GenBase):
    pb_class = WafProfileProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'wafprofile-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(WafProfile, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(WafProfile, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(WafProfile, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = WafProfileProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="wafprofile_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'dfeae3d988a24418'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.waf_pb2 import WafCRS as WafCRSProto

from models_common import Tenant


class WafCRS (models.Model, GenBase):
    pb_class = WafCRSProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'wafcrs-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(WafCRS, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(WafCRS, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(WafCRS, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = WafCRSProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('name')
        if self.name is not None:
            pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="wafcrs_tenant_ref", on_delete=models.PROTECT)
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', 'b920c311eb3a4ec9'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.uuid': 'f_immutable',
        'root.tenant_uuid': 'f_immutable',
        'root.groups.rules.tags': 'f_immutable',
        'root.release_date': 'f_immutable',
        'root.version': 'f_immutable',
        'root.name': 'f_immutable',
        'root.description': 'f_immutable',
        'root.groups': 'f_immutable',
        'root.integrity': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.waf_pb2 import WafPolicyPSMGroup as WafPolicyPSMGroupProto

from models_match import StringGroup
from models_common import Tenant


class WafPolicyPSMGroup (models.Model, GenBase):
    pb_class = WafPolicyPSMGroupProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'wafpolicypsmgroup-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(WafPolicyPSMGroup, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(WafPolicyPSMGroup, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(WafPolicyPSMGroup, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = WafPolicyPSMGroupProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        pb.ClearField('name')
        if self.name is not None:
            pb.name = self.name
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="wafpolicypsmgroup_tenant_ref", on_delete=models.PROTECT)
    name = models.TextField(null=False, blank=False)
    string_group_refs = models.ManyToManyField(StringGroup, related_name="wafpolicypsmgroup_stringgroup", through="WafPolPSMGroStrGro")
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.tenant_uuid': ('belongs_to', u'Tenant', '126aad92f0ff428b'),
        'root.locations.match.path.string_group_uuids': ('refers_to', u'StringGroup', '93a69f9ef8d7434b'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.is_learning_group': 'f_immutable',
        'root.tenant_uuid': 'f_immutable',
        'root.locations.rules.rule_id': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

class WafPolPSMGroStrGro (models.Model):
    wafpolicypsmgroup = models.ForeignKey(WafPolicyPSMGroup, null=True, blank=True, on_delete=models.PROTECT) 
    stringgroup = models.ForeignKey(StringGroup, null=True, blank=True, on_delete=models.PROTECT) 


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.waf_pb2 import WafPolicy as WafPolicyProto

from models_match import IpAddrGroup
from models_match import StringGroup
from models_common import Tenant


class WafPolicy (models.Model, GenBase):
    pb_class = WafPolicyProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'wafpolicy-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(WafPolicy, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(WafPolicy, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(WafPolicy, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = WafPolicyProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.name = self.name
        pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=False, blank=False, related_name="wafpolicy_tenant_ref", on_delete=models.PROTECT)
    waf_profile_ref_ac1e57a6af184231_ref = models.ForeignKey(WafProfile, null=True, blank=True, related_name="wafpolicy_waf_profile_ref_ac1e57a6af184231", on_delete=models.PROTECT)
    group_refs = models.ManyToManyField(IpAddrGroup, related_name="wafpolicy_ipaddrgroup", through="WafPolIpAddGro")
    string_group_refs = models.ManyToManyField(StringGroup, related_name="wafpolicy_stringgroup", through="WafPolStrGro")
    group_refs = models.ManyToManyField(WafPolicyPSMGroup, related_name="wafpolicy_wafpolicypsmgroup", through="WafPolWafPolPSMGro")
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.waf_profile_uuid': ('refers_to', u'WafProfile', 'ac1e57a6af184231'),
        'root.whitelist.rules.match.query.string_group_uuids': ('refers_to', u'StringGroup', '8b6e5abe5eb34c1d'),
        'root.whitelist.rules.match.client_ip.group_uuids': ('refers_to', u'IpAddrGroup', '2a89f86bd33d49ab'),
        'root.waf_crs_uuid': ('hyperlink_to', u'WafCRS', '53b3f82ddfd84a91'),
        'root.whitelist.rules.match.path.string_group_uuids': ('refers_to', u'StringGroup', '70683eb8d03e4234'),
        'root.positive_security_model.group_uuids': ('refers_to', u'WafPolicyPSMGroup', '092cc076b4084d70'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', '0adea0d51cca425a'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.pre_crs_groups.rules.tags': 'f_immutable',
        'root.post_crs_groups.rules.tags': 'f_immutable',
        'root.crs_groups.rules.tags': 'f_immutable',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

class WafPolIpAddGro (models.Model):
    wafpolicy = models.ForeignKey(WafPolicy, null=True, blank=True, on_delete=models.PROTECT) 
    ipaddrgroup = models.ForeignKey(IpAddrGroup, null=True, blank=True, on_delete=models.PROTECT) 

class WafPolStrGro (models.Model):
    wafpolicy = models.ForeignKey(WafPolicy, null=True, blank=True, on_delete=models.PROTECT) 
    stringgroup = models.ForeignKey(StringGroup, null=True, blank=True, on_delete=models.PROTECT) 

class WafPolWafPolPSMGro (models.Model):
    wafpolicy = models.ForeignKey(WafPolicy, null=True, blank=True, on_delete=models.PROTECT) 
    wafpolicypsmgroup = models.ForeignKey(WafPolicyPSMGroup, null=True, blank=True, on_delete=models.PROTECT) 

