
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_options import *

LAND = 0
SMURF = 1
ICMP_PING_FLOOD = 2
UNKOWN_PROTOCOL = 3
TEARDROP = 4
IP_FRAG_OVERRUN = 5
IP_FRAG_TOOSMALL = 6
IP_FRAG_FULL = 7
IP_FRAG_INCOMPLETE = 8
PORT_SCAN = 9
TCP_NON_SYN_FLOOD_OLD = 10
SYN_FLOOD = 100
BAD_RST_FLOOD = 101
MALFORMED_FLOOD = 102
FAKE_SESSION = 103
ZERO_WINDOW_STRESS = 104
SMALL_WINDOW_STRESS = 105
DOS_HTTP_TIMEOUT = 106
DOS_HTTP_ERROR = 107
DOS_HTTP_ABORT = 108
DOS_SSL_ERROR = 109
DOS_APP_ERROR = 110
DOS_REQ_IP_RL_DROP = 111
DOS_REQ_URI_RL_DROP = 112
DOS_REQ_URI_SCAN_BAD_RL_DROP = 113
DOS_REQ_URI_SCAN_UNKNOWN_RL_DROP = 114
DOS_REQ_IP_URI_RL_DROP = 115
DOS_CONN_IP_RL_DROP = 116
DOS_SLOW_URL = 117
TCP_NON_SYN_FLOOD = 118
DOS_REQ_CIP_SCAN_BAD_RL_DROP = 119
DOS_REQ_CIP_SCAN_UNKNOWN_RL_DROP = 120
DOS_REQ_IP_RL_DROP_BAD = 121
DOS_REQ_URI_RL_DROP_BAD = 122
DOS_REQ_IP_URI_RL_DROP_BAD = 123
POLICY_DROPS = 124
DOS_CONN_RL_DROP = 125
DOS_REQ_RL_DROP = 126
DOS_REQ_HDR_RL_DROP = 127
DOS_REQ_CUSTOM_RL_DROP = 128
DNS_ATTACK_REFLECTION = 129
AttackTypeChoices = (
    (LAND, 'LAND'),
    (SMURF, 'SMURF'),
    (ICMP_PING_FLOOD, 'ICMP_PING_FLOOD'),
    (UNKOWN_PROTOCOL, 'UNKOWN_PROTOCOL'),
    (TEARDROP, 'TEARDROP'),
    (IP_FRAG_OVERRUN, 'IP_FRAG_OVERRUN'),
    (IP_FRAG_TOOSMALL, 'IP_FRAG_TOOSMALL'),
    (IP_FRAG_FULL, 'IP_FRAG_FULL'),
    (IP_FRAG_INCOMPLETE, 'IP_FRAG_INCOMPLETE'),
    (PORT_SCAN, 'PORT_SCAN'),
    (TCP_NON_SYN_FLOOD_OLD, 'TCP_NON_SYN_FLOOD_OLD'),
    (SYN_FLOOD, 'SYN_FLOOD'),
    (BAD_RST_FLOOD, 'BAD_RST_FLOOD'),
    (MALFORMED_FLOOD, 'MALFORMED_FLOOD'),
    (FAKE_SESSION, 'FAKE_SESSION'),
    (ZERO_WINDOW_STRESS, 'ZERO_WINDOW_STRESS'),
    (SMALL_WINDOW_STRESS, 'SMALL_WINDOW_STRESS'),
    (DOS_HTTP_TIMEOUT, 'DOS_HTTP_TIMEOUT'),
    (DOS_HTTP_ERROR, 'DOS_HTTP_ERROR'),
    (DOS_HTTP_ABORT, 'DOS_HTTP_ABORT'),
    (DOS_SSL_ERROR, 'DOS_SSL_ERROR'),
    (DOS_APP_ERROR, 'DOS_APP_ERROR'),
    (DOS_REQ_IP_RL_DROP, 'DOS_REQ_IP_RL_DROP'),
    (DOS_REQ_URI_RL_DROP, 'DOS_REQ_URI_RL_DROP'),
    (DOS_REQ_URI_SCAN_BAD_RL_DROP, 'DOS_REQ_URI_SCAN_BAD_RL_DROP'),
    (DOS_REQ_URI_SCAN_UNKNOWN_RL_DROP, 'DOS_REQ_URI_SCAN_UNKNOWN_RL_DROP'),
    (DOS_REQ_IP_URI_RL_DROP, 'DOS_REQ_IP_URI_RL_DROP'),
    (DOS_CONN_IP_RL_DROP, 'DOS_CONN_IP_RL_DROP'),
    (DOS_SLOW_URL, 'DOS_SLOW_URL'),
    (TCP_NON_SYN_FLOOD, 'TCP_NON_SYN_FLOOD'),
    (DOS_REQ_CIP_SCAN_BAD_RL_DROP, 'DOS_REQ_CIP_SCAN_BAD_RL_DROP'),
    (DOS_REQ_CIP_SCAN_UNKNOWN_RL_DROP, 'DOS_REQ_CIP_SCAN_UNKNOWN_RL_DROP'),
    (DOS_REQ_IP_RL_DROP_BAD, 'DOS_REQ_IP_RL_DROP_BAD'),
    (DOS_REQ_URI_RL_DROP_BAD, 'DOS_REQ_URI_RL_DROP_BAD'),
    (DOS_REQ_IP_URI_RL_DROP_BAD, 'DOS_REQ_IP_URI_RL_DROP_BAD'),
    (POLICY_DROPS, 'POLICY_DROPS'),
    (DOS_CONN_RL_DROP, 'DOS_CONN_RL_DROP'),
    (DOS_REQ_RL_DROP, 'DOS_REQ_RL_DROP'),
    (DOS_REQ_HDR_RL_DROP, 'DOS_REQ_HDR_RL_DROP'),
    (DOS_REQ_CUSTOM_RL_DROP, 'DOS_REQ_CUSTOM_RL_DROP'),
    (DNS_ATTACK_REFLECTION, 'DNS_ATTACK_REFLECTION'),
)
DOS_IP = 1
DOS_URI = 2
DOS_IP_URI = 3
DOS_HIGH_RESP_TIME = 4
DOS_HDR = 5
DosDimensionChoices = (
    (DOS_IP, 'DOS_IP'),
    (DOS_URI, 'DOS_URI'),
    (DOS_IP_URI, 'DOS_IP_URI'),
    (DOS_HIGH_RESP_TIME, 'DOS_HIGH_RESP_TIME'),
    (DOS_HDR, 'DOS_HDR'),
)
