
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.avijsonfield import AviJsonField
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from avi.rest.json_db_utils import transform_json_refs_to_uuids

from models_auth import *
from models_match import *
from models_action import *
from models_options import *
from models_application_persistence_profile import *

from models_ssl import *
from models_common import *
SSO_TYPE_SAML = 1
SSO_TYPE_PINGACCESS = 2
SSOPolicyTypeChoices = (
    (SSO_TYPE_SAML, 'SSO_TYPE_SAML'),
    (SSO_TYPE_PINGACCESS, 'SSO_TYPE_PINGACCESS'),
)

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

import time
from avi.protobuf.sso_pb2 import SSOPolicy as SSOPolicyProto

from models_auth import AuthProfile
from models_match import IpAddrGroup
from models_match import StringGroup


class SSOPolicy (models.Model, GenBase):
    pb_class = SSOPolicyProto
    json = True
    random_uuid = True

    @staticmethod
    def gen_uuid(id=1):
        return 'ssopolicy-%s' % uuid.uuid4()

    def save(self, update_time=False, *args, **kwargs):
        if not self.slug:
            if not self.uuid:
                self.uuid = self.gen_uuid()
            self.slug = self.uuid
        if (hasattr(self, '_last_modified') and
                (update_time or hasattr(self, '__update_time'))):
            delattr(self, '__update_time')
            self._last_modified = str(int(time.time()*1000000))
            if hasattr(self, 'json_data'):
                self.json_data['_last_modified'] = self._last_modified
        super(SSOPolicy, self).save(*args, **kwargs)

    def save_pb(self, *args, **kwargs):
        save_model_object(self)
        super(SSOPolicy, self).save(*args, **kwargs)

    def delete(self):
        delete_model_object(self)
        super(SSOPolicy, self).delete()

    def serialize(self):
        return self.protobuf().SerializeToString()

    def _protobuf(self):
        pb = SSOPolicyProto()
        if hasattr(self, 'json_data') and self.json_data:
            updated_json = copy.deepcopy(self.json_data)
            transform_json_refs_to_uuids(updated_json, refs=self.references)
            json2pb(pb, updated_json, replace=True)
        if getattr(self, 'uuid', None):
            pb.uuid = self.uuid
        pb.ClearField('name')
        if self.name is not None:
            pb.name = self.name
        pb.ClearField('tenant_uuid')
        if self.tenant_ref is not None:
            pb.tenant_uuid = self.tenant_ref.uuid
        return pb


    def protobuf(self, decrypt=False):
        return get_model_protobuf(self, decrypt=decrypt)


    uuid = models.CharField(max_length=128, editable=False, unique=True)
    slug = AviSlugField(max_length=128, null=False, blank=False)
    pb_data = ByteaField()
    json_data = AviJsonField()
    name = models.TextField(null=False, blank=False)
    tenant_ref = models.ForeignKey(Tenant, null=True, blank=True, related_name="ssopolicy_tenant_ref", on_delete=models.PROTECT)
    auth_profile_ref_adc52fe34dc644b2_ref = models.ForeignKey(AuthProfile, null=True, blank=True, related_name="authenticationpolicy_auth_profile_ref_adc52fe34dc644b2", on_delete=models.PROTECT)
    default_auth_profile_ref_2ec64a2295eb43e2_ref = models.ForeignKey(AuthProfile, null=True, blank=True, related_name="authenticationpolicy_default_auth_profile_ref_2ec64a2295eb43e2", on_delete=models.PROTECT)
    group_refs = models.ManyToManyField(IpAddrGroup, related_name="ssopolicy_ipaddrgroup", through="SSOPolIpAddGro")
    string_group_refs = models.ManyToManyField(StringGroup, related_name="ssopolicy_stringgroup", through="SSOPolStrGro")
    _last_modified = models.CharField(max_length=16, null=True, blank=True)

    references = {
        'root.authentication_policy.auth_profile_uuid': ('refers_to', u'AuthProfile', 'adc52fe34dc644b2'),
        'root.authentication_policy.default_auth_profile_uuid': ('refers_to', u'AuthProfile', '2ec64a2295eb43e2'),
        'root.authentication_policy.authn_rules.match.client_ip.group_uuids': ('refers_to', u'IpAddrGroup', '7457e8129af6405b'),
        'root.authorization_policy.authz_rules.match.attr_matches.attribute_value_list.string_group_uuids': ('refers_to', u'StringGroup', 'fdfddca0653b435a'),
        'root.tenant_uuid': ('belongs_to', u'Tenant', '41c6896779854525'),
        'root.authentication_policy.authn_rules.match.path.string_group_uuids': ('refers_to', u'StringGroup', 'cf24849caee54015'),
        'root.authorization_policy.authz_rules.match.path.string_group_uuids': ('refers_to', u'StringGroup', '0eb46017384c4b4e'),
    }
    sensitive_fields = {
    }
    pb_check_fields = {
        'root.authentication_policy.sp_metadata': 'f_readonly',
    }

    @staticmethod
    def get_extension_fields():
        return []

    class Meta:
        unique_together = ('name','tenant_ref',)

class SSOPolIpAddGro (models.Model):
    ssopolicy = models.ForeignKey(SSOPolicy, null=True, blank=True, on_delete=models.PROTECT) 
    ipaddrgroup = models.ForeignKey(IpAddrGroup, null=True, blank=True, on_delete=models.PROTECT) 

class SSOPolStrGro (models.Model):
    ssopolicy = models.ForeignKey(SSOPolicy, null=True, blank=True, on_delete=models.PROTECT) 
    stringgroup = models.ForeignKey(StringGroup, null=True, blank=True, on_delete=models.PROTECT) 

