
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.serializers import *
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.rest.json_db_utils import transform_json_refs_to_uuids
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from models_apic import *

from models_options import *
from models_vs import *

from models_common import *


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.apic_pb2 import APICLifsRuntime as APICLifsRuntimeProto

import models_apic_legacy


class APICLifsRuntimeSerializer(ScopedModelSerializer):
    pb_class = APICLifsRuntimeProto
    vs_uuid = StringArrayField(required=False)
    se_uuid = StringArrayField(required=False)
    contract_graphs = StringArrayField(required=False)
    json = True

    def to_native(self, obj, use_extension=True, merge_extension=True,
                  remove_sensitive_field=True, remove_internal_field=True):
        return super(APICLifsRuntimeSerializer, self).to_native(obj, use_extension=use_extension,
                                                               merge_extension=merge_extension,
                                                               remove_sensitive_field=remove_sensitive_field,
                                                               remove_internal_field=remove_internal_field)

    def from_native(self, data, files):
        return super(APICLifsRuntimeSerializer, self).from_native(data, files)

    class Meta:
        model = APICLifsRuntime
        #legacy_serializer = models_apic_legacy.APICLifsRuntimeLegacySerializer
        fields = ('url', 'uuid', 'json_data', 'name', 'vs_uuid', 'se_uuid', 'contract_graphs', 'tenant_ref', '_last_modified', )
        related_fields = ()