
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.serializers import *
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.rest.json_db_utils import transform_json_refs_to_uuids
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from models_se_group import *

from models_common import *
from models_options import *
from models_vi_mgr_common import *
from models_dos import *
from models_analytics_policy import *
from models_license_tier_type import *
from models_se_bandwidth_type import *
from models_vip_autoscale import *

from models_hsm import *
from models_cloud_objects import *


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.se_group_pb2 import ServiceEngineGroup as ServiceEngineGroupProto

import models_se_group_legacy


class ServiceEngineGroupSerializer(ScopedModelSerializer):
    pb_class = ServiceEngineGroupProto
    json = True

    def to_native(self, obj, use_extension=True, merge_extension=True,
                  remove_sensitive_field=True, remove_internal_field=True):
        return super(ServiceEngineGroupSerializer, self).to_native(obj, use_extension=use_extension,
                                                               merge_extension=merge_extension,
                                                               remove_sensitive_field=remove_sensitive_field,
                                                               remove_internal_field=remove_internal_field)

    def from_native(self, data, files):
        return super(ServiceEngineGroupSerializer, self).from_native(data, files)

    class Meta:
        model = ServiceEngineGroup
        #legacy_serializer = models_se_group_legacy.ServiceEngineGroupLegacySerializer
        fields = ('url', 'uuid', 'json_data', 'name', 'tenant_ref', 'cloud_ref', '_last_modified', 'hardwaresecuritymodulegroup_ref_ba4addefba6c42b1_ref', )
        related_fields = ('hardwaresecuritymodulegroup_ref_ba4addefba6c42b1_ref', )