
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
import sys, os, uuid, copy
from django.db import models
from rest_framework import serializers
from rest_framework import relations
from avi.rest.models import GenBase, AviSlugField
from avi.rest.serializers import *
from avi.protobuf_json.protobuf_json import json2pb
from permission.models_initial_configuration import UpgradeInstance
from api.db_utils import (
    save_model_object, delete_model_object, get_model_object,
    get_model_protobuf, get_model_protobuf_extension, integer_validator,
    big_integer_validator, positive_integer_validator, parse_blob_into_pb
)
from avi.rest.json_db_utils import transform_json_refs_to_uuids
from avi.djorm_pgbytea.bytea import ByteaField
from django_pgjson.fields import JsonField
from models_gslb import *

from models_options import *
from models_common import *
from models_health_monitor import *
from models_application_persistence_profile import *



############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbSite as GslbSiteProto

import models_gslb_legacy


class GslbSiteSerializer(ScopedModelSerializer):
    pb_class = GslbSiteProto
    json = True

    def to_native(self, obj, use_extension=True, merge_extension=True,
                  remove_sensitive_field=True, remove_internal_field=True):
        return super(GslbSiteSerializer, self).to_native(obj, use_extension=use_extension,
                                                               merge_extension=merge_extension,
                                                               remove_sensitive_field=remove_sensitive_field,
                                                               remove_internal_field=remove_internal_field)

    def from_native(self, data, files):
        return super(GslbSiteSerializer, self).from_native(data, files)

    class Meta:
        model = GslbSite
        #legacy_serializer = models_gslb_legacy.GslbSiteLegacySerializer
        fields = ('url', 'uuid', 'json_data', 'name', '_last_modified', )
        related_fields = ()

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbThirdPartySite as GslbThirdPartySiteProto

import models_gslb_legacy


class GslbThirdPartySiteSerializer(ScopedModelSerializer):
    pb_class = GslbThirdPartySiteProto
    json = True

    def to_native(self, obj, use_extension=True, merge_extension=True,
                  remove_sensitive_field=True, remove_internal_field=True):
        return super(GslbThirdPartySiteSerializer, self).to_native(obj, use_extension=use_extension,
                                                               merge_extension=merge_extension,
                                                               remove_sensitive_field=remove_sensitive_field,
                                                               remove_internal_field=remove_internal_field)

    def from_native(self, data, files):
        return super(GslbThirdPartySiteSerializer, self).from_native(data, files)

    class Meta:
        model = GslbThirdPartySite
        #legacy_serializer = models_gslb_legacy.GslbThirdPartySiteLegacySerializer
        fields = ('url', 'uuid', 'json_data', 'name', '_last_modified', )
        related_fields = ()

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import Gslb as GslbProto

import models_gslb_legacy


class GslbSerializer(ScopedModelSerializer):
    pb_class = GslbProto
    json = True

    def to_native(self, obj, use_extension=True, merge_extension=True,
                  remove_sensitive_field=True, remove_internal_field=True):
        return super(GslbSerializer, self).to_native(obj, use_extension=use_extension,
                                                               merge_extension=merge_extension,
                                                               remove_sensitive_field=remove_sensitive_field,
                                                               remove_internal_field=remove_internal_field)

    def from_native(self, data, files):
        return super(GslbSerializer, self).from_native(data, files)

    class Meta:
        model = Gslb
        #legacy_serializer = models_gslb_legacy.GslbLegacySerializer
        fields = ('url', 'uuid', 'json_data', 'name', 'is_federated', 'tenant_ref', '_last_modified', )
        related_fields = ()

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbService as GslbServiceProto

import models_gslb_legacy


class GslbServiceSerializer(ScopedModelSerializer):
    pb_class = GslbServiceProto
    json = True

    def to_native(self, obj, use_extension=True, merge_extension=True,
                  remove_sensitive_field=True, remove_internal_field=True):
        return super(GslbServiceSerializer, self).to_native(obj, use_extension=use_extension,
                                                               merge_extension=merge_extension,
                                                               remove_sensitive_field=remove_sensitive_field,
                                                               remove_internal_field=remove_internal_field)

    def from_native(self, data, files):
        return super(GslbServiceSerializer, self).from_native(data, files)

    class Meta:
        model = GslbService
        #legacy_serializer = models_gslb_legacy.GslbServiceLegacySerializer
        fields = ('url', 'uuid', 'json_data', 'name', 'is_federated', 'tenant_ref', '_last_modified', 'application_persistence_profile_ref_83daf57254af4302_ref', )
        related_fields = ('application_persistence_profile_ref_83daf57254af4302_ref', )

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbGeoDbProfile as GslbGeoDbProfileProto

import models_gslb_legacy


class GslbGeoDbProfileSerializer(ScopedModelSerializer):
    pb_class = GslbGeoDbProfileProto
    json = True

    def to_native(self, obj, use_extension=True, merge_extension=True,
                  remove_sensitive_field=True, remove_internal_field=True):
        return super(GslbGeoDbProfileSerializer, self).to_native(obj, use_extension=use_extension,
                                                               merge_extension=merge_extension,
                                                               remove_sensitive_field=remove_sensitive_field,
                                                               remove_internal_field=remove_internal_field)

    def from_native(self, data, files):
        return super(GslbGeoDbProfileSerializer, self).from_native(data, files)

    class Meta:
        model = GslbGeoDbProfile
        #legacy_serializer = models_gslb_legacy.GslbGeoDbProfileLegacySerializer
        fields = ('url', 'uuid', 'json_data', 'name', 'is_federated', 'tenant_ref', '_last_modified', )
        related_fields = ()

############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from avi.protobuf.gslb_pb2 import GslbDnsUpdate as GslbDnsUpdateProto

import models_gslb_legacy


class GslbDnsUpdateSerializer(ScopedModelSerializer):
    pb_class = GslbDnsUpdateProto
    json = True

    def to_native(self, obj, use_extension=True, merge_extension=True,
                  remove_sensitive_field=True, remove_internal_field=True):
        return super(GslbDnsUpdateSerializer, self).to_native(obj, use_extension=use_extension,
                                                               merge_extension=merge_extension,
                                                               remove_sensitive_field=remove_sensitive_field,
                                                               remove_internal_field=remove_internal_field)

    def from_native(self, data, files):
        return super(GslbDnsUpdateSerializer, self).from_native(data, files)

    class Meta:
        model = GslbDnsUpdate
        #legacy_serializer = models_gslb_legacy.GslbDnsUpdateLegacySerializer
        fields = ('url', 'uuid', 'json_data', '_last_modified', )
        related_fields = ()