
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

#GENERATED FILE 
#pylint:  skip-file
from django.conf.urls import patterns, include, url
import api.views_se

urlpatterns = patterns('',
    
    url(r'^serviceengine/?$',
        api.views_se.ServiceEngineList.as_view(),
        name='serviceengine-list',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),

    
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/?$',
        api.views_se.ServiceEngineList.as_view(),
        name='serviceengine-list-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),  
                
    url(r'^serviceengine/(?P<slug>[-\w.]+)/?$',
        api.views_se.ServiceEngineDetail.as_view(),
        name='serviceengine-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<slug>[-\w.]+)/?$',
        api.views_se.ServiceEngineDetail.as_view(),
        name='serviceengine-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    
    url(r'^serviceengine/(?P<key>[-\w.]+)/reboot/?$',
        api.views_se.ServiceEngineRebootView.as_view(),
        name='serviceenginerebootview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/reboot/?$',
        api.views_se.ServiceEngineRebootView.as_view(),
        name='serviceenginerebootview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE" }),
    
    url(r'^serviceengine/(?P<key>[-\w.]+)/forcedelete/?$',
        api.views_se.ServiceEngineForcedeleteView.as_view(),
        name='serviceengineforcedeleteview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/forcedelete/?$',
        api.views_se.ServiceEngineForcedeleteView.as_view(),
        name='serviceengineforcedeleteview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE" }),
    
    url(r'^serviceengine/(?P<key>[-\w.]+)/switchover/?$',
        api.views_se.ServiceEngineSwitchoverView.as_view(),
        name='serviceengineswitchoverview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/switchover/?$',
        api.views_se.ServiceEngineSwitchoverView.as_view(),
        name='serviceengineswitchoverview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE" }),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/lldp/?$',
        api.views_se.LldpRuntimeView.as_view(),
        name='lldpruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/lldp/?$',
        api.views_se.LldpRuntimeView.as_view(),
        name='lldpruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/runtime/?$',
        api.views_se.ServiceEngineRuntimeSummaryView.as_view(),
        name='serviceengineruntimesummary-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/runtime/?$',
        api.views_se.ServiceEngineRuntimeSummaryView.as_view(),
        name='serviceengineruntimesummary-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/tcp-flows/detail/?$',
        api.views_se.TcpConnRuntimeDetailView.as_view(),
        name='tcpconnruntimedetail-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/tcp-flows/detail/?$',
        api.views_se.TcpConnRuntimeDetailView.as_view(),
        name='tcpconnruntimedetail-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/interfacesummary/?$',
        api.views_se.InterfaceSummaryRuntimeView.as_view(),
        name='interfacesummaryruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/interfacesummary/?$',
        api.views_se.InterfaceSummaryRuntimeView.as_view(),
        name='interfacesummaryruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/interface/?$',
        api.views_se.InterfaceRuntimeView.as_view(),
        name='interfaceruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/interface/?$',
        api.views_se.InterfaceRuntimeView.as_view(),
        name='interfaceruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/interface/clear/?$',
        api.views_se.InterfaceRuntimeClearView.as_view(),
        name='interfaceruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/interface/clear/?$',
        api.views_se.InterfaceRuntimeClearView.as_view(),
        name='interfaceruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/arptable/?$',
        api.views_se.ArptableRuntimeView.as_view(),
        name='arptableruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/arptable/?$',
        api.views_se.ArptableRuntimeView.as_view(),
        name='arptableruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/arptable/clear/?$',
        api.views_se.ArptableRuntimeClearView.as_view(),
        name='arptableruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/arptable/clear/?$',
        api.views_se.ArptableRuntimeClearView.as_view(),
        name='arptableruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/runtime/detail/?$',
        api.views_se.ServiceEngineRuntimeDetailView.as_view(),
        name='serviceengineruntimedetail-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/runtime/detail/?$',
        api.views_se.ServiceEngineRuntimeDetailView.as_view(),
        name='serviceengineruntimedetail-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/icmp6stat/?$',
        api.views_se.Icmp6StatRuntimeView.as_view(),
        name='icmp6statruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/icmp6stat/?$',
        api.views_se.Icmp6StatRuntimeView.as_view(),
        name='icmp6statruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/icmp6stat/clear/?$',
        api.views_se.Icmp6StatRuntimeClearView.as_view(),
        name='icmp6statruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/icmp6stat/clear/?$',
        api.views_se.Icmp6StatRuntimeClearView.as_view(),
        name='icmp6statruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/graphdb/?$',
        api.views_se.SeAgentGraphDBRuntimeView.as_view(),
        name='seagentgraphdbruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/graphdb/?$',
        api.views_se.SeAgentGraphDBRuntimeView.as_view(),
        name='seagentgraphdbruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/l4policysetstats/?$',
        api.views_se.L4PolicySetStatsView.as_view(),
        name='l4policysetstats-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/l4policysetstats/?$',
        api.views_se.L4PolicySetStatsView.as_view(),
        name='l4policysetstats-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/l4policysetstats/clear/?$',
        api.views_se.L4PolicySetStatsClearView.as_view(),
        name='l4policysetstatsclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/l4policysetstats/clear/?$',
        api.views_se.L4PolicySetStatsClearView.as_view(),
        name='l4policysetstatsclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/seruminsertionstats/?$',
        api.views_se.SeRumInsertionStatsView.as_view(),
        name='seruminsertionstats-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seruminsertionstats/?$',
        api.views_se.SeRumInsertionStatsView.as_view(),
        name='seruminsertionstats-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/seruminsertionstats/clear/?$',
        api.views_se.SeRumInsertionStatsClearView.as_view(),
        name='seruminsertionstatsclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seruminsertionstats/clear/?$',
        api.views_se.SeRumInsertionStatsClearView.as_view(),
        name='seruminsertionstatsclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/interface/lacp/?$',
        api.views_se.InterfaceLacpRuntimeView.as_view(),
        name='interfacelacpruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/interface/lacp/?$',
        api.views_se.InterfaceLacpRuntimeView.as_view(),
        name='interfacelacpruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/meminfo/?$',
        api.views_se.MeminfoRuntimeView.as_view(),
        name='meminforuntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/meminfo/?$',
        api.views_se.MeminfoRuntimeView.as_view(),
        name='meminforuntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/selogstats/?$',
        api.views_se.SeLogStatsRuntimeView.as_view(),
        name='selogstatsruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/selogstats/?$',
        api.views_se.SeLogStatsRuntimeView.as_view(),
        name='selogstatsruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/selogstats/clear/?$',
        api.views_se.SeLogStatsRuntimeClearView.as_view(),
        name='selogstatsruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/selogstats/clear/?$',
        api.views_se.SeLogStatsRuntimeClearView.as_view(),
        name='selogstatsruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/faultinject/exhaust_conn/clear/?$',
        api.views_se.SeFaultInjectExhaustConnClearView.as_view(),
        name='sefaultinjectexhaustconnclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/faultinject/exhaust_conn/clear/?$',
        api.views_se.SeFaultInjectExhaustConnClearView.as_view(),
        name='sefaultinjectexhaustconnclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/consistenthash/?$',
        api.views_se.SeAgentConsistentHashView.as_view(),
        name='seagentconsistenthash-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/consistenthash/?$',
        api.views_se.SeAgentConsistentHashView.as_view(),
        name='seagentconsistenthash-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/tcp-flows/?$',
        api.views_se.TcpConnRuntimeView.as_view(),
        name='tcpconnruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/tcp-flows/?$',
        api.views_se.TcpConnRuntimeView.as_view(),
        name='tcpconnruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/resourcemap/?$',
        api.views_se.SeAgentShardClientResourceMapView.as_view(),
        name='seagentshardclientresourcemap-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/resourcemap/?$',
        api.views_se.SeAgentShardClientResourceMapView.as_view(),
        name='seagentshardclientresourcemap-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/ipstat/?$',
        api.views_se.IpStatRuntimeView.as_view(),
        name='ipstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/ipstat/?$',
        api.views_se.IpStatRuntimeView.as_view(),
        name='ipstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/ipstat/clear/?$',
        api.views_se.IpStatRuntimeClearView.as_view(),
        name='ipstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/ipstat/clear/?$',
        api.views_se.IpStatRuntimeClearView.as_view(),
        name='ipstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/shmallocstats/?$',
        api.views_se.ShMallocStatRuntimeView.as_view(),
        name='shmallocstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/shmallocstats/?$',
        api.views_se.ShMallocStatRuntimeView.as_view(),
        name='shmallocstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/seauthstats/?$',
        api.views_se.SeAuthStatsRuntimeView.as_view(),
        name='seauthstatsruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seauthstats/?$',
        api.views_se.SeAuthStatsRuntimeView.as_view(),
        name='seauthstatsruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/seauthstats/clear/?$',
        api.views_se.SeAuthStatsRuntimeClearView.as_view(),
        name='seauthstatsruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seauthstats/clear/?$',
        api.views_se.SeAuthStatsRuntimeClearView.as_view(),
        name='seauthstatsruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/arpstat/?$',
        api.views_se.ArpStatRuntimeView.as_view(),
        name='arpstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/arpstat/?$',
        api.views_se.ArpStatRuntimeView.as_view(),
        name='arpstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/arpstat/clear/?$',
        api.views_se.ArpStatRuntimeClearView.as_view(),
        name='arpstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/arpstat/clear/?$',
        api.views_se.ArpStatRuntimeClearView.as_view(),
        name='arpstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/cpu/detail/?$',
        api.views_se.CpuStatRuntimeDetailView.as_view(),
        name='cpustatruntimedetail-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/cpu/detail/?$',
        api.views_se.CpuStatRuntimeDetailView.as_view(),
        name='cpustatruntimedetail-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/appmap/?$',
        api.views_se.SeAgentShardClientAppMapView.as_view(),
        name='seagentshardclientappmap-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/appmap/?$',
        api.views_se.SeAgentShardClientAppMapView.as_view(),
        name='seagentshardclientappmap-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/microservice/?$',
        api.views_se.SeMicroServiceView.as_view(),
        name='semicroservice-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/microservice/?$',
        api.views_se.SeMicroServiceView.as_view(),
        name='semicroservice-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/metrics/detail/?$',
        api.views_se.MetricsRuntimeDetailView.as_view(),
        name='metricsruntimedetail-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/metrics/detail/?$',
        api.views_se.MetricsRuntimeDetailView.as_view(),
        name='metricsruntimedetail-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/vnicdb/?$',
        api.views_se.SeAgentVnicDBRuntimeView.as_view(),
        name='seagentvnicdbruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/vnicdb/?$',
        api.views_se.SeAgentVnicDBRuntimeView.as_view(),
        name='seagentvnicdbruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/ndtable/?$',
        api.views_se.NdtableRuntimeView.as_view(),
        name='ndtableruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/ndtable/?$',
        api.views_se.NdtableRuntimeView.as_view(),
        name='ndtableruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/ndtable/clear/?$',
        api.views_se.NdtableRuntimeClearView.as_view(),
        name='ndtableruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/ndtable/clear/?$',
        api.views_se.NdtableRuntimeClearView.as_view(),
        name='ndtableruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/reservedvs/?$',
        api.views_se.SeReservedVsView.as_view(),
        name='sereservedvs-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/reservedvs/?$',
        api.views_se.SeReservedVsView.as_view(),
        name='sereservedvs-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/reservedvs/clear/?$',
        api.views_se.SeReservedVsClearView.as_view(),
        name='sereservedvsclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/reservedvs/clear/?$',
        api.views_se.SeReservedVsClearView.as_view(),
        name='sereservedvsclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/sevssplacement/?$',
        api.views_se.SeVssPlacementView.as_view(),
        name='sevssplacement-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/sevssplacement/?$',
        api.views_se.SeVssPlacementView.as_view(),
        name='sevssplacement-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                    
    url(r'^serviceengine/(?P<key>[-\w.]+)/faultinject/sefault/clear/?$',
        api.views_se.SeFaultInjectInfraClearView.as_view(),
        name='sefaultinjectinfraclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/faultinject/sefault/clear/?$',
        api.views_se.SeFaultInjectInfraClearView.as_view(),
        name='sefaultinjectinfraclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/cpu/?$',
        api.views_se.CpuStatRuntimeView.as_view(),
        name='cpustatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/cpu/?$',
        api.views_se.CpuStatRuntimeView.as_view(),
        name='cpustatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/nat-flows/?$',
        api.views_se.SeNatFlowRuntimeView.as_view(),
        name='senatflowruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/nat-flows/?$',
        api.views_se.SeNatFlowRuntimeView.as_view(),
        name='senatflowruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/nat-flows/clear/?$',
        api.views_se.SeNatFlowRuntimeClearView.as_view(),
        name='senatflowruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/nat-flows/clear/?$',
        api.views_se.SeNatFlowRuntimeClearView.as_view(),
        name='senatflowruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/seagent/?$',
        api.views_se.SeAgentStateRuntimeView.as_view(),
        name='seagentstateruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seagent/?$',
        api.views_se.SeAgentStateRuntimeView.as_view(),
        name='seagentstateruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/vshash/?$',
        api.views_se.VshashshowRuntimeView.as_view(),
        name='vshashshowruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/vshash/?$',
        api.views_se.VshashshowRuntimeView.as_view(),
        name='vshashshowruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/connected/?$',
        api.views_se.ServiceEngineInternalView.as_view(),
        name='serviceengineinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/connected/?$',
        api.views_se.ServiceEngineInternalView.as_view(),
        name='serviceengineinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/flowtable_remote/?$',
        api.views_se.DispatcherRemoteTimerListDumpRuntimeView.as_view(),
        name='dispatcherremotetimerlistdumpruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/flowtable_remote/?$',
        api.views_se.DispatcherRemoteTimerListDumpRuntimeView.as_view(),
        name='dispatcherremotetimerlistdumpruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/natstat/?$',
        api.views_se.SeNatStatRuntimeView.as_view(),
        name='senatstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/natstat/?$',
        api.views_se.SeNatStatRuntimeView.as_view(),
        name='senatstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/natstat/clear/?$',
        api.views_se.SeNatStatRuntimeClearView.as_view(),
        name='senatstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/natstat/clear/?$',
        api.views_se.SeNatStatRuntimeClearView.as_view(),
        name='senatstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/sevshbstats/?$',
        api.views_se.SeVsHbStatRuntimeView.as_view(),
        name='sevshbstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/sevshbstats/?$',
        api.views_se.SeVsHbStatRuntimeView.as_view(),
        name='sevshbstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/sevshbstats/clear/?$',
        api.views_se.SeVsHbStatRuntimeClearView.as_view(),
        name='sevshbstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/sevshbstats/clear/?$',
        api.views_se.SeVsHbStatRuntimeClearView.as_view(),
        name='sevshbstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/mallocstats/?$',
        api.views_se.MallocStatRuntimeView.as_view(),
        name='mallocstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/mallocstats/?$',
        api.views_se.MallocStatRuntimeView.as_view(),
        name='mallocstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/bgp/?$',
        api.views_se.BgpRuntimeView.as_view(),
        name='bgpruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/bgp/?$',
        api.views_se.BgpRuntimeView.as_view(),
        name='bgpruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                    
    url(r'^serviceengine/(?P<key>[-\w.]+)/faultinject/exhaust_mcl/clear/?$',
        api.views_se.SeFaultInjectExhaustMclClearView.as_view(),
        name='sefaultinjectexhaustmclclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/faultinject/exhaust_mcl/clear/?$',
        api.views_se.SeFaultInjectExhaustMclClearView.as_view(),
        name='sefaultinjectexhaustmclclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/httpstats/?$',
        api.views_se.L7GlobalStatsRuntimeView.as_view(),
        name='l7globalstatsruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/httpstats/?$',
        api.views_se.L7GlobalStatsRuntimeView.as_view(),
        name='l7globalstatsruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/httpstats/clear/?$',
        api.views_se.L7GlobalStatsRuntimeClearView.as_view(),
        name='l7globalstatsruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/httpstats/clear/?$',
        api.views_se.L7GlobalStatsRuntimeClearView.as_view(),
        name='l7globalstatsruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/faultinject/exhaust_mcl_small/clear/?$',
        api.views_se.SeFaultInjectExhaustMclSmallClearView.as_view(),
        name='sefaultinjectexhaustmclsmallclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/faultinject/exhaust_mcl_small/clear/?$',
        api.views_se.SeFaultInjectExhaustMclSmallClearView.as_view(),
        name='sefaultinjectexhaustmclsmallclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/flowtable/?$',
        api.views_se.DispatcherTableDumpRuntimeView.as_view(),
        name='dispatchertabledumpruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/flowtable/?$',
        api.views_se.DispatcherTableDumpRuntimeView.as_view(),
        name='dispatchertabledumpruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/flowtable/clear/?$',
        api.views_se.DispatcherTableDumpRuntimeClearView.as_view(),
        name='dispatchertabledumpruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/flowtable/clear/?$',
        api.views_se.DispatcherTableDumpRuntimeClearView.as_view(),
        name='dispatchertabledumpruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/seassertstats/dp/?$',
        api.views_se.SeAssertStatRuntimeView.as_view(),
        name='seassertstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seassertstats/dp/?$',
        api.views_se.SeAssertStatRuntimeView.as_view(),
        name='seassertstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/seassertstats/dp/clear/?$',
        api.views_se.SeAssertStatRuntimeClearView.as_view(),
        name='seassertstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seassertstats/dp/clear/?$',
        api.views_se.SeAssertStatRuntimeClearView.as_view(),
        name='seassertstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/metrics/?$',
        api.views_se.MetricsRuntimeSummaryView.as_view(),
        name='metricsruntimesummary-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/metrics/?$',
        api.views_se.MetricsRuntimeSummaryView.as_view(),
        name='metricsruntimesummary-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/vnicdbhistory/?$',
        api.views_se.SeAgentVnicDBHistoryView.as_view(),
        name='seagentvnicdbhistory-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/vnicdbhistory/?$',
        api.views_se.SeAgentVnicDBHistoryView.as_view(),
        name='seagentvnicdbhistory-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/mbufstats/?$',
        api.views_se.MbStatRuntimeView.as_view(),
        name='mbstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/mbufstats/?$',
        api.views_se.MbStatRuntimeView.as_view(),
        name='mbstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/mbufstats/clear/?$',
        api.views_se.MbStatRuntimeClearView.as_view(),
        name='mbstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/mbufstats/clear/?$',
        api.views_se.MbStatRuntimeClearView.as_view(),
        name='mbstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/memdist/?$',
        api.views_se.SeMemDistRuntimeView.as_view(),
        name='sememdistruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/memdist/?$',
        api.views_se.SeMemDistRuntimeView.as_view(),
        name='sememdistruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/flowtablestat/?$',
        api.views_se.DispatcherStatRuntimeView.as_view(),
        name='dispatcherstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/flowtablestat/?$',
        api.views_se.DispatcherStatRuntimeView.as_view(),
        name='dispatcherstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/flowtablestat/clear/?$',
        api.views_se.DispatcherStatRuntimeClearView.as_view(),
        name='dispatcherstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/flowtablestat/clear/?$',
        api.views_se.DispatcherStatRuntimeClearView.as_view(),
        name='dispatcherstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/sehmprobedisable/?$',
        api.views_se.DispatcherSehmprobetempdisableRuntimeView.as_view(),
        name='dispatchersehmprobetempdisableruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/sehmprobedisable/?$',
        api.views_se.DispatcherSehmprobetempdisableRuntimeView.as_view(),
        name='dispatchersehmprobetempdisableruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/sehmprobedisable/clear/?$',
        api.views_se.DispatcherSehmprobetempdisableRuntimeClearView.as_view(),
        name='dispatchersehmprobetempdisableruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/sehmprobedisable/clear/?$',
        api.views_se.DispatcherSehmprobetempdisableRuntimeClearView.as_view(),
        name='dispatchersehmprobetempdisableruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/rteringstat/?$',
        api.views_se.RteringStatRuntimeView.as_view(),
        name='rteringstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/rteringstat/?$',
        api.views_se.RteringStatRuntimeView.as_view(),
        name='rteringstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/dosstat/?$',
        api.views_se.SeDosStatRuntimeView.as_view(),
        name='sedosstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/dosstat/?$',
        api.views_se.SeDosStatRuntimeView.as_view(),
        name='sedosstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/dosstat/clear/?$',
        api.views_se.SeDosStatRuntimeClearView.as_view(),
        name='sedosstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/dosstat/clear/?$',
        api.views_se.SeDosStatRuntimeClearView.as_view(),
        name='sedosstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/route/?$',
        api.views_se.RouteTableRuntimeView.as_view(),
        name='routetableruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/route/?$',
        api.views_se.RouteTableRuntimeView.as_view(),
        name='routetableruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/seassertstats/ag/?$',
        api.views_se.SeAgentAssertStatRuntimeView.as_view(),
        name='seagentassertstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seassertstats/ag/?$',
        api.views_se.SeAgentAssertStatRuntimeView.as_view(),
        name='seagentassertstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/seassertstats/ag/clear/?$',
        api.views_se.SeAgentAssertStatRuntimeClearView.as_view(),
        name='seagentassertstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/seassertstats/ag/clear/?$',
        api.views_se.SeAgentAssertStatRuntimeClearView.as_view(),
        name='seagentassertstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/faultinject/exhaust_mbuf/clear/?$',
        api.views_se.SeFaultInjectExhaustMClearView.as_view(),
        name='sefaultinjectexhaustmclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/faultinject/exhaust_mbuf/clear/?$',
        api.views_se.SeFaultInjectExhaustMClearView.as_view(),
        name='sefaultinjectexhaustmclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/shardclientevents/?$',
        api.views_se.SeAgentShardClientEventHistoryView.as_view(),
        name='seagentshardclienteventhistory-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/shardclientevents/?$',
        api.views_se.SeAgentShardClientEventHistoryView.as_view(),
        name='seagentshardclienteventhistory-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/icmpstat/?$',
        api.views_se.IcmpStatRuntimeView.as_view(),
        name='icmpstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/icmpstat/?$',
        api.views_se.IcmpStatRuntimeView.as_view(),
        name='icmpstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/icmpstat/clear/?$',
        api.views_se.IcmpStatRuntimeClearView.as_view(),
        name='icmpstatruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/icmpstat/clear/?$',
        api.views_se.IcmpStatRuntimeClearView.as_view(),
        name='icmpstatruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
            
    url(r'^serviceengine/(?P<key>[-\w.]+)/placement/?$',
        api.views_se.SeResourceProtoView.as_view(),
        name='seresourceproto-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/placement/?$',
        api.views_se.SeResourceProtoView.as_view(),
        name='seresourceproto-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/bgp/debug/?$',
        api.views_se.BgpDebugInfoView.as_view(),
        name='bgpdebuginfo-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/bgp/debug/?$',
        api.views_se.BgpDebugInfoView.as_view(),
        name='bgpdebuginfo-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/ip6route/?$',
        api.views_se.Ip6RouteTableRuntimeView.as_view(),
        name='ip6routetableruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/ip6route/?$',
        api.views_se.Ip6RouteTableRuntimeView.as_view(),
        name='ip6routetableruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
                
    url(r'^serviceengine/(?P<key>[-\w.]+)/ip6stat/?$',
        api.views_se.Ip6StatRuntimeView.as_view(),
        name='ip6statruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/ip6stat/?$',
        api.views_se.Ip6StatRuntimeView.as_view(),
        name='ip6statruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        
    url(r'^serviceengine/(?P<key>[-\w.]+)/ip6stat/clear/?$',
        api.views_se.Ip6StatRuntimeClearView.as_view(),
        name='ip6statruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine/(?P<key>[-\w.]+)/ip6stat/clear/?$',
        api.views_se.Ip6StatRuntimeClearView.as_view(),
        name='ip6statruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
        

)
