
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

#Custom urls
from django.conf.urls import patterns, url
import api.views_inventory
import api.views_inventory_map

urlpatterns = patterns(
    '',
    url(r'^virtualservice-inventory/?$',
        api.views_inventory.VirtualServiceListInventoryView.as_view(),
        name='virtualservice-list-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice-inventory/?$',
        api.views_inventory.VirtualServiceListInventoryView.as_view(),
        name='virtualservice-list-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^virtualservice-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.VirtualServiceDetailInventoryView.as_view(),
        name='virtualservice-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.VirtualServiceDetailInventoryView.as_view(),
        name='virtualservice-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^virtualservice-inventory-summary/?$',
        api.views_inventory.VirtualServiceSummaryInventoryView.as_view(),
        name='virtualservice-summary-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice-inventory-summary/?$',
        api.views_inventory.VirtualServiceSummaryInventoryView.as_view(),
        name='virtualservice-summary-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),

    url(r'^pool-inventory/?$',
        api.views_inventory.PoolListInventoryView.as_view(),
        name='pool-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_POOL"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/pool-inventory/?$',
        api.views_inventory.PoolListInventoryView.as_view(),
        name='pool-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_POOL"}),
    url(r'^pool-inventory/server/?$',
        api.views_inventory.PoolListInventoryServerView.as_view(),
        name='pool-inventory-server',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_POOL"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/pool-inventory/server/?$',
        api.views_inventory.PoolListInventoryServerView.as_view(),
        name='pool-inventory-server-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_POOL"}),
    url(r'^pool-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.PoolDetailInventoryView.as_view(),
        name='pool-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_POOL"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/pool-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.PoolDetailInventoryView.as_view(),
        name='pool-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_POOL"}),
    url(r'^pool-inventory-summary/?$',
        api.views_inventory.PoolSummaryInventoryView.as_view(),
        name='pool-summary-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_POOL"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/pool-inventory-summary/?$',
        api.views_inventory.PoolSummaryInventoryView.as_view(),
        name='pool-summary-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_POOL"}),
    url(r'^pool-inventory/(?P<slug>[-\w.]+)/server/?$',
        api.views_inventory.PoolInventoryServerView.as_view(),
        name='pool-detail-inventory-server',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_POOL"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/pool-inventory/(?P<slug>[-\w.]+)/server/?$',
        api.views_inventory.PoolInventoryServerView.as_view(),
        name='pool-detail-inventory-server-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_POOL"}),

    url(r'^serviceengine-inventory/?$',
        api.views_inventory.ServiceEngineListInventoryView.as_view(),
        name='serviceengine-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine-inventory/?$',
        api.views_inventory.ServiceEngineListInventoryView.as_view(),
        name='serviceengine-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^serviceengine-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.ServiceEngineDetailInventoryView.as_view(),
        name='serviceengine-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.ServiceEngineDetailInventoryView.as_view(),
        name='serviceengine-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^serviceengine-inventory-summary/?$',
        api.views_inventory.ServiceEngineSummaryInventoryView.as_view(),
        name='serviceengine-summary-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/serviceengine-inventory-summary/?$',
        api.views_inventory.ServiceEngineSummaryInventoryView.as_view(),
        name='serviceengine-summary-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINE"}),

    url(r'^network-inventory/?$',
        api.views_inventory.NetworkListInventoryView.as_view(),
        name='network-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_NETWORK"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/network-inventory/?$',
        api.views_inventory.NetworkListInventoryView.as_view(),
        name='network-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_NETWORK"}),
    url(r'^network-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.NetworkDetailInventoryView.as_view(),
        name='network-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_NETWORK"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/network-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.NetworkDetailInventoryView.as_view(),
        name='network-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_NETWORK"}),

    url(r'^serviceenginegroup-inventory/?$',
        api.views_inventory.ServiceEngineGroupListInventoryView.as_view(),
        name='serviceenginegroup-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINEGROUP"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/network-inventory/?$',
        api.views_inventory.ServiceEngineGroupListInventoryView.as_view(),
        name='serviceenginegroup-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINEGROUP"}),
    url(r'^serviceenginegroup-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.ServiceEngineGroupDetailInventoryView.as_view(),
        name='serviceenginegroup-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_SERVICEENGINEGROUP"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/segroup-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.ServiceEngineGroupDetailInventoryView.as_view(),
        name='serviceenginegroup-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_SERVICEENGINEGROUP"}),

    url(r'^cloud-inventory/?$',
        api.views_inventory.CloudListInventoryView.as_view(),
        name='cloud-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_CLOUD"}),

    url(r'^inventory-map/?$',
        api.views_inventory_map.InventoryMapView.as_view(),
        name='inventory-map',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/inventory-map/?$',
        api.views_inventory_map.InventoryMapView.as_view(),
        name='inventory-map-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),

    url(r'^gslb-inventory/?$',
        api.views_inventory.GslbListInventoryView.as_view(),
        name='gslb-list-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_GSLB"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/gslb-inventory/?$',
        api.views_inventory.GslbListInventoryView.as_view(),
        name='gslb-list-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_GSLB"}),
    url(r'^gslb-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.GslbDetailInventoryView.as_view(),
        name='gslb-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_GSLB"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/gslb-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.GslbDetailInventoryView.as_view(),
        name='gslb-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_GSLB"}),

    url(r'^gslbservice-inventory/?$',
        api.views_inventory.GslbServiceListInventoryView.as_view(),
        name='gslbservice-list-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_GSLBSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/gslbservice-inventory/?$',
        api.views_inventory.GslbServiceListInventoryView.as_view(),
        name='gslbservice-list-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_GSLBSERVICE"}),
    url(r'^gslbservice-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.GslbServiceDetailInventoryView.as_view(),
        name='gslbservice-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_GSLBSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/gslbservice-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.GslbServiceDetailInventoryView.as_view(),
        name='gslbservice-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_GSLBSERVICE"}),

    url(r'^poolgroup-inventory/?$',
        api.views_inventory.PoolGroupListInventoryView.as_view(),
        name='poolgroup-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_POOLGROUP"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/poolgroup-inventory/?$',
        api.views_inventory.PoolGroupListInventoryView.as_view(),
        name='poolgroup-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_POOLGROUP"}),
    url(r'^poolgroup-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.PoolGroupDetailInventoryView.as_view(),
        name='poolgroup-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_POOLGROUP"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/poolgroup-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.PoolGroupDetailInventoryView.as_view(),
        name='poolgroup-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_POOLGROUP"}),
    url(r'^poolgroup-inventory-summary/?$',
        api.views_inventory.PoolGroupSummaryInventoryView.as_view(),
        name='poolgroup-summary-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_POOLGROUP"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/poolgroup-inventory-summary/?$',
        api.views_inventory.PoolGroupSummaryInventoryView.as_view(),
        name='poolgroup-summary-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_POOLGROUP"}),

    url(r'^vsvip-inventory/?$',
        api.views_inventory.VsVipListInventoryView.as_view(),
        name='vsvip-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/vsvip-inventory/?$',
        api.views_inventory.VsVipListInventoryView.as_view(),
        name='vsvip-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^vsvip-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.VsVipDetailInventoryView.as_view(),
        name='vsvip-detail-inventory',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/vsvip-inventory/(?P<slug>[-\w.]+)/?$',
        api.views_inventory.VsVipDetailInventoryView.as_view(),
        name='vsvip-detail-inventory-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"})
)
