
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
    # hand crafted views
    #url(r'^$', 'api.views.tree_view'),
    #url(r'^index.json', 'api.views.tree_view'),
    url(r'linux_host_install/?$', 'api.views.linux_host_install'),
    url(r'dnslookup/(?P<server>[-\w\.]+)/?$', 'api.views.dns_lookup'),
    url('', include('api.urls_inventory')),
    url('', include('api.urls_configuration')),
    url('', include('api.urls_system')),
    # generated views
    url('', include('api.urls_application')),
    url('', include('api.urls_controller')),
    url('', include('api.urls_debug_controller')),
    url('', include('api.urls_debug_se')),
    url('', include('api.urls_placement')),
    url('', include('api.urls_common')),
    url('', include('api.urls_match')),
    url('', include('api.urls_vrf')),
    url('', include('api.urls_analysis')),
    # fake resource combining pool + vs
    url('', include('api.urls_vs_pool')),
    # only has subresources
    url('', include('api.urls_vs')),
    url('', include('api.urls_se')),
    url('', include('api.urls_se_group')),
    url('', include('api.urls_pool')),
    url('', include('api.urls_pool_group')),
    url('', include('api.urls_pool_group_deployment_policy')),
    url('', include('api.urls_priority_labels')),
    url('', include('api.urls_analytics_profile')),
    url('', include('api.urls_traffic_clone_profile')),
    url('', include('api.urls_network_policy')),
    url('', include('api.urls_waf_policy')),
    url('', include('api.urls_waf_policy_psm_group')),
    url('', include('api.urls_waf_profile')),
    url('', include('api.urls_error_page')),
    url('', include('api.urls_network_profile')),
    url('', include('api.urls_application_policy')),
    url('', include('api.urls_application_profile')),
    url('', include('api.urls_health_monitor')),
    url('', include('api.urls_ssl_custom')),
    url('', include('api.urls_ssl')),
    url('', include('api.urls_security_policy')),
    url('', include('api.urls_vi_mgr')),
    url('', include('api.urls_vi_mgr_status')),
    url('', include('api.urls_metrics_mgr')),
    url('', include('api.urls_autoscale_mgr')),
    url('', include('api.urls_clustering_custom')),
    url('', include('api.urls_seupgrade')),
    url('', include('api.urls_rebalance')),
    url('', include('api.urls_consistencycheck')),
    url('', include('api.urls_alerts')),
    url('', include('api.urls_alerts_custom')),
    url('', include('api.urls_fileservice')),
    url('', include('api.urls_network')),
    url('', include('api.urls_transaction_stats')),
    url('', include('api.urls_controller_properties')),
    url('', include('api.urls_se_properties')),
    url('', include('api.urls_vs_datascript')),
    url('', include('api.urls_techsupport')),
    url('', include('api.urls_techsupport_v2')),
    url('', include('api.urls_core')),
    url('', include('api.urls_debug_custom')),
    url('', include('api.urls_ui_error')),
    url('', include('api.urls_apic')),
    url('', include('api.urls_nsx')),
    url('', include('api.urls_job_db')),
    url('', include('api.urls_application_persistence_profile')),
    url('', include('api.urls_macro')),
    url('', include('api.urls_default_values')),
    url('', include('api.urls_log')),
    url('', include('api.urls_auth')),
    url('', include('api.urls_se_datastore_debug')),
    url('', include('api.urls_shard_server_debug')),
    url('', include('api.urls_secure_channel')),
    url('', include('api.urls_secure_channel_custom')),
    url('', include('api.urls_licensing_custom')),
    url('', include('api.urls_network_custom')),
    url('', include('api.urls_cloud_custom')),
    url('', include('api.urls_cloud_connector_custom')),
    url('', include('api.urls_cloud_connector_user_custom')),
    url('', include('api.urls_shard_custom')),
    url('', include('api.urls_snmp')),
    url('', include('api.urls_match_custom')),
    url('', include('api.urls_cloud_properties')),
    url('', include('api.urls_server_autoscale')),
    url('', include('api.urls_network_policy_custom')),
    url('', include('api.urls_inventory_controller')),
    url('', include('api.urls_webhook_custom')),
    url('', include('api.urls_micro_service')),
    url('', include('api.urls_ipam_dns_provider_profile')),
    url('', include('api.urls_hsm')),
    url('', include('api.urls_object_graph')),
    url('', include('api.urls_ipam_dns_provider_profile_custom')),
    url('', include('api.urls_gslb')),
    url('', include('api.urls_gslb_custom')),
    url('', include('api.urls_scheduler')),
    url('', include('api.urls_backup')),
    url('', include('api.urls_django')),
    url('', include('api.urls_webhook')),
    url('', include('api.urls_dns_policy')),
    url('', include('api.urls_l4_policy')),
    url('', include('api.urls_sc')),
    url('', include('api.urls_custom_ipam_dns_profile')),
    url('', include('api.urls_cluster_cloud_details')),
    url('', include('api.urls_jobmanager_custom')),
    url('', include('api.urls_security_mgr')),
    url('', include('api.urls_ping_agent_custom')),
    url('', include('api.urls_waf_custom')),
    url('', include('api.urls_se_policy')),
    url('', include('api.urls_nat_policy')),
    url('', include('api.urls_sso')),
    url('', include('api.urls_protocol_parser')),
)
