
############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

#GENERATED FILE 
#pylint:  skip-file
from django.conf.urls import patterns, include, url
import api.views_vs

urlpatterns = patterns('',
    
    url(r'^virtualservice/(?P<key>[-\w.]+)/scaleout/?$',
        api.views_vs.VirtualServiceScale_OutView.as_view(),
        name='virtualservicescale_outview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/scaleout/?$',
        api.views_vs.VirtualServiceScale_OutView.as_view(),
        name='virtualservicescale_outview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE" }),
    
    url(r'^virtualservice/(?P<key>[-\w.]+)/scalein/?$',
        api.views_vs.VirtualServiceScale_InView.as_view(),
        name='virtualservicescale_inview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/scalein/?$',
        api.views_vs.VirtualServiceScale_InView.as_view(),
        name='virtualservicescale_inview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE" }),
    
    url(r'^virtualservice/(?P<key>[-\w.]+)/migrate/?$',
        api.views_vs.VirtualServiceMigrateView.as_view(),
        name='virtualservicemigrateview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/migrate/?$',
        api.views_vs.VirtualServiceMigrateView.as_view(),
        name='virtualservicemigrateview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE" }),
    
    url(r'^virtualservice/(?P<key>[-\w.]+)/switchover/?$',
        api.views_vs.VirtualServiceSwitchoverView.as_view(),
        name='virtualserviceswitchoverview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/switchover/?$',
        api.views_vs.VirtualServiceSwitchoverView.as_view(),
        name='virtualserviceswitchoverview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE" }),
    
    url(r'^virtualservice/(?P<key>[-\w.]+)/resync/?$',
        api.views_vs.VirtualServiceResyncView.as_view(),
        name='virtualserviceresyncview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/resync/?$',
        api.views_vs.VirtualServiceResyncView.as_view(),
        name='virtualserviceresyncview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE" }),
    
    url(r'^virtualservice/(?P<key>[-\w.]+)/rotatekeys/?$',
        api.views_vs.VirtualServiceRotate_KeysView.as_view(),
        name='virtualservicerotate_keysview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/rotatekeys/?$',
        api.views_vs.VirtualServiceRotate_KeysView.as_view(),
        name='virtualservicerotate_keysview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE" }),
    
    url(r'^virtualservice/(?P<key>[-\w.]+)/apicplacement/?$',
        api.views_vs.VirtualServiceApicplacementView.as_view(),
        name='virtualserviceapicplacementview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/apicplacement/?$',
        api.views_vs.VirtualServiceApicplacementView.as_view(),
        name='virtualserviceapicplacementview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE" }),
    
    url(r'^virtualservice/(?P<key>[-\w.]+)/retryplacement/?$',
        api.views_vs.VirtualServiceRetryplacementView.as_view(),
        name='virtualserviceretryplacementview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/retryplacement/?$',
        api.views_vs.VirtualServiceRetryplacementView.as_view(),
        name='virtualserviceretryplacementview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE" }),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/dosstat/?$',
        api.views_vs.VsDosStatRuntimeView.as_view(),
        name='vsdosstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/dosstat/?$',
        api.views_vs.VsDosStatRuntimeView.as_view(),
        name='vsdosstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/clientsummary/?$',
        api.views_vs.ClientSummaryInternalView.as_view(),
        name='clientsummaryinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/clientsummary/?$',
        api.views_vs.ClientSummaryInternalView.as_view(),
        name='clientsummaryinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/connections/?$',
        api.views_vs.ConnectionDumpRuntimeView.as_view(),
        name='connectiondumpruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/connections/?$',
        api.views_vs.ConnectionDumpRuntimeView.as_view(),
        name='connectiondumpruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/connections/clear/?$',
        api.views_vs.ConnectionDumpRuntimeClearView.as_view(),
        name='connectiondumpruntimeclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/connections/clear/?$',
        api.views_vs.ConnectionDumpRuntimeClearView.as_view(),
        name='connectiondumpruntimeclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/geodbinternal/?$',
        api.views_vs.GeoDbInternalView.as_view(),
        name='geodbinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/geodbinternal/?$',
        api.views_vs.GeoDbInternalView.as_view(),
        name='geodbinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/keyval/?$',
        api.views_vs.KeyvalInternalView.as_view(),
        name='keyvalinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/keyval/?$',
        api.views_vs.KeyvalInternalView.as_view(),
        name='keyvalinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/keyval/clear/?$',
        api.views_vs.KeyvalInternalClearView.as_view(),
        name='keyvalinternalclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/keyval/clear/?$',
        api.views_vs.KeyvalInternalClearView.as_view(),
        name='keyvalinternalclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/httppolicyset/?$',
        api.views_vs.HTTPPolicySetInternalView.as_view(),
        name='httppolicysetinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/httppolicyset/?$',
        api.views_vs.HTTPPolicySetInternalView.as_view(),
        name='httppolicysetinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/cltracksummary/?$',
        api.views_vs.CltrackSummaryInternalView.as_view(),
        name='cltracksummaryinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/cltracksummary/?$',
        api.views_vs.CltrackSummaryInternalView.as_view(),
        name='cltracksummaryinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/sescaleoutstatus/?$',
        api.views_vs.VirtualServiceSeScaleoutStatusView.as_view(),
        name='virtualservicesescaleoutstatus-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/sescaleoutstatus/?$',
        api.views_vs.VirtualServiceSeScaleoutStatusView.as_view(),
        name='virtualservicesescaleoutstatus-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/placement/?$',
        api.views_vs.SeConsumerProtoView.as_view(),
        name='seconsumerproto-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/placement/?$',
        api.views_vs.SeConsumerProtoView.as_view(),
        name='seconsumerproto-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/userdefineddatascriptcounters/?$',
        api.views_vs.UserDefinedDataScriptCountersView.as_view(),
        name='userdefineddatascriptcounters-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/userdefineddatascriptcounters/?$',
        api.views_vs.UserDefinedDataScriptCountersView.as_view(),
        name='userdefineddatascriptcounters-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/userdefineddatascriptcounters/clear/?$',
        api.views_vs.UserDefinedDataScriptCountersClearView.as_view(),
        name='userdefineddatascriptcountersclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/userdefineddatascriptcounters/clear/?$',
        api.views_vs.UserDefinedDataScriptCountersClearView.as_view(),
        name='userdefineddatascriptcountersclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/gslbservicedetail/?$',
        api.views_vs.GslbServiceDetailView.as_view(),
        name='gslbservicedetail-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/gslbservicedetail/?$',
        api.views_vs.GslbServiceDetailView.as_view(),
        name='gslbservicedetail-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/runtime/detail/?$',
        api.views_vs.VirtualServiceRuntimeDetailView.as_view(),
        name='virtualserviceruntimedetail-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/runtime/detail/?$',
        api.views_vs.VirtualServiceRuntimeDetailView.as_view(),
        name='virtualserviceruntimedetail-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/stats/clear/?$',
        api.views_vs.VirtualServiceRuntimeDetailClearView.as_view(),
        name='virtualserviceruntimedetailclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/stats/clear/?$',
        api.views_vs.VirtualServiceRuntimeDetailClearView.as_view(),
        name='virtualserviceruntimedetailclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/networksecuritypolicy/detail/?$',
        api.views_vs.NetworkSecurityPolicyDetailView.as_view(),
        name='networksecuritypolicydetail-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/networksecuritypolicy/detail/?$',
        api.views_vs.NetworkSecurityPolicyDetailView.as_view(),
        name='networksecuritypolicydetail-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/gslbserviceinternal/?$',
        api.views_vs.GslbServiceInternalView.as_view(),
        name='gslbserviceinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/gslbserviceinternal/?$',
        api.views_vs.GslbServiceInternalView.as_view(),
        name='gslbserviceinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/gslbservicehmonstat/?$',
        api.views_vs.GslbServiceHmonStatView.as_view(),
        name='gslbservicehmonstat-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/gslbservicehmonstat/?$',
        api.views_vs.GslbServiceHmonStatView.as_view(),
        name='gslbservicehmonstat-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/keyvalsummary/?$',
        api.views_vs.KeyvalSummaryInternalView.as_view(),
        name='keyvalsummaryinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/keyvalsummary/?$',
        api.views_vs.KeyvalSummaryInternalView.as_view(),
        name='keyvalsummaryinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/traffic_clone_stats/?$',
        api.views_vs.TrafficCloneRuntimeView.as_view(),
        name='trafficcloneruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/traffic_clone_stats/?$',
        api.views_vs.TrafficCloneRuntimeView.as_view(),
        name='trafficcloneruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/httppolicysetstats/?$',
        api.views_vs.HTTPPolicySetStatsView.as_view(),
        name='httppolicysetstats-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/httppolicysetstats/?$',
        api.views_vs.HTTPPolicySetStatsView.as_view(),
        name='httppolicysetstats-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/httppolicysetstats/clear/?$',
        api.views_vs.HTTPPolicySetStatsClearView.as_view(),
        name='httppolicysetstatsclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/httppolicysetstats/clear/?$',
        api.views_vs.HTTPPolicySetStatsClearView.as_view(),
        name='httppolicysetstatsclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/runtime/?$',
        api.views_vs.VirtualServiceRuntimeSummaryView.as_view(),
        name='virtualserviceruntimesummary-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/runtime/?$',
        api.views_vs.VirtualServiceRuntimeSummaryView.as_view(),
        name='virtualserviceruntimesummary-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/client/?$',
        api.views_vs.ClientInternalView.as_view(),
        name='clientinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/client/?$',
        api.views_vs.ClientInternalView.as_view(),
        name='clientinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/client/clear/?$',
        api.views_vs.ClientInternalClearView.as_view(),
        name='clientinternalclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/client/clear/?$',
        api.views_vs.ClientInternalClearView.as_view(),
        name='clientinternalclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/candidatesehostlist/?$',
        api.views_vs.VsCandidateSeHostListView.as_view(),
        name='vscandidatesehostlist-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/candidatesehostlist/?$',
        api.views_vs.VsCandidateSeHostListView.as_view(),
        name='vscandidatesehostlist-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/dnstable/?$',
        api.views_vs.DnsTableView.as_view(),
        name='dnstable-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/dnstable/?$',
        api.views_vs.DnsTableView.as_view(),
        name='dnstable-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/geolocationinfo/?$',
        api.views_vs.GeoLocationInfoView.as_view(),
        name='geolocationinfo-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/geolocationinfo/?$',
        api.views_vs.GeoLocationInfoView.as_view(),
        name='geolocationinfo-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/gslbsiteinternal/?$',
        api.views_vs.GslbSiteInternalView.as_view(),
        name='gslbsiteinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/gslbsiteinternal/?$',
        api.views_vs.GslbSiteInternalView.as_view(),
        name='gslbsiteinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/runtime/internal/?$',
        api.views_vs.VirtualServiceInternalView.as_view(),
        name='virtualserviceinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/runtime/internal/?$',
        api.views_vs.VirtualServiceInternalView.as_view(),
        name='virtualserviceinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/cltrack/?$',
        api.views_vs.CltrackInternalView.as_view(),
        name='cltrackinternal-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/cltrack/?$',
        api.views_vs.CltrackInternalView.as_view(),
        name='cltrackinternal-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/cltrack/clear/?$',
        api.views_vs.CltrackInternalClearView.as_view(),
        name='cltrackinternalclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/cltrack/clear/?$',
        api.views_vs.CltrackInternalClearView.as_view(),
        name='cltrackinternalclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/networksecuritypolicystats/?$',
        api.views_vs.NetworkSecurityPolicyStatsView.as_view(),
        name='networksecuritypolicystats-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/networksecuritypolicystats/?$',
        api.views_vs.NetworkSecurityPolicyStatsView.as_view(),
        name='networksecuritypolicystats-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/authstats/?$',
        api.views_vs.VirtualServiceAuthStatsView.as_view(),
        name='virtualserviceauthstats-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/authstats/?$',
        api.views_vs.VirtualServiceAuthStatsView.as_view(),
        name='virtualserviceauthstats-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/authstats/clear/?$',
        api.views_vs.VirtualServiceAuthStatsClearView.as_view(),
        name='virtualserviceauthstatsclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/authstats/clear/?$',
        api.views_vs.VirtualServiceAuthStatsClearView.as_view(),
        name='virtualserviceauthstatsclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/udpstat/?$',
        api.views_vs.UdpStatRuntimeView.as_view(),
        name='udpstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/udpstat/?$',
        api.views_vs.UdpStatRuntimeView.as_view(),
        name='udpstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/l4policysetstats/?$',
        api.views_vs.L4PolicySetStatsView.as_view(),
        name='l4policysetstats-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/l4policysetstats/?$',
        api.views_vs.L4PolicySetStatsView.as_view(),
        name='l4policysetstats-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/l4policysetstats/clear/?$',
        api.views_vs.L4PolicySetStatsClearView.as_view(),
        name='l4policysetstatsclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/l4policysetstats/clear/?$',
        api.views_vs.L4PolicySetStatsClearView.as_view(),
        name='l4policysetstatsclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/httpstats/?$',
        api.views_vs.L7VirtualServiceStatsRuntimeView.as_view(),
        name='l7virtualservicestatsruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/httpstats/?$',
        api.views_vs.L7VirtualServiceStatsRuntimeView.as_view(),
        name='l7virtualservicestatsruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
                
    url(r'^virtualservice/(?P<key>[-\w.]+)/dnspolicystats/?$',
        api.views_vs.DnsPolicyStatsView.as_view(),
        name='dnspolicystats-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/dnspolicystats/?$',
        api.views_vs.DnsPolicyStatsView.as_view(),
        name='dnspolicystats-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
        
    url(r'^virtualservice/(?P<key>[-\w.]+)/dnspolicystats/clear/?$',
        api.views_vs.DnsPolicyStatsClearView.as_view(),
        name='dnspolicystatsclearview-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/dnspolicystats/clear/?$',
        api.views_vs.DnsPolicyStatsClearView.as_view(),
        name='dnspolicystatsclearview-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            
    url(r'^virtualservice/(?P<key>[-\w.]+)/tcpstat/?$',
        api.views_vs.TcpStatRuntimeView.as_view(),
        name='tcpstatruntime-detail',
        kwargs={'scoped': True, 'scope_visible': False, 'permission': "PERMISSION_VIRTUALSERVICE"}),
    url(r'^tenant/(?P<tenant>[-\w.]+)/virtualservice/(?P<key>[-\w.]+)/tcpstat/?$',
        api.views_vs.TcpStatRuntimeView.as_view(),
        name='tcpstatruntime-detail-scoped',
        kwargs={'scoped': True, 'scope_visible': True, 'permission': "PERMISSION_VIRTUALSERVICE"}),
            

)
